import type { EntityDef } from '../../parsers/entity.parser.js';

// TODO: Implement Python entity generator — EntityDef to Pydantic model + types + repo
export const generatePythonEntity = (_entity: EntityDef): string => {
  return `# @generated by flusk-lang — DO NOT EDIT\n# TODO: Python entity generator not yet implemented\n`;
};
