import type { FunctionDef } from '../../parsers/function.parser.js';

// TODO: Implement Python function generator — FunctionDef to .py function
export const generatePythonFunction = (_fn: FunctionDef): string => {
  return `# @generated by flusk-lang — DO NOT EDIT\n# TODO: Python function generator not yet implemented\n`;
};
