// @generated by flusk-lang — DO NOT EDIT

import { createFileRoute } from '@tanstack/react-router'
import React, { useEffect, useRef, useState } from 'react'

export const Route = createFileRoute('/about')({
  component: AboutPage,
  head: () => ({
    meta: [
      { title: 'About Us — Flusk' },
      { name: 'description', content: 'Learn about Flusk, the AI Adoption Platform' },
      { property: 'og:image', content: '/images/og-about.png' },
    ],
  }),
})

function AboutPage() {
  return (
    <main className="min-h-screen bg-background">
      {/* Skip nav — accessibility */}
      <a
        href="#main-content"
        className="sr-only focus:not-sr-only focus:absolute focus:left-4 focus:top-4 focus:z-50 focus:rounded-md focus:bg-primary focus:px-4 focus:py-2 focus:text-primary-foreground"
      >
        Skip to content
      </a>

      <div id="main-content">
        <HeroSection />
        <MissionSection />
        <MetricsSection />
        <PillarsSection />
        <TeamSection />
        <CTASection />
      </div>
    </main>
  )
}

/* ══════════════════════════════════════════
   Hero Section
   ══════════════════════════════════════════ */
function HeroSection() {
  return (
    <header className="flex flex-col items-center gap-3 px-4 pb-8 pt-16 text-center sm:pt-20 md:pb-12 md:pt-24 lg:pt-32">
      <h1 className="text-3xl font-extrabold tracking-tight sm:text-3xl md:text-4xl lg:text-5xl">
        About Flusk
      </h1>
      <p className="text-lg font-medium text-primary sm:text-xl">
        The AI Adoption Platform
      </p>
    </header>
  )
}

/* ══════════════════════════════════════════
   Mission Section
   ══════════════════════════════════════════ */
function MissionSection() {
  return (
    <section aria-label="Our Mission" className="mx-auto max-w-prose px-4 pb-12 text-center md:pb-16">
      <h2 className="mb-4 text-xl font-bold sm:text-2xl">Our Mission</h2>
      <p className="text-base leading-relaxed text-muted-foreground sm:text-lg">
        We believe every company deserves to get maximum value from AI. Today,
        organizations spend billions on AI tools with zero visibility into what works,
        what's wasted, and who's actually using them. Flusk changes that — turning AI
        chaos into AI adoption, and scattered spend into{' '}
        <strong className="text-foreground">30x output</strong>.
      </p>
    </section>
  )
}

/* ══════════════════════════════════════════
   Metrics Bar Chart — animates on viewport
   ══════════════════════════════════════════ */
const metrics = [
  { label: 'Enterprise AI Spend', value: 37, max: 50, unit: '$B', color: '#00E5FF' },
  { label: "Can't Track AI Usage", value: 87, max: 100, unit: '%', color: '#7c3aed' },
  { label: 'Output Multiplier', value: 30, max: 50, unit: 'x', color: '#00E5FF' },
  { label: 'Visibility for Most Orgs', value: 0, max: 100, unit: '%', color: '#ef4444' },
]

function MetricsSection() {
  const ref = useRef<HTMLDivElement>(null)
  const [visible, setVisible] = useState(false)

  useEffect(() => {
    const el = ref.current
    if (!el) return
    const obs = new IntersectionObserver(
      ([entry]) => { if (entry.isIntersecting) setVisible(true) },
      { threshold: 0.3 }
    )
    obs.observe(el)
    return () => obs.disconnect()
  }, [])

  return (
    <section
      ref={ref}
      aria-label="Company metrics"
      className="mx-auto max-w-3xl px-4 pb-12 md:pb-16"
    >
      <h2 className="mb-6 text-center text-xl font-bold sm:text-2xl">By The Numbers</h2>

      {/* Mobile: vertical bars, md+: horizontal */}
      <div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-center md:gap-6">
        {metrics.map((m) => {
          const pct = (m.value / m.max) * 100
          return (
            <div key={m.label} className="flex flex-col items-center gap-2 md:flex-1">
              {/* Horizontal bar (mobile) */}
              <div className="flex w-full items-center gap-3 md:hidden">
                <span className="w-40 shrink-0 text-right text-sm text-muted-foreground">{m.label}</span>
                <div className="h-8 flex-1 overflow-hidden rounded-md bg-muted">
                  <div
                    className="flex h-full items-center justify-end rounded-md px-2 text-xs font-bold text-white transition-all duration-1000 ease-out"
                    style={{
                      width: visible ? `${Math.max(pct, 5)}%` : '0%',
                      backgroundColor: m.color,
                    }}
                    role="meter"
                    aria-valuenow={m.value}
                    aria-valuemin={0}
                    aria-valuemax={m.max}
                    aria-label={`${m.label}: ${m.value}${m.unit}`}
                  >
                    {m.value}{m.unit}
                  </div>
                </div>
              </div>

              {/* Vertical bar (md+) */}
              <div className="hidden md:flex md:h-48 md:w-full md:flex-col md:items-center md:justify-end">
                <span className="mb-1 text-sm font-bold" style={{ color: m.color }}>
                  {m.value}{m.unit}
                </span>
                <div className="w-full overflow-hidden rounded-t-md bg-muted" style={{ height: '100%' }}>
                  <div
                    className="w-full rounded-t-md transition-all duration-1000 ease-out"
                    style={{
                      height: visible ? `${Math.max(pct, 3)}%` : '0%',
                      backgroundColor: m.color,
                      marginTop: 'auto',
                      position: 'relative',
                      top: visible ? `${100 - Math.max(pct, 3)}%` : '100%',
                    }}
                    role="meter"
                    aria-valuenow={m.value}
                    aria-valuemin={0}
                    aria-valuemax={m.max}
                    aria-label={`${m.label}: ${m.value}${m.unit}`}
                  />
                </div>
                <span className="mt-2 text-center text-xs text-muted-foreground">{m.label}</span>
              </div>
            </div>
          )
        })}
      </div>
    </section>
  )
}

/* ══════════════════════════════════════════
   Three Pillars Feature Grid
   ══════════════════════════════════════════ */
const pillars = [
  {
    icon: 'eye',
    title: 'Observability',
    description: 'Real-time dashboards, cost attribution, shadow AI detection. See everything across all your AI providers.',
  },
  {
    icon: 'zap',
    title: 'Action',
    description: 'No-code solution builder, smart model routing, deploy to Slack, WhatsApp & Web in one click.',
  },
  {
    icon: 'target',
    title: 'Engagement',
    description: 'In-context nudges at friction points. Push the right AI tool to the right person at the right time.',
  },
]

function PillarsSection() {
  return (
    <section aria-label="What we do" className="mx-auto max-w-5xl px-4 pb-12 md:pb-16">
      <h2 className="mb-6 text-center text-xl font-bold sm:text-2xl">Three Pillars</h2>
      <div className="grid gap-4 sm:grid-cols-1 md:grid-cols-3 md:gap-6">
        {pillars.map((p) => (
          <article
            key={p.title}
            className="rounded-xl border bg-card p-5 shadow-sm transition-shadow hover:shadow-md sm:p-6"
          >
            <div className="mb-3 flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10 text-primary">
              <PillarIcon name={p.icon} />
            </div>
            <h3 className="mb-2 text-base font-bold sm:text-lg">{p.title}</h3>
            <p className="text-sm leading-relaxed text-muted-foreground">{p.description}</p>
          </article>
        ))}
      </div>
    </section>
  )
}

/* ══════════════════════════════════════════
   Team Grid
   ══════════════════════════════════════════ */
const team = [
  { name: 'Adir Ben Yosef', role: 'CEO', bio: 'WalkMe 6yr, Guesty, Payzen', avatar: '/images/team/adir.jpg', initials: 'AB' },
  { name: 'Yarden Cohen', role: 'CRO', bio: 'WalkMe, Akeyless', avatar: '/images/team/yarden.jpg', initials: 'YC' },
  { name: 'Nophry Lev Ari', role: 'CMO', bio: 'WalkMe 12yr', avatar: '/images/team/nophry.jpg', initials: 'NL' },
  { name: 'Omri Katz', role: 'CTO', bio: 'Payzen, Kaltura', avatar: '/images/team/omri.jpg', initials: 'OK' },
]

function TeamSection() {
  return (
    <section aria-label="Our team" className="mx-auto max-w-4xl px-4 pb-12 md:pb-16">
      <h2 className="mb-2 text-center text-xl font-bold sm:text-2xl">The Team</h2>
      <p className="mb-6 text-center text-sm text-muted-foreground">
        The team that built Digital Adoption is now building AI Adoption.
      </p>
      <div className="grid grid-cols-2 gap-4 md:grid-cols-4 md:gap-6">
        {team.map((m) => (
          <article key={m.name} className="flex flex-col items-center gap-2 rounded-xl border bg-card p-4 text-center shadow-sm">
            <TeamAvatar name={m.name} initials={m.initials} avatar={m.avatar} />
            <div>
              <p className="text-sm font-bold">{m.name}</p>
              <p className="text-xs font-medium text-primary">{m.role}</p>
              <p className="mt-1 text-xs text-muted-foreground">{m.bio}</p>
            </div>
          </article>
        ))}
      </div>
    </section>
  )
}

function TeamAvatar({ name, initials, avatar }: { name: string; initials: string; avatar: string }) {
  const [error, setError] = useState(false)

  if (error || !avatar) {
    return (
      <div
        className="flex h-16 w-16 items-center justify-center rounded-full bg-primary/10 text-sm font-bold text-primary"
        role="img"
        aria-label={`${name} avatar`}
      >
        {initials}
      </div>
    )
  }

  return (
    <img
      src={avatar}
      alt={`${name} profile photo`}
      loading="lazy"
      onError={() => setError(true)}
      className="h-16 w-16 rounded-full object-cover"
    />
  )
}

/* ══════════════════════════════════════════
   CTA Section
   ══════════════════════════════════════════ */
function CTASection() {
  return (
    <section className="mx-auto max-w-2xl px-4 pb-16 pt-4 text-center md:pb-24">
      <h2 className="mb-6 text-xl font-bold sm:text-2xl md:text-3xl">
        Ready to multiply your AI output?
      </h2>
      <div className="flex flex-col items-center gap-3 sm:flex-row sm:justify-center">
        <a
          href="/signup"
          className="inline-flex items-center justify-center rounded-lg bg-primary px-6 py-3 text-base font-semibold text-primary-foreground shadow-sm transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
        >
          Get Started — Free
        </a>
        <a
          href="https://github.com/fluskapp/flusk-dev"
          target="_blank"
          rel="noopener noreferrer"
          className="inline-flex items-center justify-center gap-2 rounded-lg border px-6 py-3 text-base font-semibold transition-colors hover:bg-accent focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
        >
          <svg className="h-5 w-5" viewBox="0 0 24 24" fill="currentColor"><path d="M12 0C5.37 0 0 5.37 0 12c0 5.31 3.435 9.795 8.205 11.385.6.105.825-.255.825-.57 0-.285-.015-1.23-.015-2.235-3.015.555-3.795-.735-4.035-1.41-.135-.345-.72-1.41-1.23-1.695-.42-.225-1.02-.78-.015-.795.945-.015 1.62.87 1.845 1.23 1.08 1.815 2.805 1.305 3.495.99.105-.78.42-1.305.765-1.605-2.67-.3-5.46-1.335-5.46-5.925 0-1.305.465-2.385 1.23-3.225-.12-.3-.54-1.53.12-3.18 0 0 1.005-.315 3.3 1.23.96-.27 1.98-.405 3-.405s2.04.135 3 .405c2.295-1.56 3.3-1.23 3.3-1.23.66 1.65.24 2.88.12 3.18.765.84 1.23 1.905 1.23 3.225 0 4.605-2.805 5.625-5.475 5.925.435.375.81 1.095.81 2.22 0 1.605-.015 2.895-.015 3.3 0 .315.225.69.825.57A12.02 12.02 0 0024 12c0-6.63-5.37-12-12-12z"/></svg>
          View on GitHub
        </a>
      </div>
    </section>
  )
}

/* ══════════════════════════════════════════
   Pillar Icons (inline SVG)
   ══════════════════════════════════════════ */
function PillarIcon({ name }: { name: string }) {
  const props = { className: 'h-5 w-5', viewBox: '0 0 24 24', fill: 'none', stroke: 'currentColor', strokeWidth: 2, strokeLinecap: 'round' as const, strokeLinejoin: 'round' as const }

  switch (name) {
    case 'eye':
      return <svg {...props}><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8S1 12 1 12z" /><circle cx="12" cy="12" r="3" /></svg>
    case 'zap':
      return <svg {...props}><polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2" /></svg>
    case 'target':
      return <svg {...props}><circle cx="12" cy="12" r="10" /><circle cx="12" cy="12" r="6" /><circle cx="12" cy="12" r="2" /></svg>
    default:
      return null
  }
}
