import { mkdir, writeFile as writeFileFs } from 'node:fs/promises';
import { join } from 'node:path';
import type { FluskSchema, GenerationResult } from '../../parsers/saas-schema.parser.js';

const HEADER = '// @generated by flusk-lang — DO NOT EDIT';

function toPascal(name: string): string {
  return name
    .replace(/[\s\-_]+(.)/g, (_: string, c: string) => c.toUpperCase())
    .replace(/^(.)/, (_: string, c: string) => c.toUpperCase());
}

function toCamel(name: string): string {
  const p = toPascal(name);
  return p.charAt(0).toLowerCase() + p.slice(1);
}

/**
 * Detect route schemas by directory or by having operations + basePath.
 */
export function isRouteSchema(schema: FluskSchema): boolean {
  const rawDir = schema._metadata?.directory ?? '';
  const topDir = rawDir.split('/')[0] ?? rawDir;
  if (topDir === 'routes') return true;
  const s = schema as unknown as Record<string, unknown>;
  return !!(s['operations']) && !!(s['basePath']);
}

function apiClientTemplate(): string {
  return `${HEADER}

const BASE_URL =
  typeof import.meta !== 'undefined' && (import.meta as unknown as Record<string, unknown>)['env'] != null
    ? (String(((import.meta as unknown as Record<string, unknown>)['env'] as unknown as Record<string, unknown>)['VITE_API_URL'] ?? 'http://localhost:3042'))
    : 'http://localhost:3042';

export const apiClient = {
  async get<T>(url: string, opts?: { params?: Record<string, unknown> }): Promise<T> {
    const fullUrl = new URL(url.startsWith('http') ? url : BASE_URL + url);
    if (opts?.params) {
      Object.entries(opts.params).forEach(([k, v]) => {
        if (v !== undefined && v !== null) fullUrl.searchParams.set(k, String(v));
      });
    }
    const res = await fetch(fullUrl.toString(), { credentials: 'include' });
    if (!res.ok) throw new Error(\`API \${res.status}: \${res.statusText}\`);
    return res.json() as Promise<T>;
  },

  async post<T>(url: string, body: unknown): Promise<T> {
    const res = await fetch(BASE_URL + url, {
      method: 'POST',
      credentials: 'include',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(body),
    });
    if (!res.ok) throw new Error(\`API \${res.status}: \${res.statusText}\`);
    return res.json() as Promise<T>;
  },

  async put<T>(url: string, body: unknown): Promise<T> {
    const res = await fetch(BASE_URL + url, {
      method: 'PUT',
      credentials: 'include',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(body),
    });
    if (!res.ok) throw new Error(\`API \${res.status}: \${res.statusText}\`);
    return res.json() as Promise<T>;
  },

  async patch<T>(url: string, body: unknown): Promise<T> {
    const res = await fetch(BASE_URL + url, {
      method: 'PATCH',
      credentials: 'include',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(body),
    });
    if (!res.ok) throw new Error(\`API \${res.status}: \${res.statusText}\`);
    return res.json() as Promise<T>;
  },

  async delete(url: string): Promise<void> {
    const res = await fetch(BASE_URL + url, {
      method: 'DELETE',
      credentials: 'include',
    });
    if (!res.ok) throw new Error(\`API \${res.status}: \${res.statusText}\`);
  },
};
`;
}

interface RouteOperation {
  method: string;
  path: string;
  call?: string;
  input?: string;
  description?: string;
  with?: Record<string, unknown>;
}

function hasIdParam(op: RouteOperation): boolean {
  return op.path.includes(':id') || op.path.includes(':');
}

function getEntityName(route: FluskSchema): string {
  const s = route as unknown as Record<string, unknown>;
  if (s['entity']) return toPascal(String(s['entity']));
  const name = route.name;
  if (name.endsWith('s')) return toPascal(name.slice(0, -1));
  return toPascal(name);
}

function generateHookFile(route: FluskSchema): string {
  const s = route as unknown as Record<string, unknown>;
  const routeName = route.name;
  const basePath = String(s['basePath'] ?? `/api/${routeName}`);
  const entityName = getEntityName(route);
  const operations = (s['operations'] ?? []) as RouteOperation[];
  const keysVar = toCamel(routeName) + 'Keys';
  const hookPrefix = toPascal(routeName);

  const listOp = operations.find((o) => o.method === 'GET' && !hasIdParam(o));
  const getOp = operations.find((o) => o.method === 'GET' && hasIdParam(o));
  const createOp = operations.find((o) => o.method === 'POST' && o.path === '/');
  const updateOp = operations.find(
    (o) => (o.method === 'PUT' || o.method === 'PATCH') && hasIdParam(o)
  );
  const deleteOp = operations.find((o) => o.method === 'DELETE' && hasIdParam(o));

  const actionOps = operations.filter((o) => o.method === 'POST' && o.path !== '/');

  let code = `${HEADER}
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import type { ${entityName}, Create${entityName}, Update${entityName} } from '../types/${entityName}';
import { apiClient } from '../lib/api-client';

export const ${keysVar} = {
  all: ['${routeName}'] as const,
  detail: (id: string) => ['${routeName}', id] as const,
} as const;

`;

  if (listOp) {
    code += `export function use${hookPrefix}(params?: Record<string, unknown>) {
  return useQuery({
    queryKey: ${keysVar}.all,
    queryFn: () => apiClient.get<${entityName}[]>('${basePath}', { params }),
  });
}

`;
  }

  if (getOp) {
    code += `export function use${entityName}(id: string) {
  return useQuery({
    queryKey: ${keysVar}.detail(id),
    queryFn: () => apiClient.get<${entityName}>(\`${basePath}/\${id}\`),
    enabled: !!id,
  });
}

`;
  }

  if (createOp) {
    code += `export function useCreate${entityName}() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (data: Create${entityName}) => apiClient.post<${entityName}>('${basePath}', data),
    onSuccess: () => qc.invalidateQueries({ queryKey: ${keysVar}.all }),
  });
}

`;
  }

  if (updateOp) {
    const method = updateOp.method === 'PUT' ? 'put' : 'patch';
    code += `export function useUpdate${entityName}(id: string) {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (data: Update${entityName}) =>
      apiClient.${method}<${entityName}>(\`${basePath}/\${id}\`, data),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ${keysVar}.all });
      qc.invalidateQueries({ queryKey: ${keysVar}.detail(id) });
    },
  });
}

`;
  }

  if (deleteOp) {
    code += `export function useDelete${entityName}() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (id: string) => apiClient.delete(\`${basePath}/\${id}\`),
    onSuccess: () => qc.invalidateQueries({ queryKey: ${keysVar}.all }),
  });
}

`;
  }

  for (const op of actionOps) {
    const callName = toPascal(op.call ?? 'action');
    const inputType = op.input ?? 'Record<string, unknown>';
    const opPath = op.path;

    if (hasIdParam(op)) {
      const pathWithId = (basePath + opPath).replace(':id', '${params.id}');
      code += `export function use${callName}() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (params: { id: string } & Partial<${inputType}>) =>
      apiClient.post(\`${pathWithId}\`, params),
    onSuccess: () => qc.invalidateQueries({ queryKey: ${keysVar}.all }),
  });
}

`;
    } else {
      const fullPath = basePath + opPath;
      code += `export function use${callName}() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (data: ${inputType}) => apiClient.post('${fullPath}', data),
    onSuccess: () => qc.invalidateQueries({ queryKey: ${keysVar}.all }),
  });
}

`;
    }
  }

  return code;
}

export class APIClientGenerator {
  async generate(schemas: FluskSchema[], outputDir: string): Promise<GenerationResult> {
    const result: GenerationResult = { filesGenerated: 0, errors: [], warnings: [] };

    const routes = schemas.filter(isRouteSchema);
    if (routes.length === 0) {
      result.warnings.push('APIClientGenerator: No route schemas found (add YAML files to a routes/ directory)');
      return result;
    }

    const libDir = join(outputDir, 'lib');
    const hooksDir = join(outputDir, 'hooks');
    await mkdir(libDir, { recursive: true });
    await mkdir(hooksDir, { recursive: true });

    await writeFileFs(join(libDir, 'api-client.ts'), apiClientTemplate(), 'utf-8');
    result.filesGenerated++;

    const barrelExports: string[] = [];

    for (const route of routes) {
      try {
        const code = generateHookFile(route);
        const fileName = `use${toPascal(route.name)}.ts`;
        await writeFileFs(join(hooksDir, fileName), code, 'utf-8');
        result.filesGenerated++;
        barrelExports.push(`export * from './use${toPascal(route.name)}';`);
      } catch (err) {
        result.errors.push(
          `APIClientGenerator: Failed for route ${route.name}: ${err instanceof Error ? err.message : String(err)}`
        );
      }
    }

    await writeFileFs(
      join(hooksDir, 'index.ts'),
      `${HEADER}\n\n${barrelExports.join('\n')}\n`,
      'utf-8'
    );
    result.filesGenerated++;

    return result;
  }
}
