import { mkdir, writeFile as writeFileFs } from 'node:fs/promises';
import { join } from 'node:path';
import type { FluskSchema, GenerationResult } from '../../parsers/saas-schema.parser.js';

const HEADER = '// @generated by flusk-lang — DO NOT EDIT';

function toPascal(name: string): string {
  return name
    .replace(/[\s\-_]+(.)/g, (_: string, c: string) => c.toUpperCase())
    .replace(/^(.)/, (_: string, c: string) => c.toUpperCase());
}

function toCamel(name: string): string {
  const p = toPascal(name);
  return p.charAt(0).toLowerCase() + p.slice(1);
}

/**
 * Detect route schemas by directory or by having operations + basePath.
 */
export function isRouteSchema(schema: FluskSchema): boolean {
  const rawDir = schema._metadata?.directory ?? '';
  const topDir = rawDir.split('/')[0] ?? rawDir;
  if (topDir === 'routes') return true;
  const s = schema as unknown as Record<string, unknown>;
  return !!(s['operations']) && !!(s['basePath']);
}

function apiClientTemplate(): string {
  return `${HEADER}

const BASE_URL =
  typeof import.meta !== 'undefined' && (import.meta as unknown as Record<string, unknown>)['env'] != null
    ? (String(((import.meta as unknown as Record<string, unknown>)['env'] as unknown as Record<string, unknown>)['VITE_API_URL'] ?? 'http://localhost:3042'))
    : 'http://localhost:3042';

export const apiClient = {
  async get<T>(url: string, opts?: { params?: Record<string, unknown> }): Promise<T> {
    const fullUrl = new URL(url.startsWith('http') ? url : BASE_URL + url);
    if (opts?.params) {
      Object.entries(opts.params).forEach(([k, v]) => {
        if (v !== undefined && v !== null) fullUrl.searchParams.set(k, String(v));
      });
    }
    const res = await fetch(fullUrl.toString(), { credentials: 'include' });
    if (!res.ok) throw new Error(\`API \${res.status}: \${res.statusText}\`);
    return res.json() as Promise<T>;
  },

  async post<T>(url: string, body: unknown): Promise<T> {
    const res = await fetch(BASE_URL + url, {
      method: 'POST',
      credentials: 'include',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(body),
    });
    if (!res.ok) throw new Error(\`API \${res.status}: \${res.statusText}\`);
    return res.json() as Promise<T>;
  },

  async put<T>(url: string, body: unknown): Promise<T> {
    const res = await fetch(BASE_URL + url, {
      method: 'PUT',
      credentials: 'include',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(body),
    });
    if (!res.ok) throw new Error(\`API \${res.status}: \${res.statusText}\`);
    return res.json() as Promise<T>;
  },

  async patch<T>(url: string, body: unknown): Promise<T> {
    const res = await fetch(BASE_URL + url, {
      method: 'PATCH',
      credentials: 'include',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(body),
    });
    if (!res.ok) throw new Error(\`API \${res.status}: \${res.statusText}\`);
    return res.json() as Promise<T>;
  },

  async delete(url: string): Promise<void> {
    const res = await fetch(BASE_URL + url, {
      method: 'DELETE',
      credentials: 'include',
    });
    if (!res.ok) throw new Error(\`API \${res.status}: \${res.statusText}\`);
  },
};
`;
}

interface RouteOperation {
  method: string;
  path: string;
  call?: string;
  input?: string;
  description?: string;
  with?: Record<string, unknown>;
}

function hasIdParam(op: RouteOperation): boolean {
  return op.path.includes(':id') || op.path.includes(':');
}

function getEntityName(route: FluskSchema): string {
  const s = route as unknown as Record<string, unknown>;
  if (s['entity']) return toPascal(String(s['entity']));
  const name = route.name;
  if (name.endsWith('s')) return toPascal(name.slice(0, -1));
  return toPascal(name);
}

function generateHookFile(route: FluskSchema): string {
  const s = route as unknown as Record<string, unknown>;
  const routeName = route.name;
  const basePath = String(s['basePath'] ?? `/api/${routeName}`);
  const entityName = getEntityName(route);
  const operations = (s['operations'] ?? []) as RouteOperation[];
  const keysVar = toCamel(routeName) + 'Keys';
  const hookPrefix = toPascal(routeName);

  const listOp = operations.find((o) => o.method === 'GET' && !hasIdParam(o));
  const getOp = operations.find((o) => o.method === 'GET' && hasIdParam(o));
  const createOp = operations.find((o) => o.method === 'POST' && o.path === '/');
  const updateOp = operations.find(
    (o) => (o.method === 'PUT' || o.method === 'PATCH') && hasIdParam(o)
  );
  const deleteOp = operations.find((o) => o.method === 'DELETE' && hasIdParam(o));

  const actionOps = operations.filter((o) => o.method === 'POST' && o.path !== '/');

  let code = `${HEADER}
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import type { ${entityName}, Create${entityName}, Update${entityName} } from '../types/${entityName}';
import { apiClient } from '../lib/api-client';

export const ${keysVar} = {
  all: ['${routeName}'] as const,
  detail: (id: string) => ['${routeName}', id] as const,
} as const;

`;

  if (listOp) {
    code += `export function use${hookPrefix}(params?: Record<string, unknown>) {
  return useQuery({
    queryKey: ${keysVar}.all,
    queryFn: () => apiClient.get<${entityName}[]>('${basePath}', { params }),
  });
}

`;
  }

  if (getOp) {
    code += `export function use${entityName}(id: string) {
  return useQuery({
    queryKey: ${keysVar}.detail(id),
    queryFn: () => apiClient.get<${entityName}>(\`${basePath}/\${id}\`),
    enabled: !!id,
  });
}

`;
  }

  if (createOp) {
    code += `export function useCreate${entityName}() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (data: Create${entityName}) => apiClient.post<${entityName}>('${basePath}', data),
    onSuccess: () => qc.invalidateQueries({ queryKey: ${keysVar}.all }),
  });
}

`;
  }

  if (updateOp) {
    const method = updateOp.method === 'PUT' ? 'put' : 'patch';
    code += `export function useUpdate${entityName}(id: string) {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (data: Update${entityName}) =>
      apiClient.${method}<${entityName}>(\`${basePath}/\${id}\`, data),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ${keysVar}.all });
      qc.invalidateQueries({ queryKey: ${keysVar}.detail(id) });
    },
  });
}

`;
  }

  if (deleteOp) {
    code += `export function useDelete${entityName}() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (id: string) => apiClient.delete(\`${basePath}/\${id}\`),
    onSuccess: () => qc.invalidateQueries({ queryKey: ${keysVar}.all }),
  });
}

`;
  }

  for (const op of actionOps) {
    const callName = toPascal(op.call ?? 'action');
    const inputType = op.input ?? 'Record<string, unknown>';
    const opPath = op.path;

    if (hasIdParam(op)) {
      const pathWithId = (basePath + opPath).replace(':id', '${params.id}');
      code += `export function use${callName}() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (params: { id: string } & Partial<${inputType}>) =>
      apiClient.post(\`${pathWithId}\`, params),
    onSuccess: () => qc.invalidateQueries({ queryKey: ${keysVar}.all }),
  });
}

`;
    } else {
      const fullPath = basePath + opPath;
      code += `export function use${callName}() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (data: ${inputType}) => apiClient.post('${fullPath}', data),
    onSuccess: () => qc.invalidateQueries({ queryKey: ${keysVar}.all }),
  });
}

`;
    }
  }

  return code;
}

// ─── View-based hook generation ──────────────────────────────────────

function isViewSchema(schema: FluskSchema): boolean {
  const rawDir = schema._metadata?.directory ?? '';
  const topDir = rawDir.split('/')[0] ?? rawDir;
  if (topDir === 'views') return true;
  const s = schema as unknown as Record<string, unknown>;
  return !!s['route'] && !!s['sections'];
}

/** Extract all unique entity sources from a view's sections (recursively) */
function extractSources(sections: unknown[]): Set<string> {
  const sources = new Set<string>();
  function walk(obj: unknown): void {
    if (!obj || typeof obj !== 'object') return;
    if (Array.isArray(obj)) { obj.forEach(walk); return; }
    const rec = obj as Record<string, unknown>;
    if (typeof rec['source'] === 'string') {
      const src = rec['source'] as string;
      // Extract entity name from "entity.field" pattern (e.g., "solutions.list" → "solutions")
      const entity = src.split('.')[0]!;
      if (entity && !entity.includes('API') && !entity.includes('Form') && entity !== 'filters') {
        sources.add(entity);
      }
    }
    for (const v of Object.values(rec)) walk(v);
  }
  walk(sections);
  return sources;
}

/** Map entity source names to Platformatic API endpoints */
function entityToEndpoint(entity: string): string {
  // Platformatic uses plural snake_case: solutions, events, connectors, etc.
  return `/api/${entity.replace(/([A-Z])/g, '_$1').toLowerCase()}`;
}

function generateViewHookFile(view: FluskSchema, entitySchemas: FluskSchema[]): string {
  const viewName = view.name.replace(/[\s\-]+/g, '');
  const hookName = `use${viewName}`;
  const s = view as unknown as Record<string, unknown>;
  const sections = (s['sections'] ?? []) as unknown[];
  const sources = extractSources(sections);

  // Find which entities have real API endpoints
  const entityNames = new Set(entitySchemas.map(e => e.name.toLowerCase().replace(/[\s\-_]+/g, '')));
  const knownEntities = ['solutions', 'events', 'connectors', 'agents', 'automations', 'deployables'];

  // Determine which real API calls we need
  const neededApis = new Set<string>();
  const viewWords = view.name.toLowerCase().split(/[\s\-]+/);
  const lastWord = viewWords[viewWords.length - 1] ?? '';
  const firstWord = viewWords[0] ?? '';

  // Direct entity sources
  for (const src of sources) {
    const normalized = src.toLowerCase().replace(/[\s\-_]+/g, '');
    if (knownEntities.includes(src) || entityNames.has(normalized) || entityNames.has(normalized.replace(/s$/, ''))) {
      neededApis.add(src);
    }
  }

  // Derive from view name if no direct entities
  if (neededApis.size === 0) {
    if (knownEntities.includes(lastWord)) {
      neededApis.add(lastWord);
    } else if (firstWord === 'observe' || ['dashboard', 'analytics', 'compliance'].includes(lastWord)) {
      neededApis.add('solutions');
      neededApis.add('events');
    }
  }

  // Build the data mapping — pages access data by source namespace (data.solutions, data.stats, etc.)
  // We fetch from real APIs and map results to the namespaces the page expects
  const apiCalls: string[] = [];
  const apiNames: string[] = [];
  for (const api of neededApis) {
    apiCalls.push(`      apiClient.get<any[]>('${entityToEndpoint(api)}').catch(() => [])`);
    apiNames.push(api);
  }

  // Map fetched data to all namespaces the view uses
  const dataFields: string[] = [];
  for (let i = 0; i < apiNames.length; i++) {
    dataFields.push(`      ${apiNames[i]}: results[${i}]`);
  }
  // For abstract namespaces (stats, observe, analytics, compliance), provide empty objects
  // so the page doesn't crash — these need real aggregation endpoints eventually
  for (const src of sources) {
    if (!neededApis.has(src) && src !== 'filters' && src !== 'event' && src !== 'connector') {
      dataFields.push(`      ${src}: {}`);
    }
  }

  if (apiCalls.length === 0) {
    // Fallback: return empty data for views that don't map to entities (landing, login)
    return `${HEADER}
// View hook for ${view.name} — no entity endpoints detected
export function ${hookName}(): { data: Record<string, any>; isLoading: boolean } {
  return { data: {}, isLoading: false };
}
`;
  }

  return `${HEADER}
import { useQuery } from '@tanstack/react-query';
import { apiClient } from '../lib/api-client';

export function ${hookName}() {
  return useQuery({
    queryKey: ['${viewName}'],
    queryFn: async () => {
      const results = await Promise.all([
${apiCalls.join(',\n')}
      ]);
      return {
${dataFields.join(',\n')}
      };
    },
  });
}
`;
}

export class APIClientGenerator {
  async generate(schemas: FluskSchema[], outputDir: string): Promise<GenerationResult> {
    const result: GenerationResult = { filesGenerated: 0, errors: [], warnings: [] };

    const libDir = join(outputDir, 'lib');
    const hooksDir = join(outputDir, 'hooks');
    await mkdir(libDir, { recursive: true });
    await mkdir(hooksDir, { recursive: true });

    // Always write api-client
    await writeFileFs(join(libDir, 'api-client.ts'), apiClientTemplate(), 'utf-8');
    result.filesGenerated++;

    const barrelExports: string[] = [];
    const writtenHooks = new Set<string>();

    // 1. Generate hooks from route schemas (explicit CRUD operations)
    const routes = schemas.filter(isRouteSchema);
    for (const route of routes) {
      try {
        const code = generateHookFile(route);
        const fileName = `use${toPascal(route.name)}.ts`;
        await writeFileFs(join(hooksDir, fileName), code, 'utf-8');
        result.filesGenerated++;
        barrelExports.push(`export * from './use${toPascal(route.name)}';`);
        writtenHooks.add(toPascal(route.name));
      } catch (err) {
        result.errors.push(
          `APIClientGenerator: Failed for route ${route.name}: ${err instanceof Error ? err.message : String(err)}`
        );
      }
    }

    // 2. Generate hooks from view schemas (fetch data for pages)
    const views = schemas.filter(isViewSchema);
    const entitySchemas = schemas.filter(s => s.type === 'entity');

    for (const view of views) {
      const viewName = view.name.replace(/[\s\-]+/g, '');
      if (writtenHooks.has(viewName)) continue; // Don't overwrite route-based hooks

      try {
        const code = generateViewHookFile(view, entitySchemas);
        const fileName = `use${viewName}.ts`;
        await writeFileFs(join(hooksDir, fileName), code, 'utf-8');
        result.filesGenerated++;
        barrelExports.push(`export { use${viewName} } from './use${viewName}';`);
        writtenHooks.add(viewName);
      } catch (err) {
        result.errors.push(
          `APIClientGenerator: Failed for view ${view.name}: ${err instanceof Error ? err.message : String(err)}`
        );
      }
    }

    // Write barrel
    await writeFileFs(
      join(hooksDir, 'index.ts'),
      `${HEADER}\n\n${barrelExports.join('\n')}\n`,
      'utf-8'
    );
    result.filesGenerated++;

    return result;
  }
}
