import { mkdir, writeFile as writeFileFs } from 'node:fs/promises';
import { join } from 'node:path';
import type { FluskSchema, GenerationResult } from '../../parsers/saas-schema.parser.js';

const HEADER = '// @generated by flusk-lang — DO NOT EDIT';

function toPascal(name: string): string {
  return name
    .replace(/[\s\-_]+(.)/g, (_: string, c: string) => c.toUpperCase())
    .replace(/^(.)/, (_: string, c: string) => c.toUpperCase());
}

function toCamel(name: string): string {
  const p = toPascal(name);
  return p.charAt(0).toLowerCase() + p.slice(1);
}

/**
 * Detect route schemas by directory or by having operations + basePath.
 */
export function isRouteSchema(schema: FluskSchema): boolean {
  const rawDir = schema._metadata?.directory ?? '';
  const topDir = rawDir.split('/')[0] ?? rawDir;
  if (topDir === 'routes') return true;
  const s = schema as unknown as Record<string, unknown>;
  return !!(s['operations']) && !!(s['basePath']);
}

function apiClientTemplate(): string {
  return `${HEADER}
// Uses relative URLs — Vite dev proxy routes:
//   /api/gateway/* → :3000 (gateway)
//   /api/*         → :3042 (Platformatic)

export const apiClient = {
  async get<T>(url: string, opts?: { params?: Record<string, unknown> }): Promise<T> {
    let fetchUrl = url;
    if (opts?.params && Object.keys(opts.params).length > 0) {
      const qs = new URLSearchParams();
      Object.entries(opts.params).forEach(([k, v]) => {
        if (v !== undefined && v !== null) qs.set(k, String(v));
      });
      fetchUrl = url + '?' + qs.toString();
    }
    const res = await fetch(fetchUrl, { credentials: 'include' });
    if (!res.ok) throw new Error(\`API \${res.status}: \${res.statusText}\`);
    return res.json() as Promise<T>;
  },

  async post<T>(url: string, body: unknown): Promise<T> {
    const res = await fetch(url, {
      method: 'POST',
      credentials: 'include',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(body),
    });
    if (!res.ok) throw new Error(\`API \${res.status}: \${res.statusText}\`);
    return res.json() as Promise<T>;
  },

  async put<T>(url: string, body: unknown): Promise<T> {
    const res = await fetch(url, {
      method: 'PUT',
      credentials: 'include',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(body),
    });
    if (!res.ok) throw new Error(\`API \${res.status}: \${res.statusText}\`);
    return res.json() as Promise<T>;
  },

  async patch<T>(url: string, body: unknown): Promise<T> {
    const res = await fetch(url, {
      method: 'PATCH',
      credentials: 'include',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(body),
    });
    if (!res.ok) throw new Error(\`API \${res.status}: \${res.statusText}\`);
    return res.json() as Promise<T>;
  },

  async delete(url: string): Promise<void> {
    const res = await fetch(url, {
      method: 'DELETE',
      credentials: 'include',
    });
    if (!res.ok) throw new Error(\`API \${res.status}: \${res.statusText}\`);
  },
};
`;
}

interface RouteOperation {
  method: string;
  path: string;
  call?: string;
  input?: string;
  description?: string;
  with?: Record<string, unknown>;
}

function hasIdParam(op: RouteOperation): boolean {
  return op.path.includes(':id') || op.path.includes(':');
}

function getEntityName(route: FluskSchema): string {
  const s = route as unknown as Record<string, unknown>;
  if (s['entity']) return toPascal(String(s['entity']));
  const name = route.name;
  if (name.endsWith('s')) return toPascal(name.slice(0, -1));
  return toPascal(name);
}

function generateHookFile(route: FluskSchema): string {
  const s = route as unknown as Record<string, unknown>;
  const routeName = route.name;
  const basePath = String(s['basePath'] ?? `/api/${routeName}`);
  const entityName = getEntityName(route);
  const operations = (s['operations'] ?? []) as RouteOperation[];
  const keysVar = toCamel(routeName) + 'Keys';
  const hookPrefix = toPascal(routeName);

  const listOp = operations.find((o) => o.method === 'GET' && !hasIdParam(o));
  const getOp = operations.find((o) => o.method === 'GET' && hasIdParam(o));
  const createOp = operations.find((o) => o.method === 'POST' && o.path === '/');
  const updateOp = operations.find(
    (o) => (o.method === 'PUT' || o.method === 'PATCH') && hasIdParam(o)
  );
  const deleteOp = operations.find((o) => o.method === 'DELETE' && hasIdParam(o));

  const actionOps = operations.filter((o) => o.method === 'POST' && o.path !== '/');

  let code = `${HEADER}
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import type { ${entityName}, Create${entityName}, Update${entityName} } from '../types/${entityName}';
import { apiClient } from '../lib/api-client';

export const ${keysVar} = {
  all: ['${routeName}'] as const,
  detail: (id: string) => ['${routeName}', id] as const,
} as const;

`;

  if (listOp) {
    // Use plural form for list hook to avoid conflict with detail hook
    const listHookName = hookPrefix === entityName ? `${hookPrefix}List` : hookPrefix;
    code += `export function use${listHookName}(params?: Record<string, unknown>) {
  return useQuery({
    queryKey: ${keysVar}.all,
    queryFn: () => apiClient.get<${entityName}[]>('${basePath}', { params }),
  });
}

`;
  }

  if (getOp) {
    code += `export function use${entityName}(id: string) {
  return useQuery({
    queryKey: ${keysVar}.detail(id),
    queryFn: () => apiClient.get<${entityName}>(\`${basePath}/\${id}\`),
    enabled: !!id,
  });
}

`;
  }

  if (createOp) {
    code += `export function useCreate${entityName}() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (data: Create${entityName}) => apiClient.post<${entityName}>('${basePath}', data),
    onSuccess: () => qc.invalidateQueries({ queryKey: ${keysVar}.all }),
  });
}

`;
  }

  if (updateOp) {
    const method = updateOp.method === 'PUT' ? 'put' : 'patch';
    code += `export function useUpdate${entityName}(id: string) {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (data: Update${entityName}) =>
      apiClient.${method}<${entityName}>(\`${basePath}/\${id}\`, data),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ${keysVar}.all });
      qc.invalidateQueries({ queryKey: ${keysVar}.detail(id) });
    },
  });
}

`;
  }

  if (deleteOp) {
    code += `export function useDelete${entityName}() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (id: string) => apiClient.delete(\`${basePath}/\${id}\`),
    onSuccess: () => qc.invalidateQueries({ queryKey: ${keysVar}.all }),
  });
}

`;
  }

  for (const op of actionOps) {
    const callName = toPascal(op.call ?? 'action');
    const inputType = op.input ?? 'Record<string, unknown>';
    const opPath = op.path;

    if (hasIdParam(op)) {
      const pathWithId = (basePath + opPath).replace(':id', '${params.id}');
      code += `export function use${callName}() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (params: { id: string } & Partial<${inputType}>) =>
      apiClient.post(\`${pathWithId}\`, params),
    onSuccess: () => qc.invalidateQueries({ queryKey: ${keysVar}.all }),
  });
}

`;
    } else {
      const fullPath = basePath + opPath;
      code += `export function use${callName}() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (data: ${inputType}) => apiClient.post('${fullPath}', data),
    onSuccess: () => qc.invalidateQueries({ queryKey: ${keysVar}.all }),
  });
}

`;
    }
  }

  return code;
}

// ─── View-based hook generation ──────────────────────────────────────

function isViewSchema(schema: FluskSchema): boolean {
  const rawDir = schema._metadata?.directory ?? '';
  const topDir = rawDir.split('/')[0] ?? rawDir;
  if (topDir === 'views') return true;
  const s = schema as unknown as Record<string, unknown>;
  return !!s['route'] && !!s['sections'];
}


interface ViewDataSource {
  endpoint?: string;
  params?: Record<string, unknown>;
  description?: string;
  lazy?: boolean;
}

function generateViewHookFile(view: FluskSchema, _entitySchemas: FluskSchema[]): string {
  const viewName = view.name.replace(/[\s\-]+/g, '');
  const hookName = `use${viewName}`;
  const s = view as unknown as Record<string, unknown>;

  // Use data_sources field directly — each entry has endpoint: "METHOD /path"
  const dataSources = s['data_sources'] as Record<string, ViewDataSource> | undefined;

  if (!dataSources || Object.keys(dataSources).length === 0) {
    return `${HEADER}
// View hook for ${view.name} — no data_sources defined
export function ${hookName}(): { data: Record<string, any>; isLoading: boolean } {
  return { data: {}, isLoading: false };
}
`;
  }

  // Skip lazy data sources (fetched on-demand, not in initial load)
  const entries = Object.entries(dataSources).filter(([, src]) => !src.lazy);

  if (entries.length === 0) {
    return `${HEADER}
// View hook for ${view.name} — all data sources are lazy
export function ${hookName}(): { data: Record<string, any>; isLoading: boolean } {
  return { data: {}, isLoading: false };
}
`;
  }

  const apiCalls: string[] = [];
  const resultKeys: string[] = [];

  for (const [key, source] of entries) {
    // Parse "GET /api/..." format — extract path after the method prefix
    const endpointRaw = source.endpoint ?? '';
    const spaceIdx = endpointRaw.indexOf(' ');
    const path = spaceIdx >= 0 ? endpointRaw.slice(spaceIdx + 1).trim() : endpointRaw;

    const params = source.params;
    if (params && Object.keys(params).length > 0) {
      apiCalls.push(`      apiClient.get<any>('${path}', { params: ${JSON.stringify(params)} }).catch(() => null)`);
    } else {
      apiCalls.push(`      apiClient.get<any>('${path}').catch(() => null)`);
    }
    resultKeys.push(key);
  }

  const unwrapMap: Record<string, string> = {};
  for (const [key, source] of entries) {
    if ((source as any).unwrap) {
      unwrapMap[key] = (source as any).unwrap;
    }
  }
  // Auto-unwrap: if API returns { key: [...] }, extract the array
  // Also support explicit unwrap field in YAML
  const autoUnwrap = `(r: any) => { if (r && typeof r === 'object' && !Array.isArray(r)) { const keys = Object.keys(r); if (keys.length === 1 && Array.isArray(r[keys[0]])) return r[keys[0]]; } return r; }`;
  const needsAutoUnwrap = resultKeys.length > 0;

  const dataFields = resultKeys.map((key, i) => {
    if (unwrapMap[key]) {
      return `        ${key}: results[${i}]?.['${unwrapMap[key]}'] ?? results[${i}]`;
    }
    return `        ${key}: autoUnwrap(results[${i}])`;
  });

  const autoUnwrapFn = needsAutoUnwrap ? `\n  const autoUnwrap = (r: any) => { if (r && typeof r === 'object' && !Array.isArray(r)) { const keys = Object.keys(r); if (keys.length === 1 && Array.isArray(r[keys[0]])) return r[keys[0]]; } return r; };\n` : '';

  return `${HEADER}
import { useQuery } from '@tanstack/react-query';
import { apiClient } from '../lib/api-client';

export function ${hookName}() {${autoUnwrapFn}
  return useQuery({
    queryKey: ['${viewName}'],
    queryFn: async () => {
      const results = await Promise.all([
${apiCalls.join(',\n')}
      ]);
      return {
${dataFields.join(',\n')}
      };
    },
  });
}
`;
}

export class APIClientGenerator {
  async generate(schemas: FluskSchema[], outputDir: string): Promise<GenerationResult> {
    const result: GenerationResult = { filesGenerated: 0, errors: [], warnings: [] };

    const libDir = join(outputDir, 'lib');
    const hooksDir = join(outputDir, 'hooks');
    await mkdir(libDir, { recursive: true });
    await mkdir(hooksDir, { recursive: true });

    // Always write api-client
    await writeFileFs(join(libDir, 'api-client.ts'), apiClientTemplate(), 'utf-8');
    result.filesGenerated++;

    const barrelExports: string[] = [];
    const writtenHooks = new Set<string>();

    // 1. Generate hooks from route schemas (explicit CRUD operations)
    const routes = schemas.filter(isRouteSchema);
    for (const route of routes) {
      try {
        const code = generateHookFile(route);
        const fileName = `use${toPascal(route.name)}.ts`;
        await writeFileFs(join(hooksDir, fileName), code, 'utf-8');
        result.filesGenerated++;
        barrelExports.push(`export * from './use${toPascal(route.name)}';`);
        writtenHooks.add(toPascal(route.name));
      } catch (err) {
        result.errors.push(
          `APIClientGenerator: Failed for route ${route.name}: ${err instanceof Error ? err.message : String(err)}`
        );
      }
    }

    // 2. Generate hooks from view schemas (fetch data for pages)
    const views = schemas.filter(isViewSchema);
    const entitySchemas = schemas.filter(s => s.type === 'entity');

    for (const view of views) {
      const viewName = view.name.replace(/[\s\-]+/g, '');
      if (writtenHooks.has(viewName)) continue; // Don't overwrite route-based hooks

      try {
        const code = generateViewHookFile(view, entitySchemas);
        const fileName = `use${viewName}.ts`;
        await writeFileFs(join(hooksDir, fileName), code, 'utf-8');
        result.filesGenerated++;
        barrelExports.push(`export { use${viewName} } from './use${viewName}';`);
        writtenHooks.add(viewName);
      } catch (err) {
        result.errors.push(
          `APIClientGenerator: Failed for view ${view.name}: ${err instanceof Error ? err.message : String(err)}`
        );
      }
    }

    // Write barrel
    await writeFileFs(
      join(hooksDir, 'index.ts'),
      `${HEADER}\n\n${barrelExports.join('\n')}\n`,
      'utf-8'
    );
    result.filesGenerated++;

    return result;
  }
}
