import { mkdir, writeFile as writeFileFs } from 'node:fs/promises';
import { join } from 'node:path';
import type { FluskSchema, GenerationResult } from '../../parsers/saas-schema.parser.js';
import { isEntitySchema } from './type.gen.js';

const HEADER = '// @generated by flusk-lang — DO NOT EDIT';

function toPascal(name: string): string {
  return name
    .replace(/[\s\-_]+(.)/g, (_: string, c: string) => c.toUpperCase())
    .replace(/^(.)/, (_: string, c: string) => c.toUpperCase());
}

function toCamel(name: string): string {
  const p = toPascal(name);
  return p.charAt(0).toLowerCase() + p.slice(1);
}

type FieldMap = Record<string, Record<string, unknown>>;

function normalizeFields(raw: unknown): FieldMap {
  if (!raw) return {};
  if (Array.isArray(raw)) {
    const map: FieldMap = {};
    for (const f of raw as Array<Record<string, unknown>>) {
      const n = f['name'] as string | undefined;
      if (n) {
        const { name: _n, ...rest } = f;
        map[n] = rest as Record<string, unknown>;
      }
    }
    return map;
  }
  return raw as FieldMap;
}

function fieldToZodType(fieldName: string, field: Record<string, unknown>): string {
  const type = String(field['type'] ?? 'string');
  const required = field['required'] === true;
  const minLength = field['min_length'] as number | undefined;
  const maxLength = field['max_length'] as number | undefined;

  let zodType: string;
  switch (type) {
    case 'string':
    case 'text':
    case 'uuid':
    case 'url':
    case 'date':
    case 'datetime':
    case 'timestamp':
      zodType = 'z.string()';
      if (minLength !== undefined) zodType += `.min(${minLength})`;
      if (maxLength !== undefined) zodType += `.max(${maxLength})`;
      break;
    case 'integer':
      zodType = 'z.number().int()';
      break;
    case 'float':
    case 'number':
      zodType = 'z.number()';
      break;
    case 'boolean':
      zodType = 'z.boolean()';
      break;
    case 'json':
      zodType = 'z.string()';
      break;
    case 'enum': {
      const values = field['values'] as string[] | undefined;
      if (values?.length) {
        zodType = `z.enum([${values.map((v) => `'${v}'`).join(', ')}])`;
      } else {
        zodType = 'z.string()';
      }
      break;
    }
    default:
      zodType = 'z.string()';
  }

  if (!required) {
    zodType += '.optional()';
  }

  // Suppress unused variable warning
  void fieldName;

  return zodType;
}

function fieldToJsx(fieldName: string, field: Record<string, unknown>): string {
  const type = String(field['type'] ?? 'string');
  const label = fieldName
    .replace(/([A-Z])/g, ' $1')
    .replace(/^./, (c) => c.toUpperCase())
    .trim();
  const required = field['required'] === true;
  const description = field['description'] as string | undefined;
  const values = field['values'] as string[] | undefined;

  const descLine = description ? `          <p className="text-xs text-muted-foreground">${description}</p>` : '';
  const reqMark = required ? ' *' : '';

  switch (type) {
    case 'boolean':
      return `        <div className="flex flex-row items-center justify-between rounded-lg border p-3">
          <div className="space-y-0.5">
            <Label htmlFor="${fieldName}">${label}${reqMark}</Label>
${descLine}
          </div>
          <Controller
            name="${fieldName}"
            control={control}
            render={({ field: f }) => (
              <Switch id="${fieldName}" checked={!!f.value} onCheckedChange={f.onChange} />
            )}
          />
          {errors.${fieldName} && <p className="text-sm text-destructive">{errors.${fieldName}?.message}</p>}
        </div>`;

    case 'enum':
      if (!values?.length) return '';
      return `        <div className="space-y-1">
          <Label htmlFor="${fieldName}">${label}${reqMark}</Label>
${descLine}
          <Controller
            name="${fieldName}"
            control={control}
            render={({ field: f }) => (
              <Select onValueChange={f.onChange} defaultValue={f.value}>
                <SelectTrigger id="${fieldName}">
                  <SelectValue placeholder="Select ${label.toLowerCase()}" />
                </SelectTrigger>
                <SelectContent>
                  ${values.map((v) => `<SelectItem value="${v}">${v}</SelectItem>`).join('\n                  ')}
                </SelectContent>
              </Select>
            )}
          />
          {errors.${fieldName} && <p className="text-sm text-destructive">{errors.${fieldName}?.message}</p>}
        </div>`;

    case 'integer':
    case 'float':
    case 'number':
      return `        <div className="space-y-1">
          <Label htmlFor="${fieldName}">${label}${reqMark}</Label>
${descLine}
          <Input
            id="${fieldName}"
            type="number"
            {...register('${fieldName}', { valueAsNumber: true })}
          />
          {errors.${fieldName} && <p className="text-sm text-destructive">{errors.${fieldName}?.message}</p>}
        </div>`;

    case 'text':
    case 'json':
      return `        <div className="space-y-1">
          <Label htmlFor="${fieldName}">${label}${reqMark}</Label>
${descLine}
          <Textarea id="${fieldName}" {...register('${fieldName}')} />
          {errors.${fieldName} && <p className="text-sm text-destructive">{errors.${fieldName}?.message}</p>}
        </div>`;

    default:
      return `        <div className="space-y-1">
          <Label htmlFor="${fieldName}">${label}${reqMark}</Label>
${descLine}
          <Input id="${fieldName}" type="text" {...register('${fieldName}')} />
          {errors.${fieldName} && <p className="text-sm text-destructive">{errors.${fieldName}?.message}</p>}
        </div>`;
  }
}

function hasEnumField(fields: FieldMap): boolean {
  return Object.values(fields).some((f) => f['type'] === 'enum');
}

function hasBooleanField(fields: FieldMap): boolean {
  return Object.values(fields).some((f) => f['type'] === 'boolean');
}

function hasTextareaField(fields: FieldMap): boolean {
  return Object.values(fields).some((f) => f['type'] === 'text' || f['type'] === 'json');
}

function generateFormComponent(schema: FluskSchema): string {
  const name = toPascal(schema.name);
  const s = schema as unknown as Record<string, unknown>;
  const fields = normalizeFields(s['fields']);

  const formFields = Object.entries(fields).filter(([, f]) => {
    return !f['primary'] && f['type'] !== 'uuid';
  });

  const zodLines = formFields.map(([fn, f]) => `  ${fn}: ${fieldToZodType(fn, f)},`);
  const jsxFields = formFields.map(([fn, f]) => fieldToJsx(fn, f)).filter(Boolean);

  const needsEnum = hasEnumField(Object.fromEntries(formFields));
  const needsSwitch = hasBooleanField(Object.fromEntries(formFields));
  const needsTextarea = hasTextareaField(Object.fromEntries(formFields));

  const selectImports = needsEnum
    ? `import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';`
    : '';
  const switchImport = needsSwitch
    ? `import { Switch } from '@/components/ui/switch';`
    : '';
  const textareaImport = needsTextarea
    ? `import { Textarea } from '@/components/ui/textarea';`
    : '';

  return `${HEADER}
import React from 'react';
import { useForm, Controller } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
${selectImports}
${switchImport}
${textareaImport}
import type { ${name} } from '../types/${name}';

// ── Validation schema ──────────────────────────────────────────────────────
const ${toCamel(name)}FormSchema = z.object({
${zodLines.join('\n')}
});

export type ${name}FormValues = z.infer<typeof ${toCamel(name)}FormSchema>;

// ── Props ──────────────────────────────────────────────────────────────────
interface ${name}FormProps {
  mode: 'create' | 'edit';
  defaultValues?: Partial<${name}>;
  onSubmit: (values: ${name}FormValues) => void | Promise<void>;
  isLoading?: boolean;
}

// ── Component ──────────────────────────────────────────────────────────────
export function ${name}Form({ mode, defaultValues, onSubmit, isLoading }: ${name}FormProps) {
  const {
    register,
    control,
    handleSubmit,
    formState: { errors },
  } = useForm<${name}FormValues>({
    resolver: zodResolver(${toCamel(name)}FormSchema),
    defaultValues: defaultValues as ${name}FormValues | undefined,
  });

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
${jsxFields.join('\n\n')}

      <Button type="submit" disabled={isLoading}>
        {isLoading ? 'Saving\u2026' : mode === 'create' ? 'Create ${name}' : 'Save Changes'}
      </Button>
    </form>
  );
}

export default ${name}Form;
`;
}

export class FormGenerator {
  async generate(schemas: FluskSchema[], outputDir: string): Promise<GenerationResult> {
    const result: GenerationResult = { filesGenerated: 0, errors: [], warnings: [] };

    const entities = schemas.filter(isEntitySchema);
    if (entities.length === 0) {
      result.warnings.push('FormGenerator: No entity schemas found');
      return result;
    }

    const formsDir = join(outputDir, 'forms');
    await mkdir(formsDir, { recursive: true });

    const barrelExports: string[] = [];

    for (const entity of entities) {
      try {
        const code = generateFormComponent(entity);
        const typeName = toPascal(entity.name);
        const fileName = `${typeName}Form.tsx`;
        await writeFileFs(join(formsDir, fileName), code, 'utf-8');
        result.filesGenerated++;
        barrelExports.push(`export * from './${typeName}Form';`);
      } catch (err) {
        result.errors.push(
          `FormGenerator: Failed for ${entity.name}: ${err instanceof Error ? err.message : String(err)}`
        );
      }
    }

    await writeFileFs(
      join(formsDir, 'index.ts'),
      `${HEADER}\n\n${barrelExports.join('\n')}\n`,
      'utf-8'
    );
    result.filesGenerated++;

    return result;
  }
}
