import { mkdir, writeFile as writeFileFs } from 'node:fs/promises';
import { join } from 'node:path';
import type { FluskSchema, GenerationResult } from '../../parsers/saas-schema.parser.js';
import { isEntitySchema } from './type.gen.js';
import { isRouteSchema } from './api-client.gen.js';

const HEADER = '-- @generated by flusk-lang — DO NOT EDIT';
const JS_HEADER = '// @generated by flusk-lang — DO NOT EDIT';

function toPascal(name: string): string {
  return name
    .replace(/[\s\-_]+(.)/g, (_: string, c: string) => c.toUpperCase())
    .replace(/^(.)/, (_: string, c: string) => c.toUpperCase());
}

function toSnake(name: string): string {
  return name
    .replace(/([A-Z])/g, '_$1')
    .toLowerCase()
    .replace(/^_/, '');
}

function tableNameFor(entityName: string): string {
  const snake = toSnake(entityName);
  return snake.endsWith('s') ? snake : snake + 's';
}

type FieldMap = Record<string, Record<string, unknown>>;

function normalizeFields(raw: unknown): FieldMap {
  if (!raw) return {};
  if (Array.isArray(raw)) {
    const map: FieldMap = {};
    for (const f of raw as Array<Record<string, unknown>>) {
      const n = f['name'] as string | undefined;
      if (n) {
        const { name: _n, ...rest } = f;
        map[n] = rest as Record<string, unknown>;
      }
    }
    return map;
  }
  return raw as FieldMap;
}

function fieldToSqlType(field: Record<string, unknown>): string {
  const type = String(field['type'] ?? 'string');
  switch (type) {
    case 'integer':
      return 'INTEGER';
    case 'float':
    case 'number':
      return 'REAL';
    case 'boolean':
      return 'INTEGER';
    case 'json':
      return 'TEXT';
    case 'enum': {
      const values = field['values'] as string[] | undefined;
      if (values?.length) {
        return `TEXT CHECK(value IN (${values.map((v) => `'${v}'`).join(', ')}))`;
      }
      return 'TEXT';
    }
    default:
      return 'TEXT';
  }
}

function enumCheck(colName: string, field: Record<string, unknown>): string | null {
  if (field['type'] !== 'enum') return null;
  const values = field['values'] as string[] | undefined;
  if (!values?.length) return null;
  return `CHECK(${colName} IN (${values.map((v) => `'${v}'`).join(', ')}))`;
}

function generateCreateTable(schema: FluskSchema): string {
  const s = schema as unknown as Record<string, unknown>;
  const fields = normalizeFields(s['fields']);
  const tableName = tableNameFor(schema.name);
  const description = s['description'] as string | undefined;

  const lines: string[] = [];

  lines.push(`  id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16))))`);

  for (const [fieldName, field] of Object.entries(fields)) {
    if (field['primary']) continue;

    const colName = toSnake(fieldName);
    const isRequired = field['required'] === true;
    const isUnique = field['unique'] === true;
    const defaultVal = field['default'];

    let colDef = `  ${colName} `;

    if (field['type'] === 'enum') {
      colDef += 'TEXT';
      const check = enumCheck(colName, field);
      if (!isRequired) colDef += ' NULL';
      else colDef += ' NOT NULL';
      if (defaultVal !== undefined && defaultVal !== null && String(defaultVal) !== '') {
        colDef += ` DEFAULT '${String(defaultVal)}'`;
      }
      if (check) colDef += ` ${check}`;
    } else {
      const sqlType = fieldToSqlType(field);
      colDef += sqlType;
      if (!isRequired) {
        colDef += ' NULL';
      } else {
        colDef += ' NOT NULL';
      }
      if (defaultVal !== undefined && defaultVal !== null) {
        const defStr = String(defaultVal);
        if (field['type'] === 'boolean') {
          colDef += ` DEFAULT ${defStr === 'true' || defStr === '1' ? 1 : 0}`;
        } else if (field['type'] === 'integer' || field['type'] === 'float' || field['type'] === 'number') {
          colDef += ` DEFAULT ${defStr}`;
        } else if (defStr !== '') {
          colDef += ` DEFAULT '${defStr}'`;
        }
      }
    }

    if (isUnique) colDef += ' UNIQUE';

    lines.push(colDef);
  }

  lines.push(`  created_at TEXT NOT NULL DEFAULT (datetime('now'))`);
  lines.push(`  updated_at TEXT NOT NULL DEFAULT (datetime('now'))`);

  const commentLine = description ? `-- ${description}\n` : '';
  return `${commentLine}CREATE TABLE IF NOT EXISTS ${tableName} (\n${lines.join(',\n')}\n);`;
}

function generateUpdateTrigger(schema: FluskSchema): string {
  const tableName = tableNameFor(schema.name);
  return `CREATE TRIGGER IF NOT EXISTS ${tableName}_updated_at
AFTER UPDATE ON ${tableName}
BEGIN
  UPDATE ${tableName} SET updated_at = datetime('now') WHERE id = NEW.id;
END;`;
}

interface RouteOperation {
  method: string;
  path: string;
  call?: string;
  description?: string;
  input?: string;
  with?: Record<string, unknown>;
}

function getEntityName(route: FluskSchema): string {
  const s = route as unknown as Record<string, unknown>;
  if (s['entity']) return toPascal(String(s['entity']));
  const name = route.name;
  if (name.endsWith('s')) return toPascal(name.slice(0, -1));
  return toPascal(name);
}

function httpMethodToFastify(method: string): string {
  return method.toLowerCase();
}

function generateRouteHandler(route: FluskSchema): string {
  const s = route as unknown as Record<string, unknown>;
  const basePath = String(s['basePath'] ?? `/api/${route.name}`);
  const entityName = getEntityName(route);
  const tableName = tableNameFor(entityName);
  const operations = (s['operations'] ?? []) as RouteOperation[];

  const handlerBlocks: string[] = [];

  for (const op of operations) {
    const method = httpMethodToFastify(op.method);
    const opPath = op.path === '/' ? '' : op.path;
    const fullPath = basePath + opPath;
    const desc = op.description ? `    // ${op.description}` : '';

    let handler: string;

    if (op.method === 'GET' && !opPath.includes(':id') && !opPath.includes('/aggregate') && !opPath.includes('/duplicates')) {
      handler = `${desc}
  fastify.${method}('${fullPath}', async (request, reply) => {
    const items = await fastify.db.all('SELECT * FROM ${tableName} ORDER BY created_at DESC');
    return items;
  });`;
    } else if (op.method === 'GET' && opPath === '/:id') {
      handler = `${desc}
  fastify.${method}('${fullPath.replace(':id', ':id')}', async (request, reply) => {
    const { id } = request.params as { id: string };
    const item = await fastify.db.get('SELECT * FROM ${tableName} WHERE id = ?', id);
    if (!item) return reply.status(404).send({ error: '${entityName} not found' });
    return item;
  });`;
    } else if (op.method === 'POST' && op.path === '/') {
      handler = `${desc}
  fastify.${method}('${fullPath}', async (request, reply) => {
    const body = request.body as Record<string, unknown>;
    const id = crypto.randomUUID();
    const fields = Object.keys(body);
    const placeholders = fields.map(() => '?').join(', ');
    const values = fields.map((k) => body[k]);
    await fastify.db.run(
      \`INSERT INTO ${tableName} (id, \${fields.join(', ')}) VALUES (?, \${placeholders})\`,
      [id, ...values]
    );
    const item = await fastify.db.get('SELECT * FROM ${tableName} WHERE id = ?', id);
    return reply.status(201).send(item);
  });`;
    } else if ((op.method === 'PUT' || op.method === 'PATCH') && opPath.includes(':id')) {
      handler = `${desc}
  fastify.${method}('${fullPath}', async (request, reply) => {
    const { id } = request.params as { id: string };
    const body = request.body as Record<string, unknown>;
    const fields = Object.keys(body);
    const setClause = fields.map((k) => \`\${k} = ?\`).join(', ');
    const values = [...fields.map((k) => body[k]), id];
    await fastify.db.run(\`UPDATE ${tableName} SET \${setClause} WHERE id = ?\`, values);
    const item = await fastify.db.get('SELECT * FROM ${tableName} WHERE id = ?', id);
    if (!item) return reply.status(404).send({ error: '${entityName} not found' });
    return item;
  });`;
    } else if (op.method === 'DELETE' && opPath.includes(':id')) {
      handler = `${desc}
  fastify.${method}('${fullPath}', async (request, reply) => {
    const { id } = request.params as { id: string };
    const item = await fastify.db.get('SELECT * FROM ${tableName} WHERE id = ?', id);
    if (!item) return reply.status(404).send({ error: '${entityName} not found' });
    await fastify.db.run('DELETE FROM ${tableName} WHERE id = ?', id);
    return reply.status(204).send();
  });`;
    } else if (op.method === 'GET' && opPath.includes('/:id/')) {
      const subPath = opPath.replace('/:id/', '');
      handler = `${desc}
  fastify.${method}('${fullPath}', async (request, reply) => {
    const { id } = request.params as { id: string };
    // TODO: implement ${op.call ?? subPath} sub-resource query
    return reply.status(501).send({ error: 'Not implemented' });
  });`;
    } else {
      handler = `${desc}
  fastify.${method}('${fullPath}', async (request, reply) => {
    // TODO: implement ${op.call ?? 'handler'}
    return reply.status(501).send({ error: 'Not implemented' });
  });`;
    }

    handlerBlocks.push(handler);
  }

  return `${JS_HEADER}
'use strict';

/** @param {import('fastify').FastifyInstance} fastify */
module.exports = async function (fastify) {
${handlerBlocks.join('\n\n')}
};
`;
}

function generatePlatformaticConfig(entities: FluskSchema[]): string {
  // entities param used for potential future per-entity config
  void entities;
  const config = {
    $schema: 'https://platformatic.dev/schemas/v1.52.0/db',
    server: {
      hostname: '{PLT_SERVER_HOSTNAME}',
      port: '{PORT}',
      logger: { level: '{PLT_SERVER_LOGGER_LEVEL}' },
    },
    db: {
      connectionString: '{DATABASE_URL}',
      graphql: true,
      openapi: true,
    },
    plugins: {
      paths: ['./plugins', { path: './routes', encapsulate: false }],
    },
    migrations: {
      dir: './migrations',
      autoApply: true,
    },
    watch: {
      ignore: ['*.sqlite-journal'],
    },
    $env: {
      PORT: { default: '3042', type: 'string' },
      PLT_SERVER_HOSTNAME: { default: '0.0.0.0', type: 'string' },
      PLT_SERVER_LOGGER_LEVEL: { default: 'info', type: 'string' },
      DATABASE_URL: { default: 'sqlite://./data.db', type: 'string' },
    },
  };

  return JSON.stringify(config, null, 2);
}

function generateEnvFile(): string {
  return `# Development environment
PORT=3042
PLT_SERVER_HOSTNAME=0.0.0.0
PLT_SERVER_LOGGER_LEVEL=info
DATABASE_URL=sqlite://./data.db
`;
}

export class PlatformaticGenerator {
  async generate(schemas: FluskSchema[], outputDir: string): Promise<GenerationResult> {
    const result: GenerationResult = { filesGenerated: 0, errors: [], warnings: [] };

    const entities = schemas.filter(isEntitySchema);
    const routes = schemas.filter(isRouteSchema);

    if (entities.length === 0) {
      result.warnings.push('PlatformaticGenerator: No entity schemas found');
      return result;
    }

    const backendDir = join(outputDir, 'backend');
    const migrationsDir = join(backendDir, 'migrations');
    const routesDir = join(backendDir, 'routes');
    const pluginsDir = join(backendDir, 'plugins');

    await mkdir(backendDir, { recursive: true });
    await mkdir(migrationsDir, { recursive: true });
    await mkdir(routesDir, { recursive: true });
    await mkdir(pluginsDir, { recursive: true });

    try {
      const config = generatePlatformaticConfig(entities);
      await writeFileFs(join(backendDir, 'platformatic.db.json'), config, 'utf-8');
      result.filesGenerated++;
    } catch (err) {
      result.errors.push(`PlatformaticGenerator: Failed to write config: ${err instanceof Error ? err.message : String(err)}`);
    }

    try {
      await writeFileFs(join(backendDir, '.env'), generateEnvFile(), 'utf-8');
      result.filesGenerated++;
    } catch (err) {
      result.errors.push(`PlatformaticGenerator: Failed to write .env: ${err instanceof Error ? err.message : String(err)}`);
    }

    try {
      const sqlBlocks: string[] = [
        `${HEADER}`,
        `-- Initial schema migration`,
        `-- Generated: ${new Date().toISOString()}`,
        '',
      ];

      for (const entity of entities) {
        try {
          sqlBlocks.push(generateCreateTable(entity));
          sqlBlocks.push('');
          sqlBlocks.push(generateUpdateTrigger(entity));
          sqlBlocks.push('');
        } catch (err) {
          result.errors.push(
            `PlatformaticGenerator: SQL for ${entity.name}: ${err instanceof Error ? err.message : String(err)}`
          );
        }
      }

      await writeFileFs(join(migrationsDir, '001_initial.sql'), sqlBlocks.join('\n'), 'utf-8');
      result.filesGenerated++;
    } catch (err) {
      result.errors.push(`PlatformaticGenerator: Failed to write migration: ${err instanceof Error ? err.message : String(err)}`);
    }

    for (const route of routes) {
      try {
        const code = generateRouteHandler(route);
        const fileName = `${route.name}.js`;
        await writeFileFs(join(routesDir, fileName), code, 'utf-8');
        result.filesGenerated++;
      } catch (err) {
        result.errors.push(
          `PlatformaticGenerator: Route ${route.name}: ${err instanceof Error ? err.message : String(err)}`
        );
      }
    }

    const dbPlugin = `${JS_HEADER}
'use strict';
const fp = require('fastify-plugin');
const { open } = require('sqlite');
const sqlite3 = require('sqlite3');

module.exports = fp(async function (fastify) {
  const dbUrl = process.env.DATABASE_URL ?? 'sqlite://./data.db';
  const filename = dbUrl.replace(/^sqlite:\\/\\//, '');
  const db = await open({ filename, driver: sqlite3.Database });
  fastify.decorate('db', db);
  fastify.addHook('onClose', async () => { await db.close(); });
});
`;
    await writeFileFs(join(pluginsDir, 'db.js'), dbPlugin, 'utf-8');
    result.filesGenerated++;

    if (routes.length === 0) {
      result.warnings.push('PlatformaticGenerator: No route schemas found — route handlers skipped');
    }

    return result;
  }
}
