import { mkdir, writeFile as writeFileFs } from 'node:fs/promises';
import { join } from 'node:path';
import type { FluskSchema, GenerationResult } from '../../parsers/saas-schema.parser.js';

const HEADER = '// @generated by flusk-lang — DO NOT EDIT';

function toPascal(name: string): string {
  return name
    .replace(/[\s\-_]+(.)/g, (_: string, c: string) => c.toUpperCase())
    .replace(/^(.)/, (_: string, c: string) => c.toUpperCase());
}

function toKebab(name: string): string {
  return name
    .toLowerCase()
    .replace(/\s+/g, '-')
    .replace(/[^a-z0-9-]/g, '');
}

/** Detect view schemas: have a `route` field and `sections` array */
export function isViewSchema(schema: FluskSchema): boolean {
  const s = schema as unknown as Record<string, unknown>;
  return typeof s['route'] === 'string' && Array.isArray(s['sections']);
}

/**
 * Convert Flusk route format to react-router-dom format.
 * e.g. "/$tenant/dashboard" → "/:tenant/dashboard"
 */
function toRouterPath(fluskRoute: string): string {
  return fluskRoute.replace(/\$([a-zA-Z_][a-zA-Z0-9_]*)/g, ':$1');
}

interface RouteEntry {
  routerPath: string;
  componentName: string;
  fileName: string;
  isFullScreen: boolean;
  tenantPath: string;
}

function parseRoute(schema: FluskSchema): RouteEntry {
  const s = schema as unknown as Record<string, unknown>;
  const fluskRoute = String(s['route'] ?? '');
  const routerPath = toRouterPath(fluskRoute);
  const componentName = toPascal(schema.name) + 'Page';
  const fileName = toKebab(schema.name) + '.page';

  const isTenantRoute = fluskRoute.startsWith('/$tenant/');
  const isFullScreen = !isTenantRoute;

  let tenantPath = '';
  if (isTenantRoute) {
    tenantPath = fluskRoute.slice('/$tenant/'.length);
    tenantPath = tenantPath.replace(/\$([a-zA-Z_][a-zA-Z0-9_]*)/g, ':$1');
  }

  return { routerPath, componentName, fileName, isFullScreen, tenantPath };
}

export class RouterGenerator {
  async generate(schemas: FluskSchema[], outputDir: string): Promise<GenerationResult> {
    const result: GenerationResult = { filesGenerated: 0, errors: [], warnings: [] };

    const views = schemas.filter(isViewSchema);
    if (views.length === 0) {
      result.warnings.push('RouterGenerator: No view schemas with route fields found');
      return result;
    }

    const routesDir = join(outputDir, 'routes');
    await mkdir(routesDir, { recursive: true });

    try {
      const code = this.generateRouterFile(views);
      await writeFileFs(join(routesDir, 'index.tsx'), code, 'utf-8');
      result.filesGenerated++;
    } catch (err) {
      result.errors.push(
        `RouterGenerator: ${err instanceof Error ? err.message : String(err)}`
      );
    }

    return result;
  }

  private generateRouterFile(views: FluskSchema[]): string {
    const entries = views.map(parseRoute);

    const fullScreenRoutes = entries.filter((e) => e.isFullScreen);
    const tenantRoutes = entries.filter((e) => !e.isFullScreen);

    tenantRoutes.sort((a, b) => a.tenantPath.localeCompare(b.tenantPath));

    const importLines = entries.map(
      (e) => `import { ${e.componentName} } from '../pages/${e.fileName}';`
    );

    const fullScreenEntries = fullScreenRoutes.map((e) => {
      const routePath = e.routerPath === '/' ? "path: '/'" : `path: '${e.routerPath}'`;
      return `  { ${routePath}, element: <${e.componentName} /> },`;
    });

    let tenantBlock = '';
    if (tenantRoutes.length > 0) {
      const childEntries = tenantRoutes.map((e) => {
        const childPath = e.tenantPath === '' ? "index: true" : `path: '${e.tenantPath}'`;
        return `      { ${childPath}, element: <${e.componentName} /> },`;
      });

      tenantBlock = `  {
    path: '/:tenant',
    children: [
${childEntries.join('\n')}
    ],
  },`;
    }

    const allRouteEntries = [...fullScreenEntries, tenantBlock].filter(Boolean).join('\n');

    return `${HEADER}
import React from 'react';
import { createBrowserRouter } from 'react-router-dom';
${importLines.join('\n')}

/**
 * Application router — generated from view YAML schemas.
 * Pass this to <RouterProvider router={router} /> in your app entry point.
 */
export const router = createBrowserRouter([
${allRouteEntries}
]);

export default router;
`;
  }
}
