import { mkdir, writeFile as writeFileFs } from 'node:fs/promises';
import { join } from 'node:path';
import type { FluskSchema, GenerationResult } from '../../parsers/saas-schema.parser.js';

const HEADER = '// @generated by flusk-lang — DO NOT EDIT';

function toPascal(name: string): string {
  return name
    .replace(/[\s\-_]+(.)/g, (_: string, c: string) => c.toUpperCase())
    .replace(/^(.)/, (_: string, c: string) => c.toUpperCase());
}

/**
 * Detect entity schemas by directory name or by having fields without sections/operations.
 */
export function isEntitySchema(schema: FluskSchema): boolean {
  const rawDir = schema._metadata?.directory ?? '';
  const topDir = rawDir.split('/')[0] ?? rawDir;
  if (topDir === 'entities') return true;
  const s = schema as unknown as Record<string, unknown>;
  return !!(s['fields']) && !s['sections'] && !s['operations'] && !s['basePath'];
}

function fieldToTsType(field: Record<string, unknown>): string {
  const type = String(field['type'] ?? 'string');
  switch (type) {
    case 'string':
    case 'text':
    case 'uuid':
    case 'date':
    case 'timestamp':
      return 'string';
    case 'integer':
    case 'float':
    case 'number':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'json':
      return 'Record<string, unknown>';
    case 'enum': {
      const values = field['values'] as string[] | undefined;
      if (values?.length) {
        return values.map((v) => `'${v}'`).join(' | ');
      }
      return 'string';
    }
    default:
      return 'string';
  }
}

function fieldToZodType(field: Record<string, unknown>): string {
  const type = String(field['type'] ?? 'string');
  switch (type) {
    case 'string':
    case 'text':
      return 'z.string()';
    case 'uuid':
      return 'z.string().uuid()';
    case 'date':
    case 'timestamp':
      return 'z.string()';
    case 'integer':
      return 'z.number().int()';
    case 'float':
    case 'number':
      return 'z.number()';
    case 'boolean':
      return 'z.boolean()';
    case 'json':
      return 'z.record(z.string(), z.unknown())';
    case 'enum': {
      const values = field['values'] as string[] | undefined;
      if (values?.length) {
        return `z.enum([${values.map((v) => `'${v}'`).join(', ')}])`;
      }
      return 'z.string()';
    }
    default:
      return 'z.string()';
  }
}

function generateEntityTypes(schema: FluskSchema): string {
  const name = toPascal(schema.name);
  const fields = ((schema as unknown as Record<string, unknown>)['fields'] ?? {}) as Record<string, Record<string, unknown>>;

  const tsLines: string[] = [];
  const zodLines: string[] = [];

  // Auto-generated primary key — always present
  tsLines.push('  id: string;');
  zodLines.push('  id: z.string().uuid(),');

  for (const [fieldName, field] of Object.entries(fields)) {
    if (fieldName === 'id') continue; // Already emitted above
    const tsType = fieldToTsType(field);
    const isRequired = field['required'] === true;
    const opt = isRequired ? '' : '?';
    tsLines.push(`  ${fieldName}${opt}: ${tsType};`);

    const zodType = fieldToZodType(field);
    const zodOpt = isRequired ? '' : '.optional()';
    zodLines.push(`  ${fieldName}: ${zodType}${zodOpt},`);
  }

  // Standard audit timestamps
  tsLines.push('  createdAt?: string;');
  tsLines.push('  updatedAt?: string;');
  zodLines.push('  createdAt: z.string().optional(),');
  zodLines.push('  updatedAt: z.string().optional(),');

  const description = (schema as unknown as Record<string, unknown>)['description'];
  const descComment = description ? `/** ${description} */\n` : '';

  return `${HEADER}
import { z } from 'zod';

${descComment}export interface ${name} {
${tsLines.join('\n')}
}

export const ${name}Schema = z.object({
${zodLines.join('\n')}
});

export type Create${name} = Omit<${name}, 'id' | 'createdAt' | 'updatedAt'>;
export type Update${name} = Partial<Create${name}>;
`;
}

export class TypeGenerator {
  async generate(schemas: FluskSchema[], outputDir: string): Promise<GenerationResult> {
    const result: GenerationResult = { filesGenerated: 0, errors: [], warnings: [] };

    const entities = schemas.filter(isEntitySchema);
    if (entities.length === 0) {
      result.warnings.push('TypeGenerator: No entity schemas found (add YAML files to an entities/ directory)');
      return result;
    }

    const typesDir = join(outputDir, 'types');
    await mkdir(typesDir, { recursive: true });

    const barrelExports: string[] = [];

    for (const entity of entities) {
      try {
        const code = generateEntityTypes(entity);
        const typeName = toPascal(entity.name);
        await writeFileFs(join(typesDir, `${typeName}.ts`), code, 'utf-8');
        result.filesGenerated++;
        barrelExports.push(`export * from './${typeName}';`);
      } catch (err) {
        result.errors.push(
          `TypeGenerator: Failed for ${entity.name}: ${err instanceof Error ? err.message : String(err)}`
        );
      }
    }

    // Barrel index
    await writeFileFs(
      join(typesDir, 'index.ts'),
      `${HEADER}\n\n${barrelExports.join('\n')}\n`,
      'utf-8'
    );
    result.filesGenerated++;

    return result;
  }
}
