import { join } from 'node:path';
import { mkdirSync, writeFileSync } from 'node:fs';
import { parseAll } from '../index.js';
import type { EntityDef } from '../parsers/entity.parser.js';
import type { RouteDef } from '../parsers/route.parser.js';
import { createChildLogger } from '../logger.js';

const log = createChildLogger('client-sdk');

const mapFieldToTs = (type: string): string => {
  const arrayMatch = type.match(/^(.+)\[\]$/);
  if (arrayMatch) return `${mapFieldToTs(arrayMatch[1]!)}[]`;
  switch (type) {
    case 'string': case 'uuid': case 'email': case 'url':
    case 'datetime': case 'date': case 'text':
      return 'string';
    case 'integer': case 'int': case 'number':
    case 'float': case 'decimal':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'json': case 'object': case 'record':
      return 'Record<string, unknown>';
    default:
      return type;
  }
};

const generateEntityType = (entity: EntityDef): string => {
  const lines = [`// @generated by flusk-lang — DO NOT EDIT`];
  lines.push(`export interface ${entity.name} {`);
  for (const field of entity.fields) {
    const optional = field.required === false ? '?' : '';
    lines.push(`  ${field.name}${optional}: ${mapFieldToTs(field.type)};`);
  }
  lines.push('}');
  lines.push('');
  return lines.join('\n');
};

const generateClientClass = (
  routes: RouteDef[],
  entityNames: Set<string>
): string => {
  const lines = [
    '// @generated by flusk-lang — DO NOT EDIT',
    '',
    ...Array.from(entityNames).map((n) => `import type { ${n} } from \'./types/${n}.js\';`),
    '',
    'export interface ClientOptions {',
    '  baseUrl: string;',
    '  headers?: Record<string, string>;',
    '}',
    '',
    'export class FluskClient {',
    '  private baseUrl: string;',
    '  private headers: Record<string, string>;',
    '',
    '  constructor(options: ClientOptions) {',
    '    this.baseUrl = options.baseUrl.replace(/\\/$/, \'\');',
    '    this.headers = options.headers ?? {};',
    '  }',
    '',
    '  private async request<T>(',
    '    method: string,',
    '    path: string,',
    '    body?: unknown',
    '  ): Promise<T> {',
    '    const res = await fetch(`${this.baseUrl}${path}`, {',
    '      method,',
    '      headers: {',
    '        \'Content-Type\': \'application/json\',',
    '        ...this.headers,',
    '      },',
    '      body: body ? JSON.stringify(body) : undefined,',
    '    });',
    '    if (!res.ok) {',
    '      throw new Error(`HTTP ${res.status}: ${res.statusText}`);',
    '    }',
    '    return res.json() as Promise<T>;',
    '  }',
  ];

  for (const route of routes) {
    for (const op of route.operations) {
      const method = op.method.toUpperCase();
      const fullPath = `${route.basePath}${op.path || ''}`;
      const methodName = op.call;
      const returnType = route.entity ?? 'unknown';
      const hasBody = ['POST', 'PUT', 'PATCH'].includes(method);
      const hasPathParam = fullPath.includes(':');

      const params: string[] = [];
      if (hasPathParam) {
        const paramNames = fullPath.match(/:(\w+)/g) ?? [];
        for (const p of paramNames) {
          params.push(`${p.slice(1)}: string`);
        }
      }
      if (hasBody && route.entity) {
        params.push(`body: Partial<${route.entity}>`);
      }

      let pathExpr = `'${fullPath}'`;
      if (hasPathParam) {
        pathExpr = '`' + fullPath.replace(/:(\w+)/g, '${$1}') + '`';
      }

      lines.push('');
      lines.push(`  async ${methodName}(${params.join(', ')}): Promise<${returnType}> {`);
      lines.push(`    return this.request<${returnType}>('${method}', ${pathExpr}${hasBody ? ', body' : ''});`);
      lines.push('  }');
    }
  }

  lines.push('}');
  lines.push('');
  return lines.join('\n');
};

export const generateClient = (schemaDir: string, generatedDir: string): string => {
  const schema = parseAll(schemaDir);
  const clientDir = join(generatedDir, 'client');
  const typesDir = join(clientDir, 'types');
  mkdirSync(typesDir, { recursive: true });

  const entityNames = new Set<string>();
  for (const entity of schema.entities) {
    const content = generateEntityType(entity);
    writeFileSync(join(typesDir, `${entity.name}.ts`), content, 'utf-8');
    entityNames.add(entity.name);
    log.debug({ entity: entity.name }, 'generated type');
  }

  // Types barrel
  const barrel = [
    '// @generated by flusk-lang — DO NOT EDIT',
    ...schema.entities.map((e) => `export type { ${e.name} } from './${e.name}.js';`),
    '',
  ].join('\n');
  writeFileSync(join(typesDir, 'index.ts'), barrel, 'utf-8');

  // Referenced entities only
  const referencedEntities = new Set<string>();
  for (const route of schema.routes) {
    if (route.entity && entityNames.has(route.entity)) {
      referencedEntities.add(route.entity);
    }
  }

  const clientCode = generateClientClass(schema.routes, referencedEntities);
  writeFileSync(join(clientDir, 'index.ts'), clientCode, 'utf-8');

  log.info({ types: schema.entities.length, routes: schema.routes.length }, 'client SDK generated');
  return clientDir;
};
