import { describe, it, expect } from 'vitest';
import { join } from 'node:path';
import { parseAll, lintGeneratedCode } from '../src/index.js';
import { generateEntitySchema, generateEntityType, generateEntityRepository } from '../src/generators/node/entity.gen.js';
import { generateFunction } from '../src/generators/node/function.gen.js';
import { generateCommand } from '../src/generators/node/command.gen.js';
import { generateRoute } from '../src/generators/node/route.gen.js';
import { generateClient } from '../src/generators/node/client.gen.js';
import { generateEvent } from '../src/generators/node/event.gen.js';
import { generateWorker } from '../src/generators/node/worker.gen.js';
import { generateStream } from '../src/generators/node/stream.gen.js';

const demosDir = join(__dirname, '..', '..', 'examples', 'demos');

interface GeneratedFile { name: string; code: string }

const generateAll = (schemaDir: string): GeneratedFile[] => {
  const s = parseAll(schemaDir);
  const files: GeneratedFile[] = [];
  for (const e of s.entities) {
    files.push({ name: `${e.name}.schema.ts`, code: generateEntitySchema(e) });
    files.push({ name: `${e.name}.types.ts`, code: generateEntityType(e) });
    files.push({ name: `${e.name}.repository.ts`, code: generateEntityRepository(e) });
  }
  for (const f of s.functions) files.push({ name: `${f.name}.function.ts`, code: generateFunction(f) });
  for (const c of s.commands) files.push({ name: `${c.name}.command.ts`, code: generateCommand(c) });
  for (const r of s.routes) files.push({ name: `${r.name}.routes.ts`, code: generateRoute(r) });
  for (const c of s.clients) files.push({ name: `${c.name}.client.ts`, code: generateClient(c) });
  for (const e of s.events) files.push({ name: `${e.name}.event.ts`, code: generateEvent(e) });
  for (const w of s.workers) files.push({ name: `${w.name}.worker.ts`, code: generateWorker(w) });
  for (const st of s.streams) files.push({ name: `${st.name}.stream.ts`, code: generateStream(st) });
  return files;
};

const demos = [
  { name: 'video-pipeline', expectedFiles: 17, yamls: 13 },
  { name: 'realtime-analytics', expectedFiles: 17, yamls: 11 },
  { name: 'agent-orchestrator', expectedFiles: 24, yamls: 18 },
  { name: 'iot-sensors', expectedFiles: 21, yamls: 15 },
  { name: 'ecommerce-orders', expectedFiles: 28, yamls: 20 },
];

describe('E2E Demos', () => {
  for (const demo of demos) {
    describe(demo.name, () => {
      const schemaDir = join(demosDir, demo.name, 'schema');

      it(`parses all ${demo.yamls} YAMLs`, () => {
        const s = parseAll(schemaDir);
        const total = Object.values(s).reduce((sum, arr) => sum + arr.length, 0);
        expect(total).toBeGreaterThan(0);
      });

      it(`generates ${demo.expectedFiles} files`, () => {
        const files = generateAll(schemaDir);
        expect(files.length).toBe(demo.expectedFiles);
      });

      it('all generated files pass lint', () => {
        const files = generateAll(schemaDir);
        const allIssues: string[] = [];
        for (const f of files) {
          const result = lintGeneratedCode(f.name, f.code);
          for (const issue of result.issues) {
            allIssues.push(`${f.name}: ${issue.rule} — ${issue.message}`);
          }
        }
        expect(allIssues).toEqual([]);
      });

      it('all generated files have @generated header', () => {
        const files = generateAll(schemaDir);
        for (const f of files) {
          expect(f.code).toMatch(/^\/\/ @generated by flusk-lang/);
        }
      });

      it('no generated file exceeds 100 lines', () => {
        const files = generateAll(schemaDir);
        for (const f of files) {
          const lines = f.code.split('\n').length;
          expect(lines, `${f.name} has ${lines} lines`).toBeLessThanOrEqual(100);
        }
      });
    });
  }

  it('total stats: 5 demos, 77 YAMLs, 107 files, 0 lint errors', () => {
    let totalFiles = 0;
    let totalIssues = 0;
    for (const demo of demos) {
      const files = generateAll(join(demosDir, demo.name, 'schema'));
      totalFiles += files.length;
      for (const f of files) {
        const r = lintGeneratedCode(f.name, f.code);
        totalIssues += r.issues.length;
      }
    }
    expect(totalFiles).toBe(107);
    expect(totalIssues).toBe(0);
  });
});
