import { describe, it, expect } from 'vitest';
import { join } from 'node:path';
import { parseEntity } from '../src/parsers/entity.parser.js';
import { parseFunction } from '../src/parsers/function.parser.js';
import { parseCommand } from '../src/parsers/command.parser.js';
import { parseRoute } from '../src/parsers/route.parser.js';
import { parseProvider } from '../src/parsers/provider.parser.js';
import { parseClient } from '../src/parsers/client.parser.js';
import { generateEntitySchema, generateEntityType, generateEntityRepository } from '../src/generators/node/entity.gen.js';
import { generateFunction } from '../src/generators/node/function.gen.js';
import { generateCommand } from '../src/generators/node/command.gen.js';
import { generateRoute } from '../src/generators/node/route.gen.js';
import { generateProvider } from '../src/generators/node/provider.gen.js';
import { generateClient } from '../src/generators/node/client.gen.js';
import { generateBarrel } from '../src/generators/node/barrel.gen.js';
import { generatePythonEntity } from '../src/generators/python/entity.gen.js';
import { generatePythonFunction } from '../src/generators/python/function.gen.js';

const examples = join(__dirname, '../../examples');
const HEADER_NODE = '@generated by flusk-lang';
const HEADER_PY = '@generated by flusk-lang';

describe('E2E: Entity → Node', () => {
  const entity = parseEntity(join(examples, 'alert-channel.entity.yaml'));

  it('generates valid TypeBox schema with header', () => {
    const out = generateEntitySchema(entity);
    expect(out).toContain(HEADER_NODE);
    expect(out).toContain('AlertChannelSchema');
    expect(out).toContain('Type.Object');
    expect(out).toContain('id: Type.String()');
  });

  it('generates valid TypeScript interface', () => {
    const out = generateEntityType(entity);
    expect(out).toContain(HEADER_NODE);
    expect(out).toContain('export interface AlertChannel');
    expect(out).toContain('id: string');
    expect(out).toContain('name: string');
  });

  it('generates repository with all CRUD methods', () => {
    const out = generateEntityRepository(entity);
    expect(out).toContain(HEADER_NODE);
    expect(out).toContain('findById');
    expect(out).toContain('findAll');
    expect(out).toContain('create');
    expect(out).toContain('update');
    expect(out).toContain('delete');
  });
});

describe('E2E: Entity → Python', () => {
  const entity = parseEntity(join(examples, 'alert-event.entity.yaml'));

  it('generates Pydantic model with header', () => {
    const out = generatePythonEntity(entity);
    expect(out).toContain(HEADER_PY);
    expect(out).toContain('class AlertEvent(BaseModel)');
    expect(out).toContain('id: str');
    expect(out).toContain('title: str');
  });

  it('generates Literal type for enums', () => {
    const out = generatePythonEntity(entity);
    expect(out).toContain('Literal["info", "warning", "error", "critical"]');
  });
});

describe('E2E: Function → Node', () => {
  const fn = parseFunction(join(examples, 'dispatch-alert.function.yaml'));

  it('generates async function with header', () => {
    const out = generateFunction(fn);
    expect(out).toContain(HEADER_NODE);
    expect(out).toContain('export const dispatchAlert = async');
    expect(out).toContain('Promise<DispatchResult[]>');
  });

  it('generates filter and forEach steps', () => {
    const out = generateFunction(fn);
    expect(out).toContain('.filter(');
    expect(out).toContain('for (const item of');
  });
});

describe('E2E: Function → Python', () => {
  const fn = parseFunction(join(examples, 'dispatch-alert.function.yaml'));

  it('generates async Python function with header', () => {
    const out = generatePythonFunction(fn);
    expect(out).toContain(HEADER_PY);
    expect(out).toContain('async def dispatchAlert');
  });

  it('generates list comprehension for filter', () => {
    const out = generatePythonFunction(fn);
    expect(out).toContain('[x for x in');
  });
});

describe('E2E: Command → Node', () => {
  const cmd = parseCommand(join(examples, 'alerts-setup.command.yaml'));

  it('generates commander command with header', () => {
    const out = generateCommand(cmd);
    expect(out).toContain(HEADER_NODE);
    expect(out).toContain("new Command('alerts-setup')");
    expect(out).toContain('.argument(');
    expect(out).toContain('.option(');
  });
});

describe('E2E: Route → Node', () => {
  const route = parseRoute(join(examples, 'alert-channels.route.yaml'));

  it('generates Fastify routes with header', () => {
    const out = generateRoute(route);
    expect(out).toContain(HEADER_NODE);
    expect(out).toContain('FastifyInstance');
    expect(out).toContain("app.get('/api/alert-channels'");
    expect(out).toContain("app.post('/api/alert-channels'");
    expect(out).toContain("app.delete('/api/alert-channels/:id'");
  });
});

describe('E2E: Provider → Node', () => {
  const provider = parseProvider(join(examples, 'slack.provider.yaml'));

  it('generates provider class with config', () => {
    const out = generateProvider(provider);
    expect(out).toContain(HEADER_NODE);
    expect(out).toContain('class SlackProvider');
    expect(out).toContain('SlackProviderConfig');
    expect(out).toContain('webhookUrl: string');
  });

  it('generates methods with template rendering', () => {
    const out = generateProvider(provider);
    expect(out).toContain('async send(');
    expect(out).toContain('async test(');
    expect(out).toContain('replaceAll');
  });
});

describe('E2E: Client → Node', () => {
  const client = parseClient(join(examples, 'openai.client.yaml'));

  it('generates typed client class with header', () => {
    const out = generateClient(client);
    expect(out).toContain(HEADER_NODE);
    expect(out).toContain('class OpenaiClient');
    expect(out).toContain('async createChatCompletion');
    expect(out).toContain('async listModels');
  });

  it('generates input interfaces', () => {
    const out = generateClient(client);
    expect(out).toContain('OpenaiCreateChatCompletionInput');
    expect(out).toContain('model: string');
    expect(out).toContain('messages: unknown');
  });

  it('generates auth handling', () => {
    const out = generateClient(client);
    expect(out).toContain('Authorization');
    expect(out).toContain('Bearer');
    expect(out).toContain('OPENAI_API_KEY');
  });

  it('generates retry logic', () => {
    const out = generateClient(client);
    expect(out).toContain('maxAttempts: 3');
    expect(out).toContain('setTimeout');
  });
});

describe('E2E: Barrel', () => {
  it('generates barrel exports', () => {
    const out = generateBarrel(['entities/alert.schema.ts', 'functions/dispatch.function.ts']);
    expect(out).toContain(HEADER_NODE);
    expect(out).toContain("export * from './entities/alert.schema.js'");
    expect(out).toContain("export * from './functions/dispatch.function.js'");
  });
});

describe('E2E: Complex function', () => {
  const fn = parseFunction(join(examples, 'process-alert-batch.function.yaml'));

  it('parses multi-step function', () => {
    expect(fn.name).toBe('processAlertBatch');
    expect(fn.steps).toHaveLength(3);
  });

  it('generates Node code for batch processing', () => {
    const out = generateFunction(fn);
    expect(out).toContain('export const processAlertBatch');
    expect(out).toContain('.filter(');
    expect(out).toContain('for (const item of');
    expect(out).toContain('return results');
  });

  it('generates Python code for batch processing', () => {
    const out = generatePythonFunction(fn);
    expect(out).toContain('async def processAlertBatch');
    expect(out).toContain('[x for x in');
    expect(out).toContain('return results');
  });
});
