import { describe, it, expect } from 'vitest';
import { generateEntitySchema, generateEntityType, generateEntityRepository } from '../src/generators/node/entity.gen.js';
import { generateFunction } from '../src/generators/node/function.gen.js';
import type { EntityDef } from '../src/parsers/entity.parser.js';
import type { FunctionDef } from '../src/parsers/function.parser.js';

const testEntity: EntityDef = {
  name: 'AlertChannel',
  fields: [
    { name: 'name', type: 'string', required: true },
    { name: 'channelType', type: 'enum', required: true, values: ['slack', 'email'] },
    { name: 'config', type: 'json' },
  ],
};

describe('Node Entity Generator', () => {
  it('generates TypeBox schema', () => {
    const output = generateEntitySchema(testEntity);
    expect(output).toContain('@generated by flusk-lang');
    expect(output).toContain('AlertChannelSchema');
    expect(output).toContain("Type.Literal('slack')");
    expect(output).toContain('Type.Record(Type.String(), Type.Unknown())');
  });

  it('generates TypeScript interface', () => {
    const output = generateEntityType(testEntity);
    expect(output).toContain('interface AlertChannel');
    expect(output).toContain('name: string');
    expect(output).toContain("'slack' | 'email'");
  });

  it('generates repository interface', () => {
    const output = generateEntityRepository(testEntity);
    expect(output).toContain('AlertChannelRepository');
    expect(output).toContain('findById');
    expect(output).toContain('create');
  });
});

describe('Node Function Generator', () => {
  it('generates function with call step', () => {
    const fn: FunctionDef = {
      name: 'doStuff',
      inputs: [{ name: 'db', type: 'Database' }],
      output: { type: 'Result' },
      steps: [{ id: 'getData', call: 'fetchData', with: { db: '$db' } }],
    };
    const output = generateFunction(fn);
    expect(output).toContain('@generated by flusk-lang');
    expect(output).toContain('export const doStuff');
    expect(output).toContain('await fetchData(db)');
  });

  it('generates filter step', () => {
    const fn: FunctionDef = {
      name: 'filterStuff',
      steps: [{
        id: 'filtered', action: 'filter', source: '$items',
        where: { field: 'score', op: 'gte', value: '10' },
      }],
    };
    const output = generateFunction(fn);
    expect(output).toContain('items.filter');
    expect(output).toContain('>= ');
  });

  it('generates forEach step with error handling', () => {
    const fn: FunctionDef = {
      name: 'sendAll',
      steps: [{
        id: 'send', action: 'forEach', source: '$items',
        call: 'sendOne', with: { item: '$item' }, onError: 'log-and-continue',
      }],
    };
    const output = generateFunction(fn);
    expect(output).toContain('for (const item of items)');
    expect(output).toContain('console.error');
  });
});
