import { describe, it, expect } from 'vitest';
import { lintGeneratedCode } from '../src/validators/lint.validator.js';
import { generateEntitySchema, generateEntityType, generateEntityRepository } from '../src/generators/node/entity.gen.js';
import { generateFunction } from '../src/generators/node/function.gen.js';
import { generateMiddleware } from '../src/generators/node/middleware.gen.js';
import { generatePlugin } from '../src/generators/node/plugin.gen.js';
import { generateService } from '../src/generators/node/service.gen.js';
import type { EntityDef } from '../src/parsers/entity.parser.js';
import type { MiddlewareDef } from '../src/parsers/middleware.parser.js';

const entity: EntityDef = {
  name: 'User',
  fields: [
    { name: 'name', type: 'string', required: true },
    { name: 'meta', type: 'json' },
  ],
};

describe('Lint Validator', () => {
  it('passes valid generated code', () => {
    const code = '// @generated by flusk-lang — DO NOT EDIT\n\nexport const x = 1;\nconsole.log(x);\n';
    const result = lintGeneratedCode('test.ts', code);
    expect(result.passed).toBe(true);
  });

  it('detects missing @generated header', () => {
    const result = lintGeneratedCode('test.ts', 'export const x = 1;\n');
    expect(result.issues.some((i) => i.rule === 'generated-header')).toBe(true);
  });

  it('detects : any type', () => {
    const code = '// @generated by flusk-lang\nconst x: any = 1;\nconsole.log(x);\n';
    const result = lintGeneratedCode('test.ts', code);
    expect(result.issues.some((i) => i.rule === 'no-explicit-any')).toBe(true);
  });

  it('detects as any cast', () => {
    const code = '// @generated by flusk-lang\nconst x = (y as any).z;\nconsole.log(x);\n';
    const result = lintGeneratedCode('test.ts', code);
    expect(result.issues.some((i) => i.rule === 'no-explicit-any')).toBe(true);
  });

  it('detects Type.Any()', () => {
    const code = '// @generated by flusk-lang\nconst s = Type.Any();\nconsole.log(s);\n';
    const result = lintGeneratedCode('test.ts', code);
    expect(result.issues.some((i) => i.rule === 'no-explicit-any')).toBe(true);
  });

  it('detects file exceeding max-lines', () => {
    const lines = ['// @generated by flusk-lang'];
    for (let i = 0; i < 110; i++) lines.push(`const line${i} = ${i};`);
    lines.push(lines.map((_, i) => `line${i}`).join('+'));
    const result = lintGeneratedCode('test.ts', lines.join('\n'));
    expect(result.issues.some((i) => i.rule === 'max-lines')).toBe(true);
  });

  it('detects export default', () => {
    const code = '// @generated by flusk-lang\nexport default function foo() {}\n';
    const result = lintGeneratedCode('test.ts', code);
    expect(result.issues.some((i) => i.rule === 'named-exports-only')).toBe(true);
  });

  it('detects unused imports', () => {
    const code = '// @generated by flusk-lang\nimport { Foo } from "bar";\nexport const x = 1;\n';
    const result = lintGeneratedCode('test.ts', code);
    expect(result.issues.some((i) => i.rule === 'no-unused-imports')).toBe(true);
  });

  it('entity schema has no any types', () => {
    const code = generateEntitySchema(entity);
    const result = lintGeneratedCode('user.schema.ts', code);
    const anyIssues = result.issues.filter((i) => i.rule === 'no-explicit-any');
    expect(anyIssues).toHaveLength(0);
  });

  it('entity type has no any types', () => {
    const code = generateEntityType(entity);
    const result = lintGeneratedCode('user.types.ts', code);
    const anyIssues = result.issues.filter((i) => i.rule === 'no-explicit-any');
    expect(anyIssues).toHaveLength(0);
  });

  it('entity schema has @generated header', () => {
    const code = generateEntitySchema(entity);
    const result = lintGeneratedCode('user.schema.ts', code);
    expect(result.issues.filter((i) => i.rule === 'generated-header')).toHaveLength(0);
  });

  it('entity repo has @generated header', () => {
    const code = generateEntityRepository(entity);
    const result = lintGeneratedCode('user.repo.ts', code);
    expect(result.issues.filter((i) => i.rule === 'generated-header')).toHaveLength(0);
  });

  it('middleware without output has no any casts', () => {
    const def: MiddlewareDef = { name: 'simple', phase: 'request' };
    const code = generateMiddleware(def);
    const result = lintGeneratedCode('simple.ts', code);
    const anyIssues = result.issues.filter((i) => i.rule === 'no-explicit-any');
    expect(anyIssues).toHaveLength(0);
  });

  it('detects unused variable declarations', () => {
    const code = '// @generated by flusk-lang\nconst unused = 42;\n';
    const result = lintGeneratedCode('test.ts', code);
    expect(result.issues.some((i) => i.rule === 'no-unused-vars')).toBe(true);
  });
});
