import { describe, it, expect } from 'vitest';
import { join } from 'node:path';
import { parseMiddleware } from '../src/parsers/middleware.parser.js';
import { generateMiddleware } from '../src/generators/node/middleware.gen.js';
import type { MiddlewareDef } from '../src/parsers/middleware.parser.js';

const examples = join(__dirname, '../../examples');

describe('Middleware Parser', () => {
  it('parses cost-calculator middleware', () => {
    const mw = parseMiddleware(join(examples, 'cost-calculator.middleware.yaml'));
    expect(mw.name).toBe('cost-calculator');
    expect(mw.phase).toBe('response');
  });

  it('parses inputs', () => {
    const mw = parseMiddleware(join(examples, 'cost-calculator.middleware.yaml'));
    expect(mw.inputs).toHaveLength(3);
    expect(mw.inputs![0].from).toBe('response.model');
  });

  it('parses lookup data', () => {
    const mw = parseMiddleware(join(examples, 'cost-calculator.middleware.yaml'));
    expect(mw.lookup).toBeDefined();
    expect(mw.lookup!.pricing).toBeDefined();
  });

  it('parses steps', () => {
    const mw = parseMiddleware(join(examples, 'cost-calculator.middleware.yaml'));
    expect(mw.steps).toHaveLength(2);
    expect(mw.steps![0].action).toBe('assign');
  });

  it('parses request-capture middleware', () => {
    const mw = parseMiddleware(join(examples, 'request-capture.middleware.yaml'));
    expect(mw.name).toBe('request-capture');
    expect(mw.phase).toBe('request');
    expect(mw.inputs).toHaveLength(2);
  });
});

describe('Middleware Generator', () => {
  it('generates hook function with header', () => {
    const mw = parseMiddleware(join(examples, 'cost-calculator.middleware.yaml'));
    const out = generateMiddleware(mw);
    expect(out).toContain('@generated by flusk-lang');
    expect(out).toContain('costCalculator');
    expect(out).toContain('FastifyRequest');
  });

  it('generates input extraction', () => {
    const mw = parseMiddleware(join(examples, 'cost-calculator.middleware.yaml'));
    const out = generateMiddleware(mw);
    expect(out).toContain('const model = response?.model');
    expect(out).toContain('const inputTokens = response?.usage?.prompt_tokens');
  });

  it('generates lookup data', () => {
    const mw = parseMiddleware(join(examples, 'cost-calculator.middleware.yaml'));
    const out = generateMiddleware(mw);
    expect(out).toContain('const lookup =');
    expect(out).toContain('gpt-4o');
  });

  it('generates output assignment', () => {
    const mw = parseMiddleware(join(examples, 'cost-calculator.middleware.yaml'));
    const out = generateMiddleware(mw);
    expect(out).toContain('middlewareOutput');
    expect(out).toContain('costUsd');
  });

  it('generates minimal middleware', () => {
    const def: MiddlewareDef = {
      name: 'simple-log',
      phase: 'request',
    };
    const out = generateMiddleware(def);
    expect(out).toContain('simpleLog');
    expect(out).toContain('async');
    expect(out).not.toContain('lookup');
  });
});
