import { describe, it, expect } from 'vitest';
import { buildViews } from '../src/pipeline.js';
import { resolve, join } from 'node:path';

const schemaDir = resolve(__dirname, '../../schema/views');

describe('View Pipeline (E2E)', () => {
  it('compiles schema/views/ to generated files', () => {
    const result = buildViews(schemaDir);

    // Should generate files for each view YAML
    expect(result.pages.length).toBeGreaterThan(0);
    expect(result.files.length).toBeGreaterThan(0);

    // Should have page files
    const pageFiles = result.files.filter((f) => f.path.endsWith('.page.tsx'));
    expect(pageFiles.length).toBe(result.pages.length);

    // Should have routes.ts
    const routesFile = result.files.find((f) => f.path === 'routes.ts');
    expect(routesFile).toBeDefined();
    expect(routesFile!.content).toContain('routeManifest');

    // Should have component barrel
    const barrelFile = result.files.find((f) => f.path === 'components/index.ts');
    expect(barrelFile).toBeDefined();

    // All generated code should have the @generated header
    for (const file of result.files) {
      expect(file.content).toContain('@generated by flusk-lang');
    }
  });

  it('all generated pages contain valid JSX structure', () => {
    const result = buildViews(schemaDir);
    const pageFiles = result.files.filter((f) => f.path.endsWith('.page.tsx'));

    for (const file of pageFiles) {
      // Has import
      expect(file.content).toContain('createFileRoute');
      // Has component function
      expect(file.content).toContain('function');
      // Has return with JSX
      expect(file.content).toContain('return (');
    }
  });

  it('reports diagnostics but does not crash', () => {
    const result = buildViews(schemaDir);
    // Diagnostics may exist (warnings about missing loaders, etc.)
    // but the pipeline should not throw
    expect(result.pages).toBeDefined();
  });

  it('returns empty result for non-existent dir', () => {
    const result = buildViews('/tmp/nonexistent-views-dir');
    expect(result.files).toHaveLength(0);
    expect(result.pages).toHaveLength(0);
  });
});
