import { describe, it, expect } from 'vitest';
import { join } from 'node:path';
import { parsePlugin } from '../src/parsers/plugin.parser.js';
import { generatePlugin } from '../src/generators/node/plugin.gen.js';
import type { PluginDef } from '../src/parsers/plugin.parser.js';

const examples = join(__dirname, '../../examples');

describe('Plugin Parser', () => {
  it('parses otel-capture plugin', () => {
    const plugin = parsePlugin(join(examples, 'otel-capture.plugin.yaml'));
    expect(plugin.name).toBe('otel-capture');
    expect(plugin.type).toBe('fastify-plugin');
  });

  it('parses hooks', () => {
    const plugin = parsePlugin(join(examples, 'otel-capture.plugin.yaml'));
    expect(plugin.hooks).toBeDefined();
    expect(plugin.hooks!.onRequest).toHaveLength(1);
    expect(plugin.hooks!.onResponse).toHaveLength(1);
  });

  it('parses hook actions', () => {
    const plugin = parsePlugin(join(examples, 'otel-capture.plugin.yaml'));
    expect(plugin.hooks!.onRequest[0].action).toBe('startSpan');
    expect(plugin.hooks!.onResponse[0].action).toBe('endSpan');
  });

  it('parses decorators', () => {
    const plugin = parsePlugin(join(examples, 'otel-capture.plugin.yaml'));
    expect(plugin.decorators).toHaveLength(1);
    expect(plugin.decorators![0].name).toBe('fluskCapture');
    expect(plugin.decorators![0].type).toBe('function');
  });

  it('parses options', () => {
    const plugin = parsePlugin(join(examples, 'otel-capture.plugin.yaml'));
    expect(plugin.options).toBeDefined();
    expect(plugin.options!.prefix).toBe('/v1');
  });
});

describe('Plugin Generator', () => {
  it('generates fastify-plugin with header', () => {
    const plugin = parsePlugin(join(examples, 'otel-capture.plugin.yaml'));
    const out = generatePlugin(plugin);
    expect(out).toContain('@generated by flusk-lang');
    expect(out).toContain('fastify-plugin');
    expect(out).toContain('fp(');
  });

  it('generates hook registrations', () => {
    const plugin = parsePlugin(join(examples, 'otel-capture.plugin.yaml'));
    const out = generatePlugin(plugin);
    expect(out).toContain("addHook('onRequest'");
    expect(out).toContain("addHook('onResponse'");
  });

  it('generates span start/end', () => {
    const plugin = parsePlugin(join(examples, 'otel-capture.plugin.yaml'));
    const out = generatePlugin(plugin);
    expect(out).toContain('startSpan');
    expect(out).toContain('span?.end()');
  });

  it('generates decorator registration', () => {
    const plugin = parsePlugin(join(examples, 'otel-capture.plugin.yaml'));
    const out = generatePlugin(plugin);
    expect(out).toContain("decorate('fluskCapture'");
    expect(out).toContain('() => {}');
  });

  it('generates minimal plugin', () => {
    const def: PluginDef = {
      name: 'basic-plugin',
      type: 'fastify-plugin',
    };
    const out = generatePlugin(def);
    expect(out).toContain('basicPlugin');
    expect(out).toContain('fp(');
    expect(out).toContain("name: 'basic-plugin'");
  });

  it('generates options interface when present', () => {
    const plugin = parsePlugin(join(examples, 'otel-capture.plugin.yaml'));
    const out = generatePlugin(plugin);
    expect(out).toContain('OtelCaptureOptions');
    expect(out).toContain('prefix');
  });
});
