import { describe, it, expect } from 'vitest';
import { generateEntityHooks, hooksFileName } from '../src/generators/react/hooks.gen.js';
import type { EntityDef } from '../src/parsers/entity.parser.js';
import {
  mapColorToTailwind,
  mapBorderRadiusToTailwind,
  mapShadowToTailwind,
  mapGapToTailwind,
  mapSpaceYToTailwind,
  mapPaddingToTailwind,
  mapMarginToTailwind,
  mapJustifyToTailwind,
  mapAlignToTailwind,
  mapSizeToTailwind,
  mapWeightToTailwind,
  mapTextAlignToTailwind,
  mapWidthToTailwind,
  mapHeightToTailwind,
  mapBadgeVariantToTailwind,
  mapButtonVariantToTailwind,
} from '../src/generators/react/tailwind.js';

// ─── Fixtures ────────────────────────────────────────────────────────────────

const userEntity: EntityDef = {
  name: 'User',
  description: 'Application user',
  fields: [
    { name: 'email', type: 'string', required: true },
    { name: 'name', type: 'string', required: true },
    { name: 'role', type: 'enum', values: ['admin', 'member'], required: false },
  ],
};

const postEntity: EntityDef = {
  name: 'Post',
  fields: [
    { name: 'title', type: 'string', required: true },
    { name: 'body', type: 'string', required: false },
    { name: 'published', type: 'boolean', required: false },
  ],
};

// ─── React Query Hooks Generator ─────────────────────────────────────────────

describe('generateEntityHooks', () => {
  it('includes @generated header', () => {
    const code = generateEntityHooks(userEntity);
    expect(code).toContain('@generated by flusk-lang');
  });

  it('imports from @tanstack/react-query', () => {
    const code = generateEntityHooks(userEntity);
    expect(code).toContain("from '@tanstack/react-query'");
    expect(code).toContain('useQuery');
    expect(code).toContain('useMutation');
    expect(code).toContain('useQueryClient');
  });

  it('imports the entity type', () => {
    const code = generateEntityHooks(userEntity);
    expect(code).toContain("import type { User } from '../types/User'");
  });

  it('generates query key object', () => {
    const code = generateEntityHooks(userEntity);
    expect(code).toContain('userKeys');
    expect(code).toContain("all: ['users'] as const");
    expect(code).toContain("detail: (id: string) => ['users', id] as const");
  });

  it('generates list hook', () => {
    const code = generateEntityHooks(userEntity);
    expect(code).toContain('function useUsers()');
    expect(code).toContain("fetch('/api/users')");
    expect(code).toContain('Promise<User[]>');
  });

  it('generates single-item hook', () => {
    const code = generateEntityHooks(userEntity);
    expect(code).toContain('function useUser(id: string)');
    expect(code).toContain('/api/users/${id}');
    expect(code).toContain('enabled: Boolean(id)');
  });

  it('generates create mutation', () => {
    const code = generateEntityHooks(userEntity);
    expect(code).toContain('function useCreateUser()');
    expect(code).toContain("method: 'POST'");
    expect(code).toContain("Omit<User, 'id' | 'createdAt' | 'updatedAt'>");
    expect(code).toContain('queryClient.invalidateQueries');
  });

  it('generates update mutation', () => {
    const code = generateEntityHooks(userEntity);
    expect(code).toContain('function useUpdateUser()');
    expect(code).toContain("method: 'PATCH'");
    expect(code).toContain('Partial<User>');
    expect(code).toContain('id: string; data: Partial<User>');
  });

  it('generates delete mutation', () => {
    const code = generateEntityHooks(userEntity);
    expect(code).toContain('function useDeleteUser()');
    expect(code).toContain("method: 'DELETE'");
    expect(code).toContain('removeQueries');
  });

  it('works for another entity (Post)', () => {
    const code = generateEntityHooks(postEntity);
    expect(code).toContain('function usePosts()');
    expect(code).toContain('function usePost(id: string)');
    expect(code).toContain('function useCreatePost()');
    expect(code).toContain('function useUpdatePost()');
    expect(code).toContain('function useDeletePost()');
    expect(code).toContain("fetch('/api/posts')");
    expect(code).toContain("import type { Post } from '../types/Post'");
  });
});

describe('hooksFileName', () => {
  it('returns correct filename for User', () => {
    expect(hooksFileName(userEntity)).toBe('useUser.hooks.ts');
  });

  it('returns correct filename for Post', () => {
    expect(hooksFileName(postEntity)).toBe('usePost.hooks.ts');
  });
});

// ─── Tailwind Utilities ───────────────────────────────────────────────────────

describe('mapColorToTailwind', () => {
  it('maps plain color', () => {
    expect(mapColorToTailwind('gray-100')).toBe('bg-gray-100');
  });

  it('maps semantic color with shade using dot notation', () => {
    expect(mapColorToTailwind('primary.500')).toBe('bg-blue-500');
    expect(mapColorToTailwind('danger.100')).toBe('bg-red-100');
    expect(mapColorToTailwind('success.50')).toBe('bg-green-50');
  });

  it('uses custom prefix', () => {
    expect(mapColorToTailwind('primary.800', 'text')).toBe('text-blue-800');
    expect(mapColorToTailwind('gray-200', 'border')).toBe('border-gray-200');
  });

  it('passes through unknown semantic colors', () => {
    expect(mapColorToTailwind('purple.400')).toBe('bg-purple-400');
  });
});

describe('mapBorderRadiusToTailwind', () => {
  it('maps known sizes', () => {
    expect(mapBorderRadiusToTailwind('sm')).toBe('rounded-sm');
    expect(mapBorderRadiusToTailwind('lg')).toBe('rounded-lg');
    expect(mapBorderRadiusToTailwind('full')).toBe('rounded-full');
  });

  it('defaults to rounded', () => {
    expect(mapBorderRadiusToTailwind('unknown')).toBe('rounded');
  });
});

describe('mapShadowToTailwind', () => {
  it('maps known sizes', () => {
    expect(mapShadowToTailwind('sm')).toBe('shadow-sm');
    expect(mapShadowToTailwind('xl')).toBe('shadow-xl');
  });

  it('defaults to shadow', () => {
    expect(mapShadowToTailwind('huge')).toBe('shadow');
  });
});

describe('mapGapToTailwind', () => {
  it('maps semantic sizes', () => {
    expect(mapGapToTailwind('xs')).toBe('gap-1');
    expect(mapGapToTailwind('sm')).toBe('gap-2');
    expect(mapGapToTailwind('md')).toBe('gap-4');
    expect(mapGapToTailwind('lg')).toBe('gap-6');
    expect(mapGapToTailwind('xl')).toBe('gap-8');
  });

  it('defaults to gap-4', () => {
    expect(mapGapToTailwind('huge')).toBe('gap-4');
  });
});

describe('mapSpaceYToTailwind', () => {
  it('maps semantic sizes', () => {
    expect(mapSpaceYToTailwind('sm')).toBe('space-y-2');
    expect(mapSpaceYToTailwind('md')).toBe('space-y-4');
  });
});

describe('mapPaddingToTailwind', () => {
  it('maps semantic sizes', () => {
    expect(mapPaddingToTailwind('xs')).toBe('p-1');
    expect(mapPaddingToTailwind('md')).toBe('p-4');
    expect(mapPaddingToTailwind('2xl')).toBe('p-12');
  });
});

describe('mapMarginToTailwind', () => {
  it('maps semantic sizes with type prefix', () => {
    expect(mapMarginToTailwind('mb', 'sm')).toBe('mb-2');
    expect(mapMarginToTailwind('mt', 'lg')).toBe('mt-6');
  });
});

describe('mapJustifyToTailwind', () => {
  it('maps justify values', () => {
    expect(mapJustifyToTailwind('center')).toBe('justify-center');
    expect(mapJustifyToTailwind('space-between')).toBe('justify-between');
    expect(mapJustifyToTailwind('end')).toBe('justify-end');
  });

  it('defaults to justify-start', () => {
    expect(mapJustifyToTailwind('unknown')).toBe('justify-start');
  });
});

describe('mapAlignToTailwind', () => {
  it('maps align values', () => {
    expect(mapAlignToTailwind('center')).toBe('items-center');
    expect(mapAlignToTailwind('stretch')).toBe('items-stretch');
  });

  it('defaults to items-start', () => {
    expect(mapAlignToTailwind('unknown')).toBe('items-start');
  });
});

describe('mapSizeToTailwind', () => {
  it('maps text sizes', () => {
    expect(mapSizeToTailwind('xs')).toBe('text-xs');
    expect(mapSizeToTailwind('2xl')).toBe('text-2xl');
    expect(mapSizeToTailwind('base')).toBe('text-base');
  });
});

describe('mapWeightToTailwind', () => {
  it('maps font weights', () => {
    expect(mapWeightToTailwind('bold')).toBe('font-bold');
    expect(mapWeightToTailwind('semibold')).toBe('font-semibold');
    expect(mapWeightToTailwind('light')).toBe('font-light');
  });
});

describe('mapTextAlignToTailwind', () => {
  it('maps text alignment', () => {
    expect(mapTextAlignToTailwind('center')).toBe('text-center');
    expect(mapTextAlignToTailwind('right')).toBe('text-right');
    expect(mapTextAlignToTailwind('left')).toBe('text-left');
  });
});

describe('mapWidthToTailwind', () => {
  it('maps 100% to w-full', () => {
    expect(mapWidthToTailwind('100%')).toBe('w-full');
  });

  it('maps px values to arbitrary', () => {
    expect(mapWidthToTailwind('320px')).toBe('w-[320px]');
  });

  it('passes through Tailwind fractions', () => {
    expect(mapWidthToTailwind('1/2')).toBe('w-1/2');
  });
});

describe('mapHeightToTailwind', () => {
  it('maps 100% to h-full', () => {
    expect(mapHeightToTailwind('100%')).toBe('h-full');
  });

  it('maps 100vh to h-screen', () => {
    expect(mapHeightToTailwind('100vh')).toBe('h-screen');
  });

  it('maps px values to arbitrary', () => {
    expect(mapHeightToTailwind('200px')).toBe('h-[200px]');
  });
});

describe('mapBadgeVariantToTailwind', () => {
  it('maps badge variants', () => {
    expect(mapBadgeVariantToTailwind('success')).toBe('bg-green-100 text-green-800');
    expect(mapBadgeVariantToTailwind('danger')).toBe('bg-red-100 text-red-800');
    expect(mapBadgeVariantToTailwind('warning')).toBe('bg-yellow-100 text-yellow-800');
    expect(mapBadgeVariantToTailwind('primary')).toBe('bg-blue-100 text-blue-800');
  });

  it('defaults to gray', () => {
    expect(mapBadgeVariantToTailwind('unknown')).toBe('bg-gray-100 text-gray-800');
  });
});

describe('mapButtonVariantToTailwind', () => {
  it('maps button variants', () => {
    expect(mapButtonVariantToTailwind('primary')).toContain('bg-blue-600');
    expect(mapButtonVariantToTailwind('ghost')).toContain('bg-transparent');
    expect(mapButtonVariantToTailwind('outline')).toContain('border');
  });

  it('defaults to primary', () => {
    expect(mapButtonVariantToTailwind('unknown')).toContain('bg-blue-600');
  });
});
