import { describe, it, expect } from 'vitest';
import { generatePage } from '../src/generators/react/page.gen.js';
import { generateLoader } from '../src/generators/react/loader.gen.js';
import { generateRoutes, generateComponentBarrel } from '../src/generators/react/routes.gen.js';
import { parseViewFromString } from '../src/parsers/view.parser.js';

describe('React Page Generator', () => {
  it('generates a basic page with widgets', () => {
    const page = parseViewFromString(`
name: Dashboard
type: dashboard
route: /$tenant/admin
auth: true
ssr: false
loader:
  source: Dashboard
  params: [tenant]
sections:
  - type: stat-card
    source: stats.users
    label: Users
  - type: chart
    source: data.byDay
    chart:
      type: line
      xAxis: date
      yAxis: count
`);
    const code = generatePage(page);
    expect(code).toContain('@generated by flusk-lang');
    expect(code).toContain("createFileRoute('/$tenant/admin')");
    expect(code).toContain('createServerFn');
    expect(code).toContain('loadDashboard');
    expect(code).toContain('Route.useLoaderData()');
    expect(code).toContain('StatCard');
    expect(code).toContain('Chart');
    expect(code).toContain('data.stats.users');
    expect(code).toContain('data.data.byDay');
  });

  it('generates page without loader', () => {
    const page = parseViewFromString(`
name: About
type: page
route: /about
auth: false
ssr: true
sections:
  - type: hero
    heading:
      text: About Us
`);
    const code = generatePage(page);
    expect(code).not.toContain('createServerFn');
    expect(code).not.toContain('useLoaderData');
    expect(code).toContain('Hero');
  });

  it('generates conditional rendering', () => {
    const page = parseViewFromString(`
name: Test
type: page
route: /test
loader:
  source: Test
  params: []
sections:
  - type: empty-state
    show: $data.isEmpty
    message: No data yet
`);
    const code = generatePage(page);
    expect(code).toContain('data.data.isEmpty');
    expect(code).toContain('EmptyState');
  });

  it('generates loop rendering', () => {
    const page = parseViewFromString(`
name: List
type: page
route: /list
loader:
  source: Items
  params: []
sections:
  - each: $data.items
    as: item
    template:
      type: badge
      source: $item.status
`);
    const code = generatePage(page);
    expect(code).toContain('.map(');
    expect(code).toContain('Badge');
  });

  it('generates nested sections', () => {
    const page = parseViewFromString(`
name: Complex
type: dashboard
route: /complex
loader:
  source: Data
  params: []
sections:
  - name: Metrics
    type: stat-cards
    layout:
      sm: stack
      md: grid-3
    widgets:
      - type: stat-card
        source: m.a
        label: A
      - type: stat-card
        source: m.b
        label: B
      - type: stat-card
        source: m.c
        label: C
`);
    const code = generatePage(page);
    expect(code).toContain('flex flex-col gap-4');
    expect(code).toContain('md:grid-cols-3');
    expect(code).toContain('StatCard');
    // 3 stat cards
    expect(code.split('StatCard').length - 1).toBeGreaterThanOrEqual(4); // import + 3 uses
  });
});

describe('Loader Generator', () => {
  it('generates loader stub', () => {
    const page = parseViewFromString(`
name: Analytics
type: dashboard
route: /analytics
loader:
  source: Analytics
  params: [tenant, period]
sections: []
`);
    const code = generateLoader(page);
    expect(code).not.toBeNull();
    expect(code).toContain('getAnalytics');
    expect(code).toContain('tenant: string, period: string');
  });

  it('returns null for pages without loader', () => {
    const page = parseViewFromString(`
name: Static
type: page
route: /static
sections: []
`);
    expect(generateLoader(page)).toBeNull();
  });
});

describe('Routes Generator', () => {
  it('generates route barrel', () => {
    const pages = [
      parseViewFromString(`
name: Dashboard
type: dashboard
route: /admin
auth: true
ssr: false
sections: []
`),
      parseViewFromString(`
name: Analytics
type: dashboard
route: /analytics
auth: true
ssr: false
sections: []
`),
    ];
    const code = generateRoutes(pages);
    expect(code).toContain('DashboardRoute');
    expect(code).toContain('AnalyticsRoute');
    expect(code).toContain('routeManifest');
  });

  it('generates component barrel', () => {
    const code = generateComponentBarrel(['stat-card', 'chart', 'stat-card', 'data-table']);
    expect(code).toContain("export { Chart } from './Chart'");
    expect(code).toContain("export { DataTable } from './DataTable'");
    expect(code).toContain("export { StatCard } from './StatCard'");
    // Deduped
    expect(code.split('StatCard').length - 1).toBe(2); // export + from
  });
});
