import { describe, it, expect } from 'vitest';
import { join } from 'node:path';
import { parseService } from '../src/parsers/service.parser.js';
import { generateService } from '../src/generators/node/service.gen.js';
import type { ServiceDef } from '../src/parsers/service.parser.js';

const examples = join(__dirname, '../../examples');

describe('Service Parser', () => {
  it('parses llm-proxy service', () => {
    const svc = parseService(join(examples, 'llm-proxy.service.yaml'));
    expect(svc.name).toBe('llm-proxy');
    expect(svc.type).toBe('http-proxy');
    expect(svc.listen.port).toBe(8787);
  });

  it('parses upstream providers', () => {
    const svc = parseService(join(examples, 'llm-proxy.service.yaml'));
    expect(svc.upstream?.providers).toHaveLength(2);
    expect(svc.upstream?.providers[0].name).toBe('openai');
  });

  it('parses middleware references', () => {
    const svc = parseService(join(examples, 'llm-proxy.service.yaml'));
    expect(svc.middleware).toEqual(['request-capture', 'cost-calculator']);
  });

  it('parses capture config', () => {
    const svc = parseService(join(examples, 'llm-proxy.service.yaml'));
    expect(svc.capture?.entity).toBe('LlmCall');
    expect(svc.capture?.async).toBe(true);
  });

  it('parses streaming flag', () => {
    const svc = parseService(join(examples, 'llm-proxy.service.yaml'));
    expect(svc.streaming).toBe(true);
  });
});

describe('Service Generator', () => {
  it('generates Fastify server with header', () => {
    const svc = parseService(join(examples, 'llm-proxy.service.yaml'));
    const out = generateService(svc);
    expect(out).toContain('@generated by flusk-lang');
    expect(out).toContain('Fastify');
    expect(out).toContain('llmProxyServer');
  });

  it('generates provider detection', () => {
    const svc = parseService(join(examples, 'llm-proxy.service.yaml'));
    const out = generateService(svc);
    expect(out).toContain('detectProvider');
    expect(out).toContain("'openai'");
    expect(out).toContain("'anthropic'");
  });

  it('generates upstream map', () => {
    const svc = parseService(join(examples, 'llm-proxy.service.yaml'));
    const out = generateService(svc);
    expect(out).toContain('https://api.openai.com');
    expect(out).toContain('https://api.anthropic.com');
  });

  it('generates middleware hooks', () => {
    const svc = parseService(join(examples, 'llm-proxy.service.yaml'));
    const out = generateService(svc);
    expect(out).toContain('addHook');
    expect(out).toContain('requestCapture');
    expect(out).toContain('costCalculator');
  });

  it('generates listen config', () => {
    const svc = parseService(join(examples, 'llm-proxy.service.yaml'));
    const out = generateService(svc);
    expect(out).toContain('port: 8787');
    expect(out).toContain("host: '0.0.0.0'");
  });

  it('generates simple http-server without upstream', () => {
    const def: ServiceDef = {
      name: 'api-server',
      type: 'http-server',
      listen: { port: 3000 },
    };
    const out = generateService(def);
    expect(out).toContain('apiServerServer');
    expect(out).toContain('port: 3000');
    expect(out).not.toContain('detectProvider');
  });
});
