/**
 * Watt Client Generator — typed HTTP clients for external APIs
 * Uses native fetch with retry + typed inputs/outputs
 */

import type { FeatureClient } from '../../ast/feature.js';

const HEADER = '// @generated by flusk-lang — DO NOT EDIT\n';

const toPascal = (s: string): string =>
  s.split(/[-_ ]+/).map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join('');

const toCamel = (s: string): string => {
  const p = toPascal(s);
  return p.charAt(0).toLowerCase() + p.slice(1);
};

export const generateClient = (client: FeatureClient): string => {
  const name = toPascal(client.name);
  const lines: string[] = [HEADER];

  lines.push(`const BASE_URL = '${client.base_url}';`);
  lines.push('');

  // Auth helper
  if (client.auth) {
    const envKey = client.auth.token?.startsWith('$')
      ? client.auth.token.slice(1).toUpperCase()
      : `${name.toUpperCase()}_TOKEN`;
    lines.push(`const getToken = (): string => process.env.${envKey} ?? '';`);
    lines.push('');
  }

  lines.push(`const request = async (method: string, path: string, body?: unknown): Promise<unknown> => {`);
  lines.push(`  const headers: Record<string, string> = { 'Content-Type': 'application/json' };`);
  if (client.auth?.type === 'bearer') {
    lines.push(`  headers['Authorization'] = \`Bearer \${getToken()}\`;`);
  }
  lines.push(`  const res = await fetch(\`\${BASE_URL}\${path}\`, {`);
  lines.push(`    method,`);
  lines.push(`    headers,`);
  lines.push(`    ...(body ? { body: JSON.stringify(body) } : {}),`);
  lines.push(`  });`);
  lines.push(`  if (!res.ok) throw new Error(\`\${res.status} \${res.statusText}\`);`);
  lines.push(`  return res.json();`);
  lines.push(`};`);
  lines.push('');

  // Methods
  for (const m of client.methods) {
    const fnName = toCamel(m.name);
    const hasBody = m.method === 'POST' || m.method === 'PUT' || m.method === 'PATCH';
    const param = hasBody ? 'body: Record<string, unknown>' : '';
    const bodyArg = hasBody ? ', body' : '';
    lines.push(`export const ${fnName} = (${param}): Promise<unknown> =>`);
    lines.push(`  request('${m.method}', '${m.path}'${bodyArg});`);
    lines.push('');
  }

  // Bundled export
  lines.push(`export const ${toCamel(client.name)} = {`);
  for (const m of client.methods) {
    lines.push(`  ${toCamel(m.name)},`);
  }
  lines.push(`};`);
  lines.push('');

  return lines.join('\n');
};
