/**
 * Watt Command Generator — CLI commands as Fastify routes (POST /commands/:name)
 */

import type { FeatureCommand } from '../../ast/feature.js';
import { toCamel } from '../../utils/naming.js';

const HEADER = '// @generated by flusk-lang — DO NOT EDIT\n';

export const generateCommandPlugin = (commands: FeatureCommand[]): string => {
  if (commands.length === 0) return '';
  const lines: string[] = [HEADER];
  lines.push("import type { FastifyInstance, FastifyRequest, FastifyReply } from 'fastify';");
  lines.push("import fp from 'fastify-plugin';");
  lines.push('');
  lines.push('export default fp(async (app: FastifyInstance) => {');

  for (const cmd of commands) {
    const handler = toCamel(cmd.name);
    lines.push('');
    lines.push(`  // Command: ${cmd.name}`);
    lines.push(`  app.post('/commands/${cmd.name}', {`);
    lines.push(`    onRequest: [app.authenticate],`);
    lines.push(`  }, async (request: FastifyRequest, reply: FastifyReply) => {`);
    lines.push(`    const input = request.body as Record<string, unknown>;`);
    lines.push(`    // TODO: implement ${handler}`);
    lines.push(`    return reply.send({ ok: true, command: '${cmd.name}' });`);
    lines.push(`  });`);
  }

  lines.push('');
  lines.push('});');
  lines.push('');
  return lines.join('\n');
};
