/**
 * Watt Config Generator — produces all config files for a runnable Watt project
 *
 * Architecture:
 * - One DB app (shared SQLite, all migrations, auto-CRUD + GraphQL)
 * - One API app (all custom routes + business logic as Fastify plugins)
 * - Watt orchestrates both as a single server
 *
 * This is the most token-efficient architecture:
 * - DB app = zero code (just config + migrations)
 * - API app = one plugin per feature (only non-CRUD logic)
 */

import type { FeatureNode } from '../../ast/feature.js';

const toKebab = (s: string): string =>
  s.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase().replace(/[_ ]+/g, '-');

const toSnake = (s: string): string =>
  s.replace(/([a-z])([A-Z])/g, '$1_$2').toLowerCase().replace(/-/g, '_');

export interface WattConfig {
  path: string;
  content: string;
}

/** Generate root watt.json */
export const generateWattJson = (features: FeatureNode[]): WattConfig => {
  const config = {
    $schema: 'https://schemas.platformatic.dev/watt/3.0.0.json',
    server: {
      hostname: '0.0.0.0',
      port: '{PLT_SERVER_PORT}',
    },
    autoload: { path: 'apps' },
    logger: { level: '{PLT_LOG_LEVEL}' },
    cors: {
      origin: '{CORS_ORIGIN}',
      credentials: true,
    },
  };

  return { path: 'watt.json', content: JSON.stringify(config, null, 2) + '\n' };
};

/** Generate platformatic.json for DB app — handles CRUD, auth, migrations */
export const generateDbConfig = (features: FeatureNode[]): WattConfig => {
  // Build authorization rules: every entity with org_id gets row-level security
  const rules: Record<string, unknown>[] = [];
  for (const feature of features) {
    for (const entity of feature.entities) {
      const hasOrgId = entity.fields.some((f) => f.name === 'org_id');
      const tableName = toSnake(entity.name) + 's';

      if (hasOrgId) {
        // Authenticated members can only access their own org's data
        rules.push({
          role: 'member',
          entity: tableName,
          find: { checks: { orgId: 'X-PLATFORMATIC-ORG-ID' } },
          save: { checks: { orgId: 'X-PLATFORMATIC-ORG-ID' } },
          delete: { checks: { orgId: 'X-PLATFORMATIC-ORG-ID' } },
          defaults: { orgId: 'X-PLATFORMATIC-ORG-ID' },
        });
        rules.push({
          role: 'admin',
          entity: tableName,
          find: { checks: { orgId: 'X-PLATFORMATIC-ORG-ID' } },
          save: true,
          delete: true,
          defaults: { orgId: 'X-PLATFORMATIC-ORG-ID' },
        });
      }
    }
  }

  const config = {
    $schema: 'https://schemas.platformatic.dev/@platformatic/db/3.0.0.json',
    db: {
      connectionString: '{DATABASE_URL}',
      graphql: true,
      openapi: true,
    },
    migrations: {
      dir: './migrations',
      autoApply: true,
    },
    authorization: {
      jwt: { secret: '{JWT_SECRET}' },
      adminSecret: '{PLT_ADMIN_SECRET}',
      anonymousRole: 'anonymous',
      rules,
    },
  };

  return {
    path: 'apps/db/platformatic.json',
    content: JSON.stringify(config, null, 2) + '\n',
  };
};

/** Generate platformatic.json for the API app (custom routes + logic) */
export const generateApiServiceConfig = (features: FeatureNode[]): WattConfig => {
  const config = {
    $schema: 'https://schemas.platformatic.dev/@platformatic/service/3.0.0.json',
    plugins: {
      paths: ['./plugins'],
    },
    clients: [{
      serviceId: 'db',
      type: 'openapi',
    }],
  };

  return {
    path: 'apps/api/platformatic.json',
    content: JSON.stringify(config, null, 2) + '\n',
  };
};

/** Generate package.json for DB app */
export const generateDbPackageJson = (): WattConfig => {
  return {
    path: 'apps/db/package.json',
    content: JSON.stringify({ name: 'flusk-db', version: '0.1.0' }, null, 2) + '\n',
  };
};

/** Generate package.json for API app */
export const generateApiPackageJson = (): WattConfig => {
  const pkg = {
    name: 'flusk-api',
    version: '0.1.0',
    dependencies: {
      bcrypt: '^5.1.1',
      nanoid: '^5.0.0',
    },
  };
  return {
    path: 'apps/api/package.json',
    content: JSON.stringify(pkg, null, 2) + '\n',
  };
};

/** Generate .env template */
export const generateEnvTemplate = (features: FeatureNode[]): WattConfig => {
  const lines = [
    '# @generated by flusk-lang',
    'PLT_SERVER_PORT=3042',
    'PLT_LOG_LEVEL=info',
    'PLT_ADMIN_SECRET=change-me',
    'JWT_SECRET=change-me-to-a-long-random-string',
    'DATABASE_URL=sqlite://./db.sqlite',
    'CORS_ORIGIN=http://localhost:5173',
  ];

  const seen = new Set<string>();
  for (const feature of features) {
    for (const client of feature.clients) {
      const envKey = toKebab(client.name).toUpperCase().replace(/-/g, '_') + '_TOKEN';
      if (!seen.has(envKey)) {
        lines.push(`${envKey}=`);
        seen.add(envKey);
      }
    }
  }

  return { path: '.env.sample', content: lines.join('\n') + '\n' };
};

/** Generate root package.json */
export const generateRootPackageJson = (): WattConfig => {
  const pkg = {
    name: '@flusk/platform',
    version: '0.2.0',
    private: true,
    type: 'module',
    scripts: {
      start: 'wattpm start',
      dev: 'wattpm start --hot-reload',
      test: 'node --test tests/**/*.test.ts',
    },
    dependencies: {
      wattpm: '^3.0.0',
    },
    engines: { node: '>=22.0.0' },
  };
  return { path: 'package.json', content: JSON.stringify(pkg, null, 2) + '\n' };
};

/** Generate Dockerfile */
export const generateDockerfile = (): WattConfig => {
  return {
    path: 'Dockerfile',
    content: `FROM node:22-slim
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN cd apps/api && npm ci
ENV PLT_SERVER_PORT=3042
EXPOSE 3042
HEALTHCHECK --interval=30s --timeout=3s CMD curl -f http://localhost:3042/status || exit 1
CMD ["npx", "wattpm", "start"]
`,
  };
};

/** Generate render.yaml */
export const generateRenderYaml = (): WattConfig => {
  return {
    path: 'render.yaml',
    content: `services:
  - type: web
    name: flusk-platform
    runtime: docker
    plan: free
    healthCheckPath: /status
    envVars:
      - key: PLT_SERVER_PORT
        value: "3042"
      - key: PLT_LOG_LEVEL
        value: info
      - key: PLT_ADMIN_SECRET
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///data/flusk.sqlite
      - key: CORS_ORIGIN
        value: "*"
    disk:
      name: flusk-data
      mountPath: /data
      sizeGB: 1
`,
  };
};

// Keep old exports for backward compat (used by tests)
export const generateServiceConfig = generateApiServiceConfig;
