/**
 * Watt Config Generator — produces watt.json and per-app platformatic.json
 * from feature definitions
 */

import type { FeatureNode } from '../../ast/feature.js';

const HEADER = '// @generated by flusk-lang — DO NOT EDIT\n';

const toKebab = (s: string): string =>
  s.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase().replace(/[_ ]+/g, '-');

export interface WattConfig {
  path: string;
  content: string;
}

/** Generate the root watt.json that ties all apps together */
export const generateWattJson = (features: FeatureNode[]): WattConfig => {
  const apps = features.map((f) => ({
    id: toKebab(f.name),
    path: `apps/${toKebab(f.name)}`,
    config: 'platformatic.json',
  }));

  // Add DB app if any feature has entities
  const hasEntities = features.some((f) => f.entities.length > 0);
  if (hasEntities) {
    apps.unshift({
      id: 'db',
      path: 'apps/db',
      config: 'platformatic.json',
    });
  }

  const config = {
    $schema: 'https://schemas.platformatic.dev/watt/3.0.0.json',
    server: { hostname: '0.0.0.0', port: '{PLT_SERVER_PORT}' },
    autoload: { path: 'apps' },
    logger: { level: '{PLT_LOG_LEVEL}' },
  };

  return { path: 'watt.json', content: JSON.stringify(config, null, 2) + '\n' };
};

/** Generate platformatic.json for DB app (all entities) */
export const generateDbConfig = (features: FeatureNode[]): WattConfig => {
  const config = {
    $schema: 'https://schemas.platformatic.dev/@platformatic/db/3.0.0.json',
    db: {
      connectionString: '{DATABASE_URL}',
    },
    migrations: {
      dir: './migrations',
      autoApply: true,
    },
    authorization: {
      adminSecret: '{PLT_ADMIN_SECRET}',
    },
  };

  return {
    path: 'apps/db/platformatic.json',
    content: JSON.stringify(config, null, 2) + '\n',
  };
};

/** Generate platformatic.json for a feature's custom service */
export const generateServiceConfig = (feature: FeatureNode): WattConfig => {
  const name = toKebab(feature.name);
  const config = {
    $schema: 'https://schemas.platformatic.dev/@platformatic/service/3.0.0.json',
    plugins: {
      paths: ['./plugins'],
    },
  };

  return {
    path: `apps/${name}/platformatic.json`,
    content: JSON.stringify(config, null, 2) + '\n',
  };
};

/** Generate .env template */
export const generateEnvTemplate = (features: FeatureNode[]): WattConfig => {
  const lines = [
    '# @generated by flusk-lang',
    'PLT_SERVER_PORT=3042',
    'PLT_LOG_LEVEL=info',
    'PLT_ADMIN_SECRET=change-me',
    'DATABASE_URL=sqlite://./db.sqlite',
  ];

  // Add feature-specific env vars
  for (const feature of features) {
    for (const client of feature.clients) {
      const envKey = toKebab(client.name).toUpperCase().replace(/-/g, '_') + '_TOKEN';
      lines.push(`${envKey}=`);
    }
  }

  return { path: '.env.sample', content: lines.join('\n') + '\n' };
};
