/**
 * Watt Hook Generator — Platformatic entity lifecycle hooks
 */

import type { HookDef } from '../../parsers/hook.parser.js';

const HEADER = '// @generated by flusk-lang — DO NOT EDIT\n';

const HOOK_MAP: Record<string, string> = {
  preSave: 'save',
  postSave: 'afterSave',
  preDelete: 'delete',
  postDelete: 'afterDelete',
  preFind: 'find',
  postFind: 'afterFind',
};

export const generateWattHook = (hook: HookDef): string => {
  const lines = [HEADER];
  const entityVar = hook.entity.charAt(0).toLowerCase() + hook.entity.slice(1);

  lines.push("import type { FastifyInstance } from 'fastify';");
  lines.push('');
  lines.push(`/** ${hook.description ?? hook.name} */`);
  lines.push(`export default async (app: FastifyInstance): Promise<void> => {`);
  lines.push(`  const entity = app.platformatic.entities.${entityVar};`);
  lines.push('');

  for (const lc of hook.lifecycle) {
    const pltHook = HOOK_MAP[lc.event] ?? lc.event;
    const callFn = lc.call ?? `handle${lc.event.charAt(0).toUpperCase() + lc.event.slice(1)}`;
    const withArgs = lc.with ? ', ' + JSON.stringify(lc.with) : '';

    if (lc.event.startsWith('pre')) {
      lines.push(`  entity.addHook('${pltHook}', async (original, context) => {`);
      lines.push(`    await ${callFn}(context${withArgs});`);
      lines.push(`    return original(context);`);
      lines.push(`  });`);
    } else {
      lines.push(`  entity.addHook('${pltHook}', async (result, context) => {`);
      lines.push(`    await ${callFn}(result, context${withArgs});`);
      lines.push(`    return result;`);
      lines.push(`  });`);
    }
    lines.push('');
  }

  lines.push('};');
  lines.push('');
  return lines.join('\n');
};
