/**
 * Logic Code Generator — compiles Logic DSL AST to TypeScript
 *
 * Generates Fastify-compatible handler code that uses:
 * - Platformatic entity API (app.platformatic.entities.*)
 * - Built-in primitives (bcrypt, jwt, nanoid, etc.)
 * - Fastify reply for HTTP responses
 */

import type {
  LogicBlock, LogicNode, Expression,
  SetNode, AssertNode, IfNode, MapNode,
  EmitNode, ReturnNode, DbCallNode, PrimitiveCallNode,
} from '../../ast/logic.js';
import { toCamel, capitalize, escStr } from '../../utils/naming.js';
import { emitExpr } from './expr-emitter.js';
import { emitDbCall, emitPrimitive } from './db-emitter.js';

const INDENT = '  ';

/** Detect which primitives are used so we can generate imports */
export const collectImports = (block: LogicBlock): Set<string> => {
  const imports = new Set<string>();
  const walk = (nodes: LogicNode[]): void => {
    for (const node of nodes) {
      if (node.kind === 'primitive') {
        const pn = node as PrimitiveCallNode;
        imports.add(pn.name.split('.')[0]!);
      }
      if (node.kind === 'set') {
        walkExpr((node as SetNode).expression, imports);
      }
      if (node.kind === 'if') {
        const ifN = node as IfNode;
        walk(ifN.then);
        if (ifN.else) walk(ifN.else);
      }
      if (node.kind === 'map') {
        walk((node as MapNode).steps);
      }
    }
  };
  walk(block.steps);
  return imports;
};

const walkExpr = (expr: Expression, imports: Set<string>): void => {
  if (expr.type === 'call') {
    const lib = expr.name.split('.')[0]!;
    if (PRIMITIVE_MAP[expr.name] || PRIMITIVE_MAP[lib]) {
      imports.add(lib);
    }
    expr.args.forEach((a) => walkExpr(a, imports));
  }
  if (expr.type === 'binary') {
    walkExpr(expr.left, imports);
    walkExpr(expr.right, imports);
  }
  if (expr.type === 'unary') {
    walkExpr(expr.operand, imports);
  }
  if (expr.type === 'object') {
    Object.values(expr.properties).forEach((v) => walkExpr(v, imports));
  }
  if (expr.type === 'array') {
    expr.elements.forEach((e) => walkExpr(e, imports));
  }
};

/** Map primitive names to actual import code */
const PRIMITIVE_MAP: Record<string, string> = {
  hash: "import bcrypt from 'bcrypt';",
  verify: "import bcrypt from 'bcrypt';",
  bcrypt: "import bcrypt from 'bcrypt';",
  jwt: "// JWT handled via app.jwt (fastify-jwt plugin)",
  slugify: "const slugify = (s: string) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');",
  nanoid: "import { nanoid } from 'nanoid';",
  apikey: "import { nanoid } from 'nanoid';",
  now: "// now() = new Date().toISOString()",
  crypto: "import { randomUUID, createHash } from 'node:crypto';",
};

const tsType = (t: string): string => {
  const map: Record<string, string> = {
    string: 'string', integer: 'number', number: 'number',
    float: 'number', boolean: 'boolean', date: 'string',
    datetime: 'string', json: 'unknown', object: 'Record<string, unknown>',
    array: 'unknown[]',
  };
  return map[t] ?? 'unknown';
};

/** Generate full function file from a logic block */
export const generateLogicFunction = (
  fnName: string,
  inputFields: { name: string; type: string }[],
  block: LogicBlock,
  featureName: string,
): string => {
  const imports = collectImports(block);
  const lines: string[] = [];

  lines.push('// @generated by flusk-lang logic compiler');
  lines.push("import type { FastifyInstance, FastifyRequest, FastifyReply } from 'fastify';");
  lines.push('');

  const importSet = new Set<string>();
  for (const lib of imports) {
    const imp = PRIMITIVE_MAP[lib];
    if (imp && !importSet.has(imp)) {
      lines.push(imp);
      importSet.add(imp);
    }
  }
  if (importSet.size > 0) lines.push('');

  if (inputFields.length > 0) {
    lines.push(`interface ${capitalize(fnName)}Input {`);
    for (const f of inputFields) {
      lines.push(`  ${toCamel(f.name)}: ${tsType(f.type)};`);
    }
    lines.push('}');
    lines.push('');
  }

  const safeName = fnName.includes('-') || fnName.includes('_') ? toCamel(fnName) : fnName;
  const inputType = inputFields.length > 0 ? `${capitalize(fnName)}Input` : 'unknown';
  lines.push(`export default async function ${safeName}(`);
  lines.push(`  app: FastifyInstance,`);
  lines.push(`  request: FastifyRequest,`);
  lines.push(`  reply: FastifyReply,`);
  lines.push(`  input: ${inputType},`);
  lines.push(`) {`);

  lines.push(generateBlock(block, 1));
  lines.push('}');
  lines.push('');

  return lines.join('\n');
};

/** Generate a route handler that parses input and calls logic */
export const generateLogicRouteHandler = (
  routeName: string,
  method: string,
  inputFields: { name: string; type: string }[],
  block: LogicBlock,
  featureName: string,
): string => {
  const fnName = toCamel(routeName);
  return generateLogicFunction(fnName, inputFields, block, featureName);
};

const generateBlock = (block: LogicBlock, depth: number): string =>
  block.steps.map((step) => generateStep(step, depth)).join('\n');

const generateStep = (node: LogicNode, depth: number): string => {
  const pad = INDENT.repeat(depth);

  switch (node.kind) {
    case 'set': {
      const n = node as SetNode;
      return `${pad}const ${n.variable} = ${emitExpr(n.expression)};`;
    }
    case 'assert': {
      const n = node as AssertNode;
      let negated: string;
      if (n.condition.type === 'unary' && n.condition.op === '!') {
        negated = emitExpr(n.condition.operand);
      } else {
        negated = `!(${emitExpr(n.condition)})`;
      }
      return [
        `${pad}if (${negated}) {`,
        `${pad}${INDENT}return reply.code(${n.statusCode}).send({ error: '${escStr(n.message)}' });`,
        `${pad}}`,
      ].join('\n');
    }
    case 'if': {
      const n = node as IfNode;
      const lines = [`${pad}if (${emitExpr(n.condition)}) {`];
      for (const step of n.then) lines.push(generateStep(step, depth + 1));
      if (n.else?.length) {
        lines.push(`${pad}} else {`);
        for (const step of n.else) lines.push(generateStep(step, depth + 1));
      }
      lines.push(`${pad}}`);
      return lines.join('\n');
    }
    case 'map': {
      const n = node as MapNode;
      const lines = [
        `${pad}const results = [];`,
        `${pad}for (const ${n.variable} of ${emitExpr(n.collection)}) {`,
      ];
      for (const step of n.steps) lines.push(generateStep(step, depth + 1));
      lines.push(`${pad}}`);
      return lines.join('\n');
    }
    case 'emit': {
      const n = node as EmitNode;
      const payloadParts = Object.entries(n.payload)
        .map(([k, v]) => `${k}: ${emitExpr(v)}`);
      return `${pad}app.emit('${toCamel(n.event)}', { ${payloadParts.join(', ')} });`;
    }
    case 'return': {
      const n = node as ReturnNode;
      return `${pad}return reply.send(${emitExpr(n.value)});`;
    }
    case 'db': {
      const n = node as DbCallNode;
      return `${pad}${emitDbCall(n)};`;
    }
    case 'primitive': {
      return `${pad}${emitPrimitive(node as PrimitiveCallNode)};`;
    }
    default:
      return `${pad}// TODO: unknown logic node kind "${node.kind}"`;
  }
};

/** Generate Platformatic authorization config from entity auth rules */
export const generateAuthConfig = (features: {
  entities: { name: string; fields: { name: string }[] }[];
  auth?: { jwt?: { secret: string }; rules?: unknown[] };
}[]): Record<string, unknown> => {
  const rules: unknown[] = [];

  for (const feature of features) {
    for (const entity of feature.entities) {
      const hasOrgId = entity.fields.some((f) => f.name === 'org_id');
      if (hasOrgId) {
        const tableName = entity.name.replace(/-/g, '_') + 's';
        rules.push({
          role: 'member',
          entity: tableName,
          find: { checks: { orgId: 'X-PLATFORMATIC-ORG-ID' } },
          save: { checks: { orgId: 'X-PLATFORMATIC-ORG-ID' } },
          delete: { checks: { orgId: 'X-PLATFORMATIC-ORG-ID' } },
          defaults: { orgId: 'X-PLATFORMATIC-ORG-ID' },
        });
        rules.push({
          role: 'admin',
          entity: tableName,
          find: { checks: { orgId: 'X-PLATFORMATIC-ORG-ID' } },
          save: { checks: { orgId: 'X-PLATFORMATIC-ORG-ID' } },
          delete: { checks: { orgId: 'X-PLATFORMATIC-ORG-ID' } },
          defaults: { orgId: 'X-PLATFORMATIC-ORG-ID' },
        });
      }
    }
  }

  return {
    jwt: { secret: '{JWT_SECRET}' },
    rules,
  };
};
