/**
 * Watt Middleware Generator — Fastify hooks for request/response lifecycle
 */

import type { FeatureMiddleware } from '../../ast/feature.js';
import { toCamel } from '../../utils/naming.js';

const HEADER = '// @generated by flusk-lang — DO NOT EDIT\n';

const PHASE_MAP: Record<string, string> = {
  request: 'onRequest',
  response: 'onSend',
  error: 'onError',
  pre: 'onRequest',
  post: 'onResponse',
};

export const generateMiddlewarePlugin = (middlewares: FeatureMiddleware[]): string => {
  if (middlewares.length === 0) return '';
  const lines: string[] = [HEADER];
  lines.push("import type { FastifyInstance, FastifyRequest, FastifyReply } from 'fastify';");
  lines.push("import fp from 'fastify-plugin';");
  lines.push('');
  lines.push('export default fp(async (app: FastifyInstance) => {');

  for (const mw of middlewares) {
    const fnName = toCamel(mw.name);
    const hook = PHASE_MAP[mw.type ?? 'request'] ?? 'onRequest';
    lines.push('');
    lines.push(`  // Middleware: ${mw.name}`);
    lines.push(`  app.addHook('${hook}', async (request: FastifyRequest, reply: FastifyReply) => {`);
    lines.push(`    // TODO: implement ${fnName}`);
    lines.push(`  });`);
  }

  lines.push('');
  lines.push('});');
  lines.push('');
  return lines.join('\n');
};
