/**
 * Watt Plugin Generator — Fastify plugins with proper route wiring
 *
 * Each feature becomes one plugin file that:
 * 1. Registers custom routes (non-CRUD — Platformatic handles CRUD)
 * 2. Imports and calls logic functions
 * 3. Handles auth (JWT verification, API key check)
 * 4. Validates input with JSON Schema
 */

import type { FeatureNode, FeatureRoute, FeatureFunction } from '../../ast/feature.js';
import { toCamel } from '../../utils/naming.js';

export { generateAuthPlugin } from './plugin-auth.gen.js';
export { generateRouteHandler, generateFunction } from './plugin-stub.gen.js';

const HEADER = '// @generated by flusk-lang — DO NOT EDIT\n';

const toJsonSchemaType = (t: string): string => {
  const map: Record<string, string> = {
    string: 'string', integer: 'integer', number: 'number',
    float: 'number', boolean: 'boolean', object: 'object',
    array: 'array', date: 'string', datetime: 'string',
  };
  return map[t] ?? 'string';
};

/** Generate a complete Fastify plugin for a feature */
export const generatePlugin = (feature: FeatureNode): string => {
  const lines: string[] = [HEADER];
  const logicFns = collectLogicFns(feature);

  lines.push("import type { FastifyInstance, FastifyRequest, FastifyReply } from 'fastify';");
  lines.push("import fp from 'fastify-plugin';");
  lines.push('');

  for (const fnName of logicFns) {
    lines.push(`import ${fnName} from '../functions/${fnName}.js';`);
  }
  lines.push('');

  lines.push(`export default fp(async (app: FastifyInstance) => {`);

  for (const route of feature.routes) {
    lines.push('');
    appendRouteRegistration(lines, route);
  }

  lines.push('');
  lines.push('});');
  lines.push('');

  return lines.join('\n');
};

const collectLogicFns = (feature: FeatureNode): Set<string> => {
  const logicFns = new Set<string>();
  for (const fn of feature.functions) {
    if (fn.logic && fn.logic.length > 0) logicFns.add(toCamel(fn.name));
  }
  for (const route of feature.routes) {
    logicFns.add(toCamel(route.name));
  }
  return logicFns;
};

const appendRouteRegistration = (lines: string[], route: FeatureRoute): void => {
  const method = route.method.toLowerCase();
  const handler = toCamel(route.name);
  const hasBody = route.input && route.input.length > 0 && route.method !== 'GET';
  const hasQuery = route.input && route.input.length > 0 && route.method === 'GET';

  lines.push(`  // ${route.method} ${route.path}`);
  lines.push(`  app.${method}('${route.path}', {`);

  if (hasBody) appendBodySchema(lines, route);

  if (route.auth === 'session') lines.push(`    onRequest: [app.authenticate],`);
  else if (route.auth === 'api-key') lines.push(`    onRequest: [app.authenticateApiKey],`);

  lines.push(`  }, async (request: FastifyRequest, reply: FastifyReply) => {`);

  if (hasBody) lines.push(`    const input = request.body as Record<string, unknown>;`);
  else if (hasQuery) lines.push(`    const input = request.query as Record<string, unknown>;`);
  else lines.push(`    const input = {};`);

  if (route.path.includes(':')) {
    lines.push(`    const params = request.params as Record<string, string>;`);
    lines.push(`    Object.assign(input, params);`);
  }

  if (route.auth === 'session') {
    lines.push(`    const user = request.user as { sub: number; org: number; role: string };`);
    lines.push(`    Object.assign(input, { org_id: user.org, user_id: user.sub });`);
  }
  if (route.auth === 'api-key') {
    lines.push(`    const typed = request as FastifyRequest & { orgId: number };`);
    lines.push(`    Object.assign(input, { org_id: typed.orgId });`);
  }

  lines.push(`    return ${handler}(app, request, reply, input);`);
  lines.push(`  });`);
};

const appendBodySchema = (lines: string[], route: FeatureRoute): void => {
  const props: string[] = [];
  const required: string[] = [];
  for (const inp of route.input!) {
    props.push(`          ${toCamel(inp.name)}: { type: '${toJsonSchemaType(inp.type)}' }`);
    if (inp.required) required.push(`'${toCamel(inp.name)}'`);
  }
  lines.push(`    schema: {`);
  lines.push(`      body: {`);
  lines.push(`        type: 'object',`);
  lines.push(`        properties: {`);
  lines.push(props.join(',\n'));
  lines.push(`        },`);
  if (required.length > 0) lines.push(`        required: [${required.join(', ')}],`);
  lines.push(`      },`);
  lines.push(`    },`);
};
