/**
 * Stub generators — route handlers and functions without logic blocks
 */

import type { FeatureRoute, FeatureFunction } from '../../ast/feature.js';
import { toCamel } from '../../utils/naming.js';

const HEADER = '// @generated by flusk-lang — DO NOT EDIT\n';

/** Generate a stub handler for routes without logic blocks */
export const generateRouteHandler = (route: FeatureRoute): string => {
  const lines: string[] = [HEADER];
  const name = toCamel(route.name);

  lines.push("import type { FastifyInstance, FastifyRequest, FastifyReply } from 'fastify';");
  lines.push('');
  lines.push(`export default async function ${name}(`);
  lines.push(`  app: FastifyInstance,`);
  lines.push(`  request: FastifyRequest,`);
  lines.push(`  reply: FastifyReply,`);
  lines.push(`  input: Record<string, unknown>,`);
  lines.push(`) {`);

  if (route.loader) {
    const parts = route.loader.split('.');
    const entity = parts.length > 1 ? toCamel(parts[0]!) : toCamel(route.loader.replace(/-/g, ' '));
    lines.push(`  const orgId = input.org_id;`);
    lines.push(`  const data = await app.platformatic.entities.${entity}.find({`);
    lines.push(`    where: orgId ? { orgId: { eq: orgId } } : {},`);
    lines.push(`  });`);
    lines.push(`  return reply.send(data);`);
  } else if (route.actions?.length) {
    appendActionLines(lines, route);
  } else {
    lines.push(`  // TODO: implement ${name}`);
    lines.push(`  return reply.send({ ok: true });`);
  }

  lines.push('}');
  lines.push('');
  return lines.join('\n');
};

const appendActionLines = (lines: string[], route: FeatureRoute): void => {
  for (const action of route.actions ?? []) {
    if (action.type === 'create' || action.type === 'update') {
      const entity = toCamel(action.target);
      lines.push(`  const result = await app.platformatic.entities.${entity}.save({`);
      lines.push(`    input: input as Record<string, string>,`);
      lines.push(`  });`);
      lines.push(`  return reply.send(result);`);
    } else if (action.type === 'delete') {
      const entity = toCamel(action.target);
      const paramName = toCamel(route.path.split(':').pop() ?? 'id');
      lines.push(`  await app.platformatic.entities.${entity}.delete({`);
      lines.push(`    where: { id: { eq: (input.id ?? input.${paramName}) as string } },`);
      lines.push(`  });`);
      lines.push(`  return reply.send({ ok: true });`);
    } else if (action.type === 'emit') {
      lines.push(`  app.emit('${toCamel(action.target)}', input);`);
    } else if (action.type === 'validate') {
      lines.push(`  // Validation handled by JSON Schema in route config`);
    } else if (action.type === 'call') {
      lines.push(`  // TODO: call ${action.target}`);
    }
  }
  if (!route.actions?.some((a) => a.type === 'create' || a.type === 'update' || a.type === 'delete')) {
    lines.push(`  return reply.send({ ok: true });`);
  }
};

/** Generate a stub function (no logic block) */
export const generateFunction = (fn: FeatureFunction): string => {
  const lines: string[] = [HEADER];
  const name = toCamel(fn.name);

  lines.push("import type { FastifyInstance, FastifyRequest, FastifyReply } from 'fastify';");
  lines.push('');
  lines.push(`export default async function ${name}(`);
  lines.push(`  app: FastifyInstance,`);
  lines.push(`  request: FastifyRequest,`);
  lines.push(`  reply: FastifyReply,`);
  lines.push(`  input: Record<string, unknown>,`);
  lines.push(`) {`);

  if (fn.uses) {
    lines.push(`  // External call: ${fn.uses}`);
    lines.push(`  return reply.send({ todo: '${fn.uses}' });`);
  } else {
    lines.push(`  // TODO: implement ${name}`);
    if (fn.description) lines.push(`  // ${fn.description}`);
    lines.push(`  return reply.send({ ok: true });`);
  }

  lines.push('}');
  lines.push('');
  return lines.join('\n');
};
