/**
 * Watt Plugin Generator — Fastify plugins for custom business logic
 * Platformatic DB handles CRUD; plugins add custom routes + logic
 */

import type { FeatureNode, FeatureRoute, FeatureFunction } from '../../ast/feature.js';

const HEADER = '// @generated by flusk-lang — DO NOT EDIT\n';

const toCamel = (s: string): string => {
  const parts = s.split(/[-_ ]+/);
  return parts[0] + parts.slice(1).map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join('');
};

const toPascal = (s: string): string =>
  s.split(/[-_ ]+/).map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join('');

/** Collect all handler names needed by routes */
const collectHandlers = (feature: FeatureNode): string[] => {
  const explicitFns = new Set(feature.functions.map((f) => toCamel(f.name)));
  const allHandlers = new Set<string>();

  // Every route needs a handler
  for (const route of feature.routes) {
    allHandlers.add(toCamel(route.name));
  }
  // Plus explicit functions
  for (const fn of feature.functions) {
    allHandlers.add(toCamel(fn.name));
  }

  return [...allHandlers];
};

/** Generate a Fastify plugin with custom routes (non-CRUD) */
export const generatePlugin = (feature: FeatureNode): string => {
  const lines: string[] = [HEADER];
  lines.push(`import { type FastifyInstance } from 'fastify';`);
  lines.push(`import fp from 'fastify-plugin';`);
  lines.push('');

  // Import ALL handlers (explicit + auto-generated for routes)
  const handlers = collectHandlers(feature);
  for (const handler of handlers) {
    lines.push(`import { ${handler} } from '../functions/${handler}.js';`);
  }
  lines.push('');

  lines.push(`export default fp(async (app: FastifyInstance) => {`);

  // Register custom routes (non-CRUD)
  for (const route of feature.routes) {
    const method = route.method.toLowerCase();
    const handler = toCamel(route.name);

    lines.push('');
    lines.push(`  app.${method}('${route.path}', {`);

    // Add schema if there's input
    if (route.input?.length) {
      lines.push(`    schema: {`);
      lines.push(`      body: {`);
      lines.push(`        type: 'object',`);
      lines.push(`        properties: {`);
      for (const inp of route.input) {
        const jsonType = inp.type === 'number' ? 'number' : inp.type === 'boolean' ? 'boolean' : 'string';
        lines.push(`          ${inp.name}: { type: '${jsonType}' },`);
      }
      lines.push(`        },`);
      const required = route.input.filter((i) => i.required).map((i) => `'${i.name}'`);
      if (required.length) lines.push(`        required: [${required.join(', ')}],`);
      lines.push(`      },`);
      lines.push(`    },`);
    }

    // Auth
    if (route.auth && route.auth !== 'none') {
      lines.push(`    preHandler: app.auth,`);
    }

    lines.push(`  }, async (request, reply) => {`);
    lines.push(`    const result = await ${handler}(app.platformatic, request);`);
    lines.push(`    return reply.send(result);`);
    lines.push(`  });`);
  }

  lines.push(`});`);
  lines.push('');

  return lines.join('\n');
};

/** Generate a route handler function (auto-generated for routes without explicit functions) */
export const generateRouteHandler = (route: FeatureRoute): string => {
  const lines: string[] = [HEADER];
  const name = toCamel(route.name);

  lines.push(`import type { PlatformaticApp } from '@platformatic/db';`);
  lines.push(`import type { FastifyRequest } from 'fastify';`);
  lines.push('');

  lines.push(`export const ${name} = async (`);
  lines.push(`  platformatic: PlatformaticApp,`);
  lines.push(`  request: FastifyRequest,`);
  lines.push(`): Promise<unknown> => {`);

  // Generate body from route actions
  if (route.actions?.length) {
    for (const action of route.actions) {
      if (action.type === 'create') {
        const entity = toCamel(action.target);
        lines.push(`  const created = await platformatic.entities.${entity}.save({`);
        lines.push(`    input: request.body as Record<string, unknown>,`);
        lines.push(`  });`);
      } else if (action.type === 'update') {
        const entity = toCamel(action.target);
        lines.push(`  const updated = await platformatic.entities.${entity}.save({`);
        lines.push(`    input: request.body as Record<string, unknown>,`);
        lines.push(`  });`);
      } else if (action.type === 'delete') {
        const entity = toCamel(action.target);
        lines.push(`  await platformatic.entities.${entity}.delete({`);
        lines.push(`    where: { id: { eq: (request.params as Record<string, string>).id } },`);
        lines.push(`  });`);
      } else if (action.type === 'emit') {
        lines.push(`  // Emit event via request context`);
        lines.push(`  (request.server as any).events?.emit('${action.target}', request.body);`);
      } else if (action.type === 'validate') {
        lines.push(`  // Validate: ${action.target}`);
      }
    }
    lines.push(`  return { ok: true };`);
  } else if (route.loader) {
    // GET route with loader
    const entity = toCamel(route.loader.split('.')[0]);
    lines.push(`  return platformatic.entities.${entity}.find({});`);
  } else {
    lines.push(`  // TODO: implement ${name}`);
    lines.push(`  return { ok: true };`);
  }

  lines.push(`};`);
  lines.push('');

  return lines.join('\n');
};

/** Generate individual function files (business logic) */
export const generateFunction = (fn: FeatureFunction): string => {
  const lines: string[] = [HEADER];
  const name = toCamel(fn.name);

  lines.push(`import type { PlatformaticApp } from '@platformatic/db';`);
  lines.push(`import type { FastifyRequest } from 'fastify';`);
  lines.push('');

  // Input type
  if (fn.input.length > 0) {
    lines.push(`interface ${toPascal(fn.name)}Input {`);
    for (const inp of fn.input) {
      const tsType = inp.type === 'number' ? 'number' : inp.type === 'boolean' ? 'boolean' : inp.type === 'object' ? 'Record<string, unknown>' : 'string';
      lines.push(`  ${inp.name}: ${tsType};`);
    }
    lines.push(`}`);
    lines.push('');
  }

  // Output type
  const returnType = fn.output?.type === 'void' ? 'void' : 'unknown';

  lines.push(`export const ${name} = async (`);
  lines.push(`  platformatic: PlatformaticApp,`);
  lines.push(`  request: FastifyRequest,`);
  lines.push(`): Promise<${returnType}> => {`);

  if (fn.uses) {
    // External client call
    const [client, method] = fn.uses.split('.');
    lines.push(`  // Call external: ${fn.uses}`);
    lines.push(`  const client = platformatic.${toCamel(client)};`);
    lines.push(`  return client.${method}(request.body);`);
  } else {
    lines.push(`  // TODO: implement ${name}`);
    lines.push(`  return { ok: true };`);
  }

  lines.push(`};`);
  lines.push('');

  return lines.join('\n');
};
