/**
 * Auth plugin generator — JWT verification + API key lookup
 */

import type { FeatureNode } from '../../ast/feature.js';

const HEADER = '// @generated by flusk-lang — DO NOT EDIT\n';

export const generateAuthPlugin = (_features: FeatureNode[]): string => {
  const lines: string[] = [HEADER];
  lines.push("import type { FastifyInstance, FastifyRequest, FastifyReply } from 'fastify';");
  lines.push("import fp from 'fastify-plugin';");
  lines.push("import fjwt from '@fastify/jwt';");
  lines.push('');
  lines.push('export default fp(async (app: FastifyInstance) => {');
  lines.push('');
  lines.push("  // Register JWT plugin");
  lines.push("  await app.register(fjwt, {");
  lines.push("    secret: process.env.JWT_SECRET || 'dev-secret',");
  lines.push("  });");
  lines.push('');
  lines.push('  // JWT auth decorator');
  lines.push('  app.decorate("authenticate", async (request: FastifyRequest, reply: FastifyReply) => {');
  lines.push('    try {');
  lines.push('      await request.jwtVerify();');
  lines.push('    } catch (err) {');
  lines.push("      return reply.code(401).send({ error: 'Unauthorized' });");
  lines.push('    }');
  lines.push('  });');
  lines.push('');
  lines.push('  // API key auth decorator');
  lines.push('  app.decorate("authenticateApiKey", async (request: FastifyRequest, reply: FastifyReply) => {');
  lines.push("    const apiKey = request.headers['x-api-key'] as string;");
  lines.push('    if (!apiKey) {');
  lines.push("      return reply.code(401).send({ error: 'API key required' });");
  lines.push('    }');
  lines.push('    const org = await app.platformatic.entities.organization.find({');
  lines.push("      where: { apiKey: { eq: apiKey } },");
  lines.push('      limit: 1,');
  lines.push('    });');
  lines.push('    if (!org || org.length === 0) {');
  lines.push("      return reply.code(401).send({ error: 'Invalid API key' });");
  lines.push('    }');
  lines.push('    const typedRequest = request as FastifyRequest & { orgId: number };');
  lines.push('    typedRequest.orgId = org[0].id;');
  lines.push('  });');
  lines.push('');
  lines.push("  app.get('/status', async () => ({ status: 'ok', timestamp: new Date().toISOString() }));");
  lines.push('');
  lines.push('});');
  lines.push('');

  return lines.join('\n');
};
