/**
 * Watt Provider Generator — external provider adapters
 */

import type { ProviderDef } from '../../parsers/provider.parser.js';
import { toCamel } from '../../utils/naming.js';

const HEADER = '// @generated by flusk-lang — DO NOT EDIT\n';

export const generateWattProvider = (provider: ProviderDef): string => {
  const lines = [HEADER];
  const name = toCamel(provider.name);

  lines.push("import type { FastifyInstance } from 'fastify';");
  lines.push("import fp from 'fastify-plugin';");
  lines.push('');
  lines.push(`/** ${provider.description ?? provider.name} — ${provider.type} provider */`);
  lines.push(`export default fp(async (app: FastifyInstance) => {`);
  lines.push(`  const config = {`);

  for (const field of provider.config?.fields ?? []) {
    const envKey = `${provider.name.toUpperCase().replace(/-/g, '_')}_${field.name.toUpperCase()}`;
    lines.push(`    ${toCamel(field.name)}: process.env.${envKey} ?? '',`);
  }

  lines.push(`  };`);
  lines.push('');

  for (const method of provider.methods) {
    const methodName = toCamel(method.name);
    lines.push(`  const ${methodName} = async (input: Record<string, unknown>) => {`);
    lines.push(`    // TODO: implement ${methodName}`);
    lines.push(`    return { ok: true };`);
    lines.push(`  };`);
    lines.push('');
  }

  lines.push(`  app.decorate('${name}', {`);
  for (const method of provider.methods) {
    lines.push(`    ${toCamel(method.name)},`);
  }
  lines.push(`  });`);
  lines.push('');
  lines.push('});');
  lines.push('');
  return lines.join('\n');
};
