/**
 * Watt Service Generator — standalone microservice or proxy
 */

import type { ServiceDef } from '../../parsers/service.parser.js';
import { toCamel } from '../../utils/naming.js';

const HEADER = '// @generated by flusk-lang — DO NOT EDIT\n';

export const generateWattService = (service: ServiceDef): string => {
  const lines = [HEADER];
  const name = toCamel(service.name);

  lines.push("import type { FastifyInstance } from 'fastify';");
  lines.push("import fp from 'fastify-plugin';");
  lines.push('');
  lines.push(`/** ${service.description ?? service.name} — ${service.type} service */`);
  lines.push(`export default fp(async (app: FastifyInstance) => {`);

  if (service.type === 'http-proxy' && service.upstream?.providers?.length) {
    for (const up of service.upstream.providers) {
      const prefix = up.pathPrefix ?? `/${toCamel(up.name)}`;
      lines.push(`  // Proxy: ${up.name} → ${up.baseUrl}`);
      lines.push(`  app.register(import('@fastify/http-proxy'), {`);
      lines.push(`    upstream: '${up.baseUrl}',`);
      lines.push(`    prefix: '${prefix}',`);
      lines.push(`  });`);
      lines.push('');
    }
  } else {
    lines.push(`  // TODO: implement ${name} (${service.type})`);
  }

  if (service.middleware?.length) {
    lines.push(`  // Middleware: ${service.middleware.join(', ')}`);
  }

  lines.push('');
  lines.push('});');
  lines.push('');
  return lines.join('\n');
};
