/**
 * Watt Stream Generator — SSE/WebSocket endpoints as Fastify routes
 */

import type { StreamDef } from '../../parsers/stream.parser.js';
import { toCamel } from '../../utils/naming.js';

const HEADER = '// @generated by flusk-lang — DO NOT EDIT\n';

export const generateWattStream = (stream: StreamDef): string => {
  const lines = [HEADER];
  const fnName = toCamel(stream.name);

  lines.push("import type { FastifyInstance, FastifyRequest, FastifyReply } from 'fastify';");
  lines.push("import fp from 'fastify-plugin';");
  lines.push('');
  lines.push(`/** ${stream.description ?? stream.name} — ${stream.type} stream */`);
  lines.push(`export default fp(async (app: FastifyInstance) => {`);

  if (stream.type === 'sse') {
    lines.push(`  app.get('${stream.path}', async (request: FastifyRequest, reply: FastifyReply) => {`);
    lines.push(`    reply.raw.writeHead(200, {`);
    lines.push(`      'Content-Type': 'text/event-stream',`);
    lines.push(`      'Cache-Control': 'no-cache',`);
    lines.push(`      Connection: 'keep-alive',`);
    lines.push(`    });`);
    lines.push(`    // TODO: implement ${fnName} SSE stream`);
    lines.push(`    reply.raw.write('data: {"connected":true}\\n\\n');`);
    lines.push(`  });`);
  } else if (stream.type === 'websocket') {
    lines.push(`  app.get('${stream.path}', { websocket: true }, (socket) => {`);
    lines.push(`    // TODO: implement ${fnName} WebSocket stream`);
    lines.push(`    socket.send(JSON.stringify({ connected: true }));`);
    lines.push(`  });`);
  } else {
    lines.push(`  // TODO: implement ${stream.type} stream at ${stream.path}`);
  }

  lines.push('');
  lines.push('});');
  lines.push('');
  return lines.join('\n');
};
