/**
 * Component Generator - WidgetDef → reusable .tsx component files
 *
 * Generates premium React components from widget definitions.
 * Each widget type gets a typed, styled component using Tailwind CSS.
 *
 * Design system: Coral #E8384F, Blue #3B3FBF, Navy #0F1629, Warm grays
 * Font: Inter, 8pt grid spacing
 */

import type { WidgetDef, WidgetProp } from '../../parsers/widget.parser.js';

const HEADER = '// @generated by flusk-lang -- DO NOT EDIT\n';

// ── Type mapping ──────────────────────────────────────────────────────

const tsPropType = (prop: WidgetProp): string => {
  switch (prop.type) {
    case 'string': return 'string';
    case 'number': return 'number';
    case 'boolean': return 'boolean';
    case 'binding': return 'unknown';
    case 'icon': return 'string';
    case 'enum': return prop.values?.map((v) => `'${v}'`).join(' | ') ?? 'string';
    case 'string[]': return 'string[]';
    case 'object': return 'Record<string, unknown>';
    case 'object[]': return 'Record<string, unknown>[]';
    default: return 'unknown';
  }
};

// ── Component name from widget name ───────────────────────────────────

const componentName = (widgetName: string): string =>
  widgetName
    .split('-')
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join('');

// ── Generate interface ────────────────────────────────────────────────

const generateInterface = (widget: WidgetDef): string => {
  const name = componentName(widget.name);
  const lines: string[] = [`export interface ${name}Props {`];

  for (const [key, prop] of Object.entries(widget.props)) {
    const optional = prop.required ? '' : '?';
    const tsType = tsPropType(prop);
    if (prop.description) {
      lines.push(`  /** ${prop.description} */`);
    }
    // 'source' binding becomes 'data' prop (page generator passes data={data.X})
    const propName = key === 'source' && prop.type === 'binding' ? 'data' : key;
    lines.push(`  ${propName}${optional}: ${tsType};`);
  }

  // Standard props all components get
  lines.push(`  className?: string;`);
  lines.push(`  dir?: 'ltr' | 'rtl';`);
  lines.push(`}`);

  return lines.join('\n');
};

// ── Component templates by category ───────────────────────────────────

const COMPONENT_TEMPLATES: Record<string, (widget: WidgetDef) => string> = {
  'stat-card': () => `
export function StatCard({ data, label, format = 'number', icon, className = '', dir }: StatCardProps) {
  const formatValue = (val: unknown): string => {
    const num = Number(val);
    if (isNaN(num)) return String(val ?? '');
    switch (format) {
      case 'currency': return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(num);
      case 'percent': return num.toFixed(1) + '%';
      case 'duration': return num >= 3600 ? (num / 3600).toFixed(1) + 'h' : num >= 60 ? Math.round(num / 60) + 'm' : num + 's';
      case 'bytes': return num >= 1e9 ? (num / 1e9).toFixed(1) + 'GB' : num >= 1e6 ? (num / 1e6).toFixed(1) + 'MB' : num >= 1e3 ? (num / 1e3).toFixed(1) + 'KB' : num + 'B';
      default: return num >= 1000 ? new Intl.NumberFormat('en-US').format(num) : String(num);
    }
  };

  return (
    <div dir={dir} className={\`rounded-xl border border-black/[0.08] bg-white p-6 transition-shadow hover:shadow-md \${className}\`}>
      <div className="flex items-center justify-between">
        <p className="text-sm font-medium text-black/[0.02]0">{label}</p>
        {icon && <span className="text-black/[0.30]">{icon}</span>}
      </div>
      <p className="mt-2 text-3xl font-bold tracking-tight text-[#0F1629]">
        {formatValue(data)}
      </p>
    </div>
  );
}`,

  'chart': () => `
export function Chart({ data, chart, animate = true, className = '', dir }: ChartProps) {
  const chartType = (chart as Record<string, unknown>)?.type ?? 'area';
  const items = Array.isArray(data) ? data : [];

  return (
    <div dir={dir} className={\`rounded-xl border border-black/[0.08] bg-white p-6 \${className}\`}>
      <div className="h-64 w-full">
        {items.length === 0 ? (
          <div className="flex h-full items-center justify-center text-black/[0.30]">No data</div>
        ) : (
          <div className="relative h-full w-full">
            {/* SVG chart placeholder - wire recharts here */}
            <svg viewBox="0 0 400 200" className="h-full w-full" preserveAspectRatio="none">
              {chartType === 'area' || chartType === 'line' ? (
                <g>
                  <defs>
                    <linearGradient id="areaGrad" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="0%" stopColor="#E8384F" stopOpacity="0.2" />
                      <stop offset="100%" stopColor="#E8384F" stopOpacity="0" />
                    </linearGradient>
                  </defs>
                  {items.length > 1 && (() => {
                    const max = Math.max(...items.map((d: Record<string, unknown>) => Number(Object.values(d)[1]) || 0));
                    const pts = items.map((d: Record<string, unknown>, i: number) => {
                      const val = Number(Object.values(d)[1]) || 0;
                      return \`\${(i / (items.length - 1)) * 400},\${200 - (val / (max || 1)) * 180}\`;
                    });
                    const line = pts.join(' ');
                    const area = \`0,200 \${line} 400,200\`;
                    return (
                      <>
                        {chartType === 'area' && <polygon points={area} fill="url(#areaGrad)" />}
                        <polyline points={line} fill="none" stroke="#E8384F" strokeWidth="2" />
                      </>
                    );
                  })()}
                </g>
              ) : chartType === 'bar' ? (
                <g>
                  {items.map((d: Record<string, unknown>, i: number) => {
                    const max = Math.max(...items.map((x: Record<string, unknown>) => Number(Object.values(x)[1]) || 0));
                    const val = Number(Object.values(d)[1]) || 0;
                    const w = 400 / items.length * 0.6;
                    const h = (val / (max || 1)) * 180;
                    const x = (400 / items.length) * i + w * 0.3;
                    return <rect key={i} x={x} y={200 - h} width={w} height={h} fill="#3B3FBF" rx="4" />;
                  })}
                </g>
              ) : chartType === 'donut' ? (
                <g transform="translate(200,100)">
                  {(() => {
                    const total = items.reduce((s: number, d: Record<string, unknown>) => s + (Number(Object.values(d)[1]) || 0), 0);
                    const colors = ['#E8384F', '#3B3FBF', '#0F1629', '#78716C', '#F59E0B'];
                    let angle = 0;
                    return items.map((d: Record<string, unknown>, i: number) => {
                      const val = Number(Object.values(d)[1]) || 0;
                      const sweep = (val / (total || 1)) * 360;
                      const start = angle * Math.PI / 180;
                      const end = (angle + sweep) * Math.PI / 180;
                      const large = sweep > 180 ? 1 : 0;
                      const path = \`M \${Math.cos(start)*80} \${Math.sin(start)*80} A 80 80 0 \${large} 1 \${Math.cos(end)*80} \${Math.sin(end)*80} L \${Math.cos(end)*50} \${Math.sin(end)*50} A 50 50 0 \${large} 0 \${Math.cos(start)*50} \${Math.sin(start)*50} Z\`;
                      angle += sweep;
                      return <path key={i} d={path} fill={colors[i % colors.length]} />;
                    });
                  })()}
                </g>
              ) : null}
            </svg>
          </div>
        )}
      </div>
    </div>
  );
}`,

  'data-table': () => `
export function DataTable({ data, columns, actions, sortable = true, filterable = false, className = '', dir }: DataTableProps) {
  const items = Array.isArray(data) ? data as Record<string, unknown>[] : [];

  return (
    <div dir={dir} className={\`rounded-xl border border-black/[0.08] bg-white overflow-hidden \${className}\`}>
      <div className="overflow-x-auto">
        <table className="w-full text-sm">
          <thead>
            <tr className="border-b border-black/[0.06] bg-black/[0.02]">
              {columns.map((col) => (
                <th key={col} className="px-6 py-3 text-left font-medium text-black/[0.02]0 uppercase tracking-wider text-xs">
                  {col.replace(/([A-Z])/g, ' $1').trim()}
                </th>
              ))}
              {actions && actions.length > 0 && (
                <th className="px-6 py-3 text-right font-medium text-black/[0.02]0 uppercase tracking-wider text-xs">Actions</th>
              )}
            </tr>
          </thead>
          <tbody className="divide-y divide-black/[0.06]">
            {items.map((row, i) => (
              <tr key={i} className="hover:bg-black/[0.02] transition-colors">
                {columns.map((col) => (
                  <td key={col} className="px-6 py-4 text-black/[0.70] whitespace-nowrap">
                    {String(row[col] ?? '')}
                  </td>
                ))}
                {actions && actions.length > 0 && (
                  <td className="px-6 py-4 text-right space-x-2">
                    {actions.map((action) => (
                      <button key={action} className="text-xs font-medium text-[#3B3FBF] hover:text-[#E8384F] transition-colors">
                        {action}
                      </button>
                    ))}
                  </td>
                )}
              </tr>
            ))}
            {items.length === 0 && (
              <tr>
                <td colSpan={columns.length + (actions?.length ? 1 : 0)} className="px-6 py-12 text-center text-black/[0.30]">
                  No data available
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}`,

  'form': () => `
export function Form({ data, className = '', dir }: FormProps) {
  return (
    <form dir={dir} className={\`rounded-xl border border-black/[0.08] bg-white p-6 space-y-4 \${className}\`}>
      <p className="text-black/[0.02]0 text-sm">Form component</p>
    </form>
  );
}`,

  'chat-messages': () => `
export function ChatMessages({ data, className = '', dir }: ChatMessagesProps) {
  const messages = Array.isArray(data) ? data as Record<string, unknown>[] : [];

  return (
    <div dir={dir} className={\`flex flex-col space-y-3 p-4 overflow-y-auto \${className}\`}>
      {messages.map((msg, i) => (
        <div key={i} className={\`max-w-[80%] rounded-2xl px-4 py-2 text-sm \${
          msg.role === 'user'
            ? 'ml-auto bg-[#3B3FBF] text-white'
            : 'mr-auto bg-black/[0.06] text-black/[0.70]'
        }\`}>
          {String(msg.content ?? '')}
        </div>
      ))}
    </div>
  );
}`,

  'chat-input': () => `
export function ChatInput({ className = '', dir }: ChatInputProps) {
  return (
    <div dir={dir} className={\`flex items-center gap-3 border-t border-black/[0.08] p-4 \${className}\`}>
      <input
        type="text"
        placeholder="Type a message..."
        className="flex-1 rounded-xl border border-black/[0.08] px-4 py-3 text-sm text-black/[0.70] placeholder-black/[0.30] focus:border-[#3B3FBF] focus:outline-none focus:ring-1 focus:ring-[#3B3FBF]"
      />
      <button className="rounded-xl bg-[#E8384F] px-6 py-3 text-sm font-medium text-white hover:bg-[#d42f45] transition-colors">
        Send
      </button>
    </div>
  );
}`,

  'preview': () => `
export function Preview({ data, className = '', dir }: PreviewProps) {
  return (
    <div dir={dir} className={\`rounded-xl border border-black/[0.08] bg-white p-6 \${className}\`}>
      <pre className="text-sm text-black/[0.55] whitespace-pre-wrap font-mono">
        {typeof data === 'string' ? data : JSON.stringify(data, null, 2)}
      </pre>
    </div>
  );
}`,
};

// ── Fallback component for unknown widget types ───────────────────────

const fallbackComponent = (widget: WidgetDef): string => {
  const name = componentName(widget.name);
  const propsKeys = Object.keys(widget.props).filter((k) => k !== 'source');
  const propsStr = propsKeys.length > 0
    ? propsKeys.map((k) => `<span className="text-black/[0.30]">{${JSON.stringify(k)}}: </span><span>{String(${k} ?? '')}</span>`).join('\n          ')
    : '';

  return `
export function ${name}({ data, ${propsKeys.join(', ')}, className = '', dir }: ${name}Props) {
  return (
    <div dir={dir} className={\`rounded-xl border border-black/[0.08] bg-white p-6 \${className}\`}>
      <p className="text-xs font-medium text-black/[0.30] uppercase tracking-wider mb-2">${widget.name}</p>
      ${propsStr ? `<div className="space-y-1 text-sm text-black/[0.55]">\n          ${propsStr}\n        </div>` : '<p className="text-sm text-black/[0.02]0">No data</p>'}
    </div>
  );
}`;
};

// ── Main: generate component file ─────────────────────────────────────

export const generateComponent = (widget: WidgetDef): string => {
  const name = componentName(widget.name);
  const iface = generateInterface(widget);

  const template = COMPONENT_TEMPLATES[widget.name];
  const body = template ? template(widget) : fallbackComponent(widget);

  const lines = [
    HEADER,
    `import React from 'react';`,
    ``,
    iface,
    ``,
    body,
    ``,
  ];

  return lines.join('\n');
};

/**
 * Generate filename for component file
 */
export const componentFileName = (widget: WidgetDef): string =>
  `${componentName(widget.name)}.tsx`;

/**
 * Generate all components for the widget types used in views
 */
export const generateComponents = (
  widgetTypes: string[],
  registry: { get: (name: string) => WidgetDef | undefined },
): Array<{ path: string; content: string }> => {
  const seen = new Set<string>();
  const files: Array<{ path: string; content: string }> = [];

  for (const type of widgetTypes) {
    if (seen.has(type)) continue;
    seen.add(type);

    const def = registry.get(type);
    if (!def) continue;

    files.push({
      path: `components/${componentFileName(def)}`,
      content: generateComponent(def),
    });
  }

  return files;
};
