/**
 * React Query Hooks Generator — EntityDef → typed useQuery / useMutation hooks
 * Ported from flusk-lang-compiler/TanStackStartGenerator.generateEntityHooks()
 */

import type { EntityDef } from '../../parsers/entity.parser.js';

const HEADER = '// @generated by flusk-lang — DO NOT EDIT\n';

const capitalize = (s: string): string =>
  s.charAt(0).toUpperCase() + s.slice(1);

const lowercase = (s: string): string =>
  s.charAt(0).toLowerCase() + s.slice(1);

/**
 * Generate typed React Query hooks for an entity:
 *  - use{Entity}s()         — list query
 *  - use{Entity}(id)        — single-item query
 *  - useCreate{Entity}()    — create mutation
 *  - useUpdate{Entity}()    — partial update mutation
 *  - useDelete{Entity}()    — delete mutation
 */
export const generateEntityHooks = (entity: EntityDef): string => {
  const name = capitalize(entity.name);
  const slug = lowercase(entity.name) + 's';       // e.g. "users"
  const singularSlug = lowercase(entity.name);      // e.g. "user"

  const lines = [
    HEADER,
    `import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'`,
    `import type { ${name} } from '../types/${name}'`,
    ``,
    `// ─── Query keys ──────────────────────────────────────────────────`,
    ``,
    `export const ${singularSlug}Keys = {`,
    `  all: ['${slug}'] as const,`,
    `  detail: (id: string) => ['${slug}', id] as const,`,
    `} as const`,
    ``,
    `// ─── List ────────────────────────────────────────────────────────`,
    ``,
    `export function use${name}s() {`,
    `  return useQuery({`,
    `    queryKey: ${singularSlug}Keys.all,`,
    `    queryFn: (): Promise<${name}[]> =>`,
    `      fetch('/api/${slug}').then((res) => {`,
    `        if (!res.ok) throw new Error(res.statusText)`,
    `        return res.json()`,
    `      }),`,
    `  })`,
    `}`,
    ``,
    `// ─── Single ──────────────────────────────────────────────────────`,
    ``,
    `export function use${name}(id: string) {`,
    `  return useQuery({`,
    `    queryKey: ${singularSlug}Keys.detail(id),`,
    `    queryFn: (): Promise<${name}> =>`,
    `      fetch(\`/api/${slug}/\${id}\`).then((res) => {`,
    `        if (!res.ok) throw new Error(res.statusText)`,
    `        return res.json()`,
    `      }),`,
    `    enabled: Boolean(id),`,
    `  })`,
    `}`,
    ``,
    `// ─── Create ──────────────────────────────────────────────────────`,
    ``,
    `export function useCreate${name}() {`,
    `  const queryClient = useQueryClient()`,
    ``,
    `  return useMutation({`,
    `    mutationFn: (data: Omit<${name}, 'id' | 'createdAt' | 'updatedAt'>): Promise<${name}> =>`,
    `      fetch('/api/${slug}', {`,
    `        method: 'POST',`,
    `        headers: { 'Content-Type': 'application/json' },`,
    `        body: JSON.stringify(data),`,
    `      }).then((res) => {`,
    `        if (!res.ok) throw new Error(res.statusText)`,
    `        return res.json()`,
    `      }),`,
    `    onSuccess: () => {`,
    `      queryClient.invalidateQueries({ queryKey: ${singularSlug}Keys.all })`,
    `    },`,
    `  })`,
    `}`,
    ``,
    `// ─── Update ──────────────────────────────────────────────────────`,
    ``,
    `export function useUpdate${name}() {`,
    `  const queryClient = useQueryClient()`,
    ``,
    `  return useMutation({`,
    `    mutationFn: ({ id, data }: { id: string; data: Partial<${name}> }): Promise<${name}> =>`,
    `      fetch(\`/api/${slug}/\${id}\`, {`,
    `        method: 'PATCH',`,
    `        headers: { 'Content-Type': 'application/json' },`,
    `        body: JSON.stringify(data),`,
    `      }).then((res) => {`,
    `        if (!res.ok) throw new Error(res.statusText)`,
    `        return res.json()`,
    `      }),`,
    `    onSuccess: (_, { id }) => {`,
    `      queryClient.invalidateQueries({ queryKey: ${singularSlug}Keys.all })`,
    `      queryClient.invalidateQueries({ queryKey: ${singularSlug}Keys.detail(id) })`,
    `    },`,
    `  })`,
    `}`,
    ``,
    `// ─── Delete ──────────────────────────────────────────────────────`,
    ``,
    `export function useDelete${name}() {`,
    `  const queryClient = useQueryClient()`,
    ``,
    `  return useMutation({`,
    `    mutationFn: (id: string): Promise<void> =>`,
    `      fetch(\`/api/${slug}/\${id}\`, { method: 'DELETE' }).then((res) => {`,
    `        if (!res.ok) throw new Error(res.statusText)`,
    `      }),`,
    `    onSuccess: (_, id) => {`,
    `      queryClient.invalidateQueries({ queryKey: ${singularSlug}Keys.all })`,
    `      queryClient.removeQueries({ queryKey: ${singularSlug}Keys.detail(id) })`,
    `    },`,
    `  })`,
    `}`,
    ``,
  ];

  return lines.join('\n');
};

/**
 * Generate filename for hooks file
 */
export const hooksFileName = (entity: EntityDef): string => {
  const name = entity.name.charAt(0).toLowerCase() + entity.name.slice(1);
  return `use${entity.name.charAt(0).toUpperCase() + entity.name.slice(1)}.hooks.ts`;
};
