/**
 * Loader Generator — generates server-side data fetching stubs
 */

import type { PageNode } from '../../ast/nodes.js';

const HEADER = '// @generated by flusk-lang — DO NOT EDIT\n';

const kebabCase = (name: string): string =>
  name.replace(/([A-Z])/g, (_, c, i) => (i > 0 ? '-' : '') + c.toLowerCase());

/**
 * Generate a loader stub file for a page with a loader config
 */
export const generateLoader = (page: PageNode): string | null => {
  if (!page.loader) return null;

  const source = page.loader.source;
  const params = page.loader.params;
  const paramsType = params.map((p) => `${p}: string`).join(', ');
  const fnName = `get${source}`;

  const lines = [
    HEADER,
    `// TODO: implement data fetching for ${source}`,
    `// This is a stub — replace with actual DB/API calls`,
    '',
    `export const ${fnName} = async (${paramsType}): Promise<Record<string, unknown>> => {`,
    `  // Fetch ${source} data`,
    `  return {}`,
    `}`,
    '',
  ];

  return lines.join('\n');
};

/**
 * Generate loader filename
 */
export const loaderFileName = (page: PageNode): string =>
  `${kebabCase(page.name)}.loader.ts`;
