/**
 * Page Generator — PageNode AST → .page.tsx (TanStack Router)
 */

import type { PageNode } from '../../ast/nodes.js';
import { ImportTracker } from './imports.js';
import { emitChild } from './jsx.js';

const HEADER = '// @generated by flusk-lang — DO NOT EDIT\n';

// ─── Convert route to TanStack file route ────────────────────────────

const toFileRoute = (route: string): string =>
  route.replace(/:(\w+)/g, '$$$1');

// ─── Convert page name to camelCase for loader fn ────────────────────

const loaderFnName = (name: string): string =>
  'load' + name.charAt(0).toUpperCase() + name.slice(1);

// ─── Generate loader server function ─────────────────────────────────

const emitLoader = (page: PageNode): string => {
  if (!page.loader) return '';

  const fnName = loaderFnName(page.name);
  const params = page.loader.params;
  const paramsType = params.map((p) => `${p}: string`).join('; ');
  const paramsArg = params.map((p) => `params.${p}`).join(', ');

  const lines = [
    '',
    `const ${fnName} = createServerFn(`,
    `  'GET',`,
    `  async (params: { ${paramsType} }) => {`,
    `    const { get${page.loader.source} } = await import(`,
    `      '~/loaders/${page.name.replace(/([A-Z])/g, (_, c, i) => (i > 0 ? '-' : '') + c.toLowerCase())}.loader'`,
    `    )`,
    `    return get${page.loader.source}(${paramsArg})`,
    `  },`,
    `)`,
    '',
  ];
  return lines.join('\n');
};

// ─── Generate route definition ───────────────────────────────────────

const emitRouteDefinition = (page: PageNode): string => {
  const fileRoute = toFileRoute(page.route);
  const lines = [
    `export const Route = createFileRoute('${fileRoute}')({`,
    `  component: ${page.name}Page,`,
  ];

  if (page.loader) {
    const params = page.loader.params;
    const fnName = loaderFnName(page.name);
    const paramObj = params.map((p) => `${p}: params.${p}`).join(', ');
    lines.push(`  loader: ({ params }) => ${fnName}({ ${paramObj} }),`);
  }

  if (page.pageMeta) {
    lines.push(`  head: () => ({`);
    lines.push(`    meta: [`);
    for (const [key, val] of Object.entries(page.pageMeta)) {
      if (key === 'title') lines.push(`      { title: '${val}' },`);
      else lines.push(`      { name: '${key}', content: '${val}' },`);
    }
    lines.push(`    ],`);
    lines.push(`  }),`);
  }

  lines.push(`})`);
  return lines.join('\n');
};

// ─── Main: generate page .tsx ────────────────────────────────────────

export const generatePage = (page: PageNode): string => {
  const imports = new ImportTracker();
  imports.add('@tanstack/react-router', 'createFileRoute');
  if (page.loader) {
    imports.add('@tanstack/start', 'createServerFn');
  }

  // Build JSX body
  const dataVar = 'data';
  const jsxChildren = page.sections
    .map((s) => emitChild(s, imports, dataVar, '      '))
    .join('\n');

  // Assemble file
  const lines = [HEADER];
  lines.push(imports.emit());
  lines.push(emitLoader(page));
  lines.push(emitRouteDefinition(page));
  lines.push('');
  lines.push(`function ${page.name}Page() {`);

  if (page.loader) {
    lines.push(`  const ${dataVar} = Route.useLoaderData()`);
    lines.push('');
  }

  const mainTag = page.accessibility?.landmark ?? 'main';
  const ariaLabel = page.accessibility?.ariaLabel
    ? ` aria-label="${page.accessibility.ariaLabel}"`
    : '';

  lines.push(`  return (`);
  lines.push(`    <${mainTag} className="space-y-6 p-6"${ariaLabel}>`);
  lines.push(jsxChildren);
  lines.push(`    </${mainTag}>`);
  lines.push(`  )`);
  lines.push(`}`);
  lines.push('');

  return lines.join('\n');
};
