/**
 * Routes Generator — generates route registry barrel file
 */

import type { PageNode } from '../../ast/nodes.js';

const HEADER = '// @generated by flusk-lang — DO NOT EDIT\n';

const kebabCase = (name: string): string =>
  name.replace(/([A-Z])/g, (_, c, i) => (i > 0 ? '-' : '') + c.toLowerCase());

export interface RouteEntry {
  name: string;
  route: string;
  page: string;   // File path
  loader?: string; // File path
  auth: boolean;
  ssr: boolean;
}

/**
 * Generate routes.ts barrel that re-exports all page routes
 */
export const generateRoutes = (pages: PageNode[]): string => {
  const lines = [HEADER];

  for (const page of pages) {
    const fileName = kebabCase(page.name);
    lines.push(`export { Route as ${page.name}Route } from './pages/${fileName}.page'`);
  }

  lines.push('');

  // Route manifest for programmatic access
  lines.push('export const routeManifest = [');
  for (const page of pages) {
    lines.push(`  { name: '${page.name}', route: '${page.route}', auth: ${page.auth}, ssr: ${page.ssr} },`);
  }
  lines.push('] as const');
  lines.push('');

  return lines.join('\n');
};

/**
 * Generate barrel index for components
 */
export const generateComponentBarrel = (widgetTypes: string[]): string => {
  const lines = [HEADER];
  const unique = [...new Set(widgetTypes)].sort();

  for (const wt of unique) {
    const name = wt
      .split('-')
      .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
      .join('');
    lines.push(`export { ${name} } from './${name}'`);
  }

  lines.push('');
  return lines.join('\n');
};
