// TODO: Implement barrel generator — auto-generate index.ts files
export const generateBarrel = (_files: string[]): string => {
  return `// @generated by flusk-lang — DO NOT EDIT\n// TODO: barrel generator not yet implemented\n`;
};
