const HEADER = '// @generated by flusk-lang — DO NOT EDIT\n';

export const generateBarrel = (files: string[]): string => {
  const lines = [HEADER];
  for (const file of files.sort()) {
    const mod = file.replace(/\.ts$/, '.js');
    lines.push(`export * from './${mod}';`);
  }
  lines.push('');
  return lines.join('\n');
};
