import type { CommandDef } from '../../parsers/command.parser.js';

// TODO: Implement command generator — translate CommandDef to commander CLI command
export const generateCommand = (_cmd: CommandDef): string => {
  return `// @generated by flusk-lang — DO NOT EDIT\n// TODO: command generator not yet implemented\n`;
};
