import type { EntityDef, EntityField } from '../../parsers/entity.parser.js';

const HEADER = '// @generated by flusk-lang — DO NOT EDIT\n';

const mapType = (field: EntityField): string => {
  const types: Record<string, string> = {
    string: 'Type.String()',
    number: 'Type.Number()',
    boolean: 'Type.Boolean()',
    date: 'Type.String({ format: "date-time" })',
    json: 'Type.Any()',
  };
  if (field.type === 'enum' && field.values) {
    return `Type.Union([${field.values.map((v) => `Type.Literal('${v}')`).join(', ')}])`;
  }
  return types[field.type] ?? 'Type.Any()';
};

const mapTsType = (field: EntityField): string => {
  const types: Record<string, string> = {
    string: 'string', number: 'number', boolean: 'boolean',
    date: 'string', json: 'unknown',
  };
  if (field.type === 'enum' && field.values) return field.values.map((v) => `'${v}'`).join(' | ');
  return types[field.type] ?? 'unknown';
};

export const generateEntitySchema = (entity: EntityDef): string => {
  const lines = [HEADER, `import { Type, Static } from '@sinclair/typebox';\n`];
  lines.push(`export const ${entity.name}Schema = Type.Object({`);
  lines.push(`  id: Type.String(),`);
  for (const f of entity.fields) {
    const typeExpr = f.required === false ? `Type.Optional(${mapType(f)})` : mapType(f);
    lines.push(`  ${f.name}: ${typeExpr},`);
  }
  lines.push(`});\n`);
  lines.push(`export type ${entity.name} = Static<typeof ${entity.name}Schema>;\n`);
  return lines.join('\n');
};

export const generateEntityType = (entity: EntityDef): string => {
  const lines = [HEADER];
  lines.push(`export interface ${entity.name} {`);
  lines.push(`  id: string;`);
  for (const f of entity.fields) {
    const opt = f.required === false ? '?' : '';
    lines.push(`  ${f.name}${opt}: ${mapTsType(f)};`);
  }
  lines.push(`}\n`);
  return lines.join('\n');
};

export const generateEntityRepository = (entity: EntityDef): string => {
  const name = entity.name;
  const lines = [HEADER];
  lines.push(`import type { ${name} } from './${name.toLowerCase()}.types.js';\n`);
  lines.push(`export interface ${name}Repository {`);
  lines.push(`  findById(id: string): Promise<${name} | null>;`);
  lines.push(`  findAll(): Promise<${name}[]>;`);
  lines.push(`  create(data: Omit<${name}, 'id'>): Promise<${name}>;`);
  lines.push(`  update(id: string, data: Partial<${name}>): Promise<${name}>;`);
  lines.push(`  delete(id: string): Promise<void>;`);
  lines.push(`}\n`);
  return lines.join('\n');
};
