/**
 * Entity Test Generator — produces unit tests for SQLite repositories
 */

import type { EntityDef, EntityField } from '../../parsers/entity.parser.js';

const HEADER = '// @generated by flusk-lang — DO NOT EDIT\n';

const toPascal = (s: string): string =>
  s.split(/[-_ ]+/).map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join('');

const toSnake = (s: string): string =>
  s.replace(/([a-z])([A-Z])/g, '$1_$2').toLowerCase().replace(/-/g, '_');

const toTableName = (entity: string): string => toSnake(entity) + 's';

const mockValue = (field: EntityField): string => {
  switch (field.type) {
    case 'string': return `'test-${field.name}'`;
    case 'number': case 'integer': return '42';
    case 'float': return '3.14';
    case 'boolean': return 'true';
    case 'date': case 'datetime': case 'timestamp': return `'2026-01-01T00:00:00.000Z'`;
    case 'json': case 'object': return `{ key: 'value' }`;
    case 'array': return `['item']`;
    case 'enum': return field.values?.[0] ? `'${field.values[0]}'` : `'default'`;
    default: return `'test'`;
  }
};

export const generateEntityTest = (entity: EntityDef): string => {
  const pascal = toPascal(entity.name);
  const table = toTableName(entity.name);
  const lower = entity.name.toLowerCase();
  const autoColumns = new Set(['id', 'createdAt', 'updatedAt', 'created_at', 'updated_at']);
  const requiredFields = entity.fields.filter((f) => f.required !== false && !autoColumns.has(f.name));

  const lines = [HEADER];
  lines.push(`import { describe, it, expect, beforeEach } from 'vitest';`);
  lines.push(`import Database from 'better-sqlite3';`);
  lines.push(`import { ${pascal}Repository } from '../../src/repositories/${lower}.repository.js';`);
  lines.push('');
  lines.push(`describe('${pascal}Repository', () => {`);
  lines.push(`  let db: Database.Database;`);
  lines.push(`  let repo: ${pascal}Repository;`);
  lines.push('');
  lines.push(`  beforeEach(() => {`);
  lines.push(`    db = new Database(':memory:');`);

  // Create table inline for test
  const cols = [
    'id TEXT PRIMARY KEY',
    ...entity.fields
      .filter((f) => !['id', 'createdAt', 'updatedAt', 'created_at', 'updated_at'].includes(f.name))
      .map((f) => {
        const col = toSnake(f.name);
        const sqlType = { string: 'TEXT', number: 'INTEGER', integer: 'INTEGER', float: 'REAL', boolean: 'INTEGER', enum: 'TEXT' }[f.type] ?? 'TEXT';
        return `${col} ${sqlType}${f.required !== false ? ' NOT NULL' : ''}`;
      }),
    "created_at TEXT NOT NULL DEFAULT (datetime('now'))",
    "updated_at TEXT NOT NULL DEFAULT (datetime('now'))",
  ];
  lines.push(`    db.exec(\`CREATE TABLE ${table} (${cols.join(', ')})\`);`);
  lines.push(`    repo = new ${pascal}Repository(db);`);
  lines.push(`  });`);
  lines.push('');

  // Test data helper
  lines.push(`  const testData = () => ({`);
  for (const f of requiredFields) {
    lines.push(`    ${f.name}: ${mockValue(f)},`);
  }
  lines.push(`  });`);
  lines.push('');

  // Create test
  lines.push(`  it('creates a record', () => {`);
  lines.push(`    const result = repo.create(testData());`);
  lines.push(`    expect(result).toBeDefined();`);
  lines.push(`    expect(result.id).toBeDefined();`);
  lines.push(`  });`);
  lines.push('');

  // FindById test
  lines.push(`  it('finds by id', () => {`);
  lines.push(`    const created = repo.create(testData());`);
  lines.push(`    const found = repo.findById(created.id);`);
  lines.push(`    expect(found).toBeDefined();`);
  lines.push(`    expect(found!.id).toBe(created.id);`);
  lines.push(`  });`);
  lines.push('');

  // List test
  lines.push(`  it('lists records', () => {`);
  lines.push(`    repo.create(testData());`);
  lines.push(`    repo.create(testData());`);
  lines.push(`    const list = repo.list();`);
  lines.push(`    expect(list.length).toBe(2);`);
  lines.push(`  });`);
  lines.push('');

  // Update test
  lines.push(`  it('updates a record', () => {`);
  lines.push(`    const created = repo.create(testData());`);
  if (requiredFields[0]) {
    const f = requiredFields[0];
    const updateVal = f.type === 'string' ? `'updated'` : f.type === 'number' ? '99' : `'updated'`;
    lines.push(`    const updated = repo.update(created.id, { ${f.name}: ${updateVal} });`);
    lines.push(`    expect(updated).toBeDefined();`);
  }
  lines.push(`  });`);
  lines.push('');

  // Delete test
  lines.push(`  it('deletes a record', () => {`);
  lines.push(`    const created = repo.create(testData());`);
  lines.push(`    const deleted = repo.delete(created.id);`);
  lines.push(`    expect(deleted).toBe(true);`);
  lines.push(`    expect(repo.findById(created.id)).toBeNull();`);
  lines.push(`  });`);

  lines.push(`});`);
  lines.push('');

  return lines.join('\n');
};
