import type { EventDef } from '../../parsers/event.parser.js';

const HEADER = '// @generated by flusk-lang — DO NOT EDIT\n';

const camelCase = (s: string): string =>
  s.charAt(0).toLowerCase() + s.slice(1);

const genPayloadType = (def: EventDef): string[] => {
  if (!def.payload?.fields?.length) return [];
  const lines = [`export interface ${def.name}Payload {`];
  for (const f of def.payload.fields) {
    const opt = f.required === false ? '?' : '';
    const tsType = f.type === 'number' ? 'number' : f.type === 'boolean' ? 'boolean' : 'string';
    lines.push(`  ${f.name}${opt}: ${tsType};`);
  }
  lines.push('}\n');
  return lines;
};

const genPublisher = (def: EventDef): string[] => {
  const lines: string[] = [];
  const payloadParam = def.payload?.fields?.length ? `payload: ${def.name}Payload` : '';
  lines.push(`export const publish${def.name} = async (${payloadParam}): Promise<void> => {`);
  if (def.channel === 'kafka') {
    const topic = def.topic ?? camelCase(def.name);
    lines.push(`  await producer.send({ topic: '${topic}', messages: [{ value: JSON.stringify(payload) }] });`);
  } else if (def.channel === 'redis') {
    const topic = def.topic ?? camelCase(def.name);
    lines.push(`  await redis.publish('${topic}', JSON.stringify(payload));`);
  } else if (def.channel === 'webhook') {
    const url = def.url ?? 'process.env.WEBHOOK_URL';
    lines.push(`  await fetch(${def.url ? `'${url}'` : url}, {`);
    lines.push(`    method: 'POST', headers: { 'Content-Type': 'application/json' },`);
    lines.push(`    body: JSON.stringify(payload),`);
    lines.push(`  });`);
  } else {
    lines.push(`  // ${def.channel} publish — emit event`);
    lines.push(`  console.log('${def.name}', payload);`);
  }
  lines.push(`};\n`);
  return lines;
};

const genSubscriber = (def: EventDef): string[] => {
  if (!def.subscribe) return [];
  const lines: string[] = [];
  const retry = def.subscribe.retry?.maxAttempts ?? 1;
  lines.push(`export const subscribe${def.name} = async (): Promise<void> => {`);
  lines.push(`  const maxAttempts = ${retry};`);
  lines.push(`  // Subscribe to ${def.channel} channel and call ${def.subscribe.handler}`);
  lines.push(`  console.log('Subscribed to ${def.name}', { maxAttempts });`);
  lines.push(`};\n`);
  return lines;
};

export const generateEvent = (def: EventDef): string => {
  const lines = [HEADER];
  lines.push(...genPayloadType(def));
  lines.push(...genPublisher(def));
  lines.push(...genSubscriber(def));
  return lines.join('\n');
};
