import type { FunctionDef, FunctionStep } from '../../parsers/function.parser.js';

const HEADER = '// @generated by flusk-lang — DO NOT EDIT\n';

const toPascal = (s: string): string =>
  s.split(/[-_ ]+/).map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join('');

const toCamel = (s: string): string => {
  const p = toPascal(s);
  return p.charAt(0).toLowerCase() + p.slice(1);
};

/**
 * Infer CRUD pattern from function name.
 * Returns { op, entityName, entityPascal } or null if not a CRUD function.
 */
const inferCrud = (fnName: string): { op: string; entityKebab: string; entityPascal: string } | null => {
  // Standard patterns: createLlmCall, findLlmCallById, listLlmCalls, updateLlmCall, deleteLlmCall
  const patterns: Array<{ re: RegExp; op: string }> = [
    { re: /^create([A-Z].+)$/, op: 'create' },
    { re: /^find([A-Z].+)ById$/, op: 'findById' },
    { re: /^list([A-Z].+?)s?$/, op: 'list' },
    { re: /^update([A-Z].+)$/, op: 'update' },
    { re: /^delete([A-Z].+)$/, op: 'delete' },
  ];
  for (const { re, op } of patterns) {
    const m = fnName.match(re);
    if (m) {
      const entityPascal = m[1]!;
      const entityKebab = entityPascal.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
      return { op, entityKebab, entityPascal };
    }
  }

  // Reversed patterns: dashboardList, dashboardCreate, delusionList, driftList, alertsList
  const reversedPatterns: Array<{ re: RegExp; op: string }> = [
    { re: /^([a-z][a-zA-Z]*)List$/, op: 'list' },
    { re: /^([a-z][a-zA-Z]*)Create$/, op: 'create' },
    { re: /^([a-z][a-zA-Z]*)Scan$/, op: 'list' },
  ];
  for (const { re, op } of reversedPatterns) {
    const m = fnName.match(re);
    if (m) {
      const raw = m[1]!;
      const entityPascal = raw.charAt(0).toUpperCase() + raw.slice(1);
      const entityKebab = entityPascal.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
      return { op, entityKebab, entityPascal };
    }
  }

  return null;
};

/**
 * Check if steps are just a stub: single return with value 'null' or no real logic
 */
const isStub = (steps: FunctionStep[]): boolean => {
  if (steps.length === 0) return true;
  if (steps.length === 1) {
    const s = steps[0]!;
    if (s.action === 'return' && (s.with === undefined || Object.keys(s.with).length === 0)) {
      return true;
    }
  }
  return false;
};

/**
 * Resolve a value from YAML into a JS expression.
 */
const resolveValue = (val: unknown): string => {
  if (typeof val === 'string') {
    if (val.startsWith('$')) return val.slice(1);
    return `'${val}'`;
  }
  if (typeof val === 'number' || typeof val === 'boolean') return String(val);
  if (val === null || val === undefined) return 'undefined';
  if (Array.isArray(val)) {
    return `[${val.map(resolveValue).join(', ')}]`;
  }
  if (typeof val === 'object') {
    const entries = Object.entries(val as Record<string, unknown>)
      .map(([k, v]) => `${k}: ${resolveValue(v)}`);
    return `{ ${entries.join(', ')} }`;
  }
  return String(val);
};

/**
 * Access raw YAML properties on step (parser passes through all fields).
 */
const raw = (step: FunctionStep): Record<string, unknown> => step as unknown as Record<string, unknown>;

const generateStepCode = (step: FunctionStep, indent: string): string => {
  const lines: string[] = [];
  const r = raw(step);

  // action: call with entity → repository query
  if (step.action === 'call' && r.entity) {
    const entity = String(r.entity);
    const entityLower = entity.charAt(0).toLowerCase() + entity.slice(1);
    const entityKebab = entity.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
    const repoClass = `${entity}Repository`;
    const filters = r.filters ? resolveValue(r.filters) : 'undefined';
    lines.push(`${indent}const ${entityLower}Repo = new ${repoClass}(db);`);
    lines.push(`${indent}const ${step.id} = ${entityLower}Repo.list(${filters});`);
    return lines.join('\n');
  }

  if (step.call && (!step.action || step.action === 'call')) {
    const args = step.with
      ? Object.entries(step.with).map(([, v]) => resolveValue(v)).join(', ')
      : '';
    lines.push(`${indent}const ${step.id} = ${step.call}(${args});`);
  } else if (step.action === 'filter') {
    const src = step.source?.startsWith('$') ? step.source.slice(1) : step.source;
    const condition = r.condition ? String(r.condition) : undefined;
    if (step.where) {
      const val = String(step.where.value);
      const valExpr = val.startsWith('$') ? val.slice(1) : `'${val}'`;
      const opMap: Record<string, string> = {
        eq: '===', neq: '!==', gt: '>', gte: '>=', lt: '<', lte: '<=',
      };
      const op = opMap[step.where.op] ?? '===';
      lines.push(`${indent}const ${step.id} = ${src}.filter((item: Record<string, unknown>) => item.${step.where!.field} ${op} ${valExpr});`);
    } else if (condition) {
      // Inline condition like "$item.count >= $minOccurrences"
      const condExpr = condition.replace(/\$item\.(\w+)/g, 'item.$1').replace(/\$(\w+)/g, '$1');
      lines.push(`${indent}const ${step.id} = (${src} as unknown[]).filter((item: Record<string, unknown>) => ${condExpr});`);
    } else {
      lines.push(`${indent}const ${step.id} = ${src}; // filter: no condition`);
    }
  } else if (step.action === 'forEach') {
    const src = step.source?.startsWith('$') ? step.source.slice(1) : step.source;
    const args = step.with
      ? Object.entries(step.with).map(([, v]) => {
          if (v === '$item') return 'item';
          return resolveValue(v);
        }).join(', ')
      : 'item';
    lines.push(`${indent}for (const item of ${src} as unknown[]) {`);
    lines.push(`${indent}  try {`);
    lines.push(`${indent}    ${step.call}(${args});`);
    if (step.onError === 'log-and-continue') {
      lines.push(`${indent}  } catch (err) {`);
      lines.push(`${indent}    console.error(err);`);
    } else {
      lines.push(`${indent}  } catch (err) {`);
      lines.push(`${indent}    throw err;`);
    }
    lines.push(`${indent}  }`);
    lines.push(`${indent}}`);
  } else if (step.action === 'return') {
    // Check for value field (raw YAML passthrough)
    const value = r.value as string | undefined;
    if (step.with) {
      const obj = Object.entries(step.with)
        .map(([k, v]) => `${k}: ${resolveValue(v)}`).join(', ');
      lines.push(`${indent}return { ${obj} };`);
    } else if (value !== undefined) {
      lines.push(`${indent}return ${resolveValue(value)};`);
    } else {
      const val = step.source?.startsWith('$') ? step.source.slice(1) : step.source;
      lines.push(`${indent}return ${val ?? 'undefined'};`);
    }
  } else if (step.action === 'transform') {
    const value = r.value as unknown;
    const src = value ? resolveValue(value) : step.with?.source ? resolveValue(step.with.source) : 'undefined';
    lines.push(`${indent}const ${step.id} = ${src};`);
  } else if (step.action === 'condition') {
    // Handle both with.if and top-level if
    const ifField = r.if as Record<string, unknown> | undefined;
    const cond = step.with?.if ? resolveValue(step.with.if)
      : ifField ? `${resolveValue(ifField.field)} ${ifField.op === 'eq' ? '===' : '!=='} ${resolveValue(ifField.value)}`
      : 'false';
    lines.push(`${indent}let ${step.id}: unknown = undefined;`);
    lines.push(`${indent}if (${cond}) {`);

    const thenSteps = (r.then ?? step.with?.then) as unknown;
    if (Array.isArray(thenSteps)) {
      for (const ts of thenSteps) {
        const thenBlock = ts as Record<string, unknown>;
        if (thenBlock.call) {
          const args = thenBlock.with
            ? Object.entries(thenBlock.with as Record<string, unknown>)
                .map(([, v]) => resolveValue(v)).join(', ')
            : '';
          lines.push(`${indent}  ${step.id} = ${thenBlock.call}(${args});`);
        }
      }
    } else if (thenSteps && typeof thenSteps === 'object') {
      const thenBlock = thenSteps as Record<string, unknown>;
      if (thenBlock.call) {
        const args = thenBlock.with
          ? Object.entries(thenBlock.with as Record<string, unknown>)
              .map(([, v]) => resolveValue(v)).join(', ')
          : '';
        lines.push(`${indent}  ${step.id} = ${thenBlock.call}(${args});`);
      }
    }

    const elseSteps = r.else as unknown;
    if (elseSteps) {
      lines.push(`${indent}} else {`);
      if (Array.isArray(elseSteps)) {
        for (const es of elseSteps) {
          const elseBlock = es as Record<string, unknown>;
          if (elseBlock.call) {
            const args = elseBlock.with
              ? Object.entries(elseBlock.with as Record<string, unknown>)
                  .map(([, v]) => resolveValue(v)).join(', ')
              : '';
            lines.push(`${indent}  ${step.id} = ${elseBlock.call}(${args});`);
          }
        }
      }
    }

    lines.push(`${indent}}`);
  } else if (step.action === 'assign') {
    if (step.with) {
      for (const [k, v] of Object.entries(step.with)) {
        lines.push(`${indent}const ${k} = ${resolveValue(v)};`);
      }
    }
  } else {
    lines.push(`${indent}// TODO: implement action "${step.action}" for step "${step.id}"`);
  }

  return lines.join('\n');
};

/**
 * Generate a CRUD function that delegates to a repository.
 */
const generateCrudFunction = (
  fn: FunctionDef,
  crud: { op: string; entityKebab: string; entityPascal: string },
): string => {
  const lines = [HEADER];
  const repoClass = `${crud.entityPascal}Repository`;
  const repoFile = crud.entityPascal.toLowerCase();
  lines.push(`import type Database from 'better-sqlite3';`);
  lines.push(`import { ${repoClass} } from '../repositories/${repoFile}.repository.js';\n`);

  switch (crud.op) {
    case 'create':
      lines.push(`export const ${fn.name} = (db: Database.Database, data: Record<string, unknown>): unknown => {`);
      lines.push(`  const repo = new ${repoClass}(db);`);
      lines.push(`  return repo.create(data as Parameters<typeof repo.create>[0]);`);
      lines.push(`};\n`);
      break;
    case 'findById':
      lines.push(`export const ${fn.name} = (db: Database.Database, id: string): unknown => {`);
      lines.push(`  const repo = new ${repoClass}(db);`);
      lines.push(`  return repo.findById(id);`);
      lines.push(`};\n`);
      break;
    case 'list':
      lines.push(`export const ${fn.name} = (db: Database.Database, filters?: Partial<Record<string, unknown>>): unknown => {`);
      lines.push(`  const repo = new ${repoClass}(db);`);
      lines.push(`  return repo.list(filters);`);
      lines.push(`};\n`);
      break;
    case 'update':
      lines.push(`export const ${fn.name} = (db: Database.Database, id: string, data: Record<string, unknown>): unknown => {`);
      lines.push(`  const repo = new ${repoClass}(db);`);
      lines.push(`  return repo.update(id, data);`);
      lines.push(`};\n`);
      break;
    case 'delete':
      lines.push(`export const ${fn.name} = (db: Database.Database, id: string): unknown => {`);
      lines.push(`  const repo = new ${repoClass}(db);`);
      lines.push(`  return repo.delete(id);`);
      lines.push(`};\n`);
      break;
  }

  return lines.join('\n');
};

/**
 * Generate a non-CRUD function with step-based logic.
 */
const generateStepFunction = (fn: FunctionDef): string => {
  const lines = [HEADER];
  const hasDbInput = fn.inputs?.some((i) => i.name === 'db');

  // Collect function calls and entity calls from steps
  const calledFunctions = new Set<string>();
  const calledEntities = new Set<string>();
  for (const step of fn.steps) {
    const r = step as unknown as Record<string, unknown>;
    if (step.call && /^[a-z]/.test(step.call)) {
      calledFunctions.add(step.call);
    }
    if (step.action === 'forEach' && step.call && /^[a-z]/.test(step.call)) {
      calledFunctions.add(step.call);
    }
    if (step.action === 'call' && r.entity) {
      calledEntities.add(String(r.entity));
    }
    // Check then/else blocks for calls
    const thenSteps = r.then as unknown;
    if (Array.isArray(thenSteps)) {
      for (const ts of thenSteps) {
        const t = ts as Record<string, unknown>;
        if (t.call && /^[a-z]/.test(String(t.call))) calledFunctions.add(String(t.call));
      }
    }
    const elseSteps = r.else as unknown;
    if (Array.isArray(elseSteps)) {
      for (const es of elseSteps) {
        const e = es as Record<string, unknown>;
        if (e.call && /^[a-z]/.test(String(e.call))) calledFunctions.add(String(e.call));
      }
    }
  }

  if (hasDbInput || calledEntities.size > 0) {
    lines.push(`import type Database from 'better-sqlite3';`);
  }
  for (const entity of calledEntities) {
    lines.push(`import { ${entity}Repository } from '../repositories/${entity.toLowerCase()}.repository.js';`);
  }
  for (const fnCall of calledFunctions) {
    lines.push(`import { ${fnCall} } from './${fnCall}.function.js';`);
  }
  if (hasDbInput || calledFunctions.size > 0 || calledEntities.size > 0) lines.push('');

  const params = (fn.inputs ?? []).map((i) => {
    const tsType = i.type === 'Database' ? 'Database.Database' : mapInputType(i.type);
    return `${i.name}: ${tsType}`;
  }).join(', ');
  const returnType = fn.output?.type ?? 'unknown';

  lines.push(`export const ${fn.name} = (${params}): ${mapReturnType(returnType)} => {`);

  for (const step of fn.steps) {
    lines.push(generateStepCode(step, '  '));
  }

  // If no explicit return step, return the last step's variable (or 'result' if exists)
  const hasReturn = fn.steps.some((s) => s.action === 'return');
  if (!hasReturn && fn.steps.length > 0) {
    const lastStep = fn.steps[fn.steps.length - 1]!;
    const resultStep = fn.steps.find((s) => s.id === 'result');
    const returnVar = resultStep ? 'result' : lastStep.id;
    lines.push(`  return ${returnVar} as unknown;`);
  }

  lines.push(`};\n`);
  const code = lines.join('\n');
  return prefixUnusedVars(code);
};

/**
 * Prefix unused const/let variables with _ to avoid lint errors.
 */
const prefixUnusedVars = (code: string): string => {
  const bodyMatch = code.match(/=> \{([\s\S]*)\};/);
  if (!bodyMatch) return code;
  const body = bodyMatch[1]!;

  // Collect all declared variables
  const decls = [...body.matchAll(/(?:const|let) (\w+)\s*[:=]/g)].map((m) => m[1]!);

  let result = code;
  for (const varName of decls) {
    if (varName.startsWith('_')) continue;
    // Count usages in the body (excluding the declaration line itself)
    const usagePattern = new RegExp(`\\b${varName}\\b`, 'g');
    const usages = [...body.matchAll(usagePattern)];
    // One usage is the declaration itself; if only 1, it's unused
    if (usages.length <= 1) {
      result = result.replace(
        new RegExp(`((?:const|let) )${varName}(\\s*[:=])`),
        `$1_${varName}$2`,
      );
    }
  }
  return result;
};

const mapInputType = (type: string): string => {
  const map: Record<string, string> = {
    string: 'string', number: 'number', boolean: 'boolean',
    json: 'Record<string, unknown>', 'json[]': 'Record<string, unknown>[]',
  };
  if (type.startsWith('enum')) return 'string';
  return map[type] ?? 'unknown';
};

const mapReturnType = (type: string): string => {
  if (type === 'void') return 'void';
  if (type === 'json') return 'unknown';
  if (type.endsWith('[]')) return 'unknown[]';
  return 'unknown';
};

export const generateFunction = (fn: FunctionDef): string => {
  // Check if this is a CRUD stub that should be wired to a repository
  const crud = inferCrud(fn.name);
  if (crud && isStub(fn.steps)) {
    return generateCrudFunction(fn, crud);
  }

  // Non-CRUD or has real step logic
  return generateStepFunction(fn);
};
