import type { MiddlewareDef } from '../../parsers/middleware.parser.js';

const HEADER = '// @generated by flusk-lang — DO NOT EDIT\n';

const camelCase = (s: string): string => s.replace(/-([a-z])/g, (_, c) => c.toUpperCase());

const resolveFrom = (from: string): string => {
  const parts = from.split('.');
  return parts.join('?.');
};

const generateStep = (step: { id: string; action: string; value?: unknown }): string[] => {
  const lines: string[] = [];
  if (step.action === 'assign') {
    if (typeof step.value === 'object' && step.value !== null) {
      lines.push(`  const ${step.id} = ${JSON.stringify(step.value)};`);
    } else {
      lines.push(`  const ${step.id} = ${String(step.value)};`);
    }
  } else if (step.action === 'return') {
    lines.push(`  return ${String(step.value)};`);
  } else {
    lines.push(`  // TODO: implement action "${step.action}" for step "${step.id}"`);
  }
  return lines;
};

export const generateMiddleware = (def: MiddlewareDef): string => {
  const lines = [HEADER, `import type { FastifyRequest, FastifyReply } from 'fastify';\n`];
  const fnName = camelCase(def.name);
  const hookMap = { request: 'onRequest', response: 'onResponse', error: 'onError' };
  const hookName = hookMap[def.phase] ?? 'onRequest';
  lines.push(`/** Fastify ${hookName} hook — ${def.description ?? def.name} */`);
  lines.push(`export const ${fnName} = async (request: FastifyRequest, reply: FastifyReply): Promise<void> => {`);

  if (def.lookup) {
    lines.push(`  const lookup = ${JSON.stringify(def.lookup)};`);
  }

  for (const input of def.inputs ?? []) {
    lines.push(`  const ${input.name} = ${resolveFrom(input.from)};`);
  }

  for (const step of def.steps ?? []) {
    lines.push(...generateStep(step));
  }

  if (def.output) {
    const keys = Object.keys(def.output);
    lines.push(`  (request as Record<string, unknown>).middlewareOutput = { ${keys.join(', ')} };`);
  }

  lines.push(`};\n`);
  return lines.join('\n');
};
