import type { PluginDef, HookAction } from '../../parsers/plugin.parser.js';

const HEADER = '// @generated by flusk-lang — DO NOT EDIT\n';

const camelCase = (s: string): string => s.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
const pascalCase = (s: string): string => {
  const c = camelCase(s);
  return c.charAt(0).toUpperCase() + c.slice(1);
};

const generateHookBody = (actions: HookAction[]): string[] => {
  const lines: string[] = [];
  for (const action of actions) {
    if (action.action === 'startSpan') {
      lines.push(`      const span = tracer.startSpan('${action.name ?? 'unknown'}', {`);
      lines.push(`        attributes: ${JSON.stringify(action.attributes ?? {})},`);
      lines.push(`      });`);
      lines.push(`      (request as any).__span = span;`);
    } else if (action.action === 'endSpan') {
      lines.push(`      const span = (request as any).__span;`);
      if (action.attributes) {
        for (const [k, v] of Object.entries(action.attributes)) {
          lines.push(`      span?.setAttribute('${k}', ${v});`);
        }
      }
      lines.push(`      span?.end();`);
    } else {
      lines.push(`      // TODO: implement action "${action.action}"`);
    }
  }
  return lines;
};

export const generatePlugin = (def: PluginDef): string => {
  const lines = [HEADER];
  lines.push(`import fp from 'fastify-plugin';`);
  lines.push(`import type { FastifyInstance } from 'fastify';\n`);
  const fnName = camelCase(def.name);
  const typeName = `${pascalCase(def.name)}Options`;
  if (def.options && Object.keys(def.options).length) {
    lines.push(`export interface ${typeName} {`);
    for (const [k, v] of Object.entries(def.options)) {
      lines.push(`  ${k}: ${typeof v === 'string' ? 'string' : 'unknown'};`);
    }
    lines.push(`}\n`);
  }
  lines.push(`export const ${fnName} = fp(async (app: FastifyInstance) => {`);
  if (def.hooks) {
    for (const [hookName, actions] of Object.entries(def.hooks)) {
      lines.push(`  app.addHook('${hookName}', async (request, reply) => {`);
      lines.push(...generateHookBody(actions));
      lines.push(`  });`);
    }
  }
  for (const dec of def.decorators ?? []) {
    const val = dec.type === 'function' ? '() => {}' : dec.type === 'object' ? '{}' : "''";
    lines.push(`  app.decorate('${dec.name}', ${val});`);
  }
  lines.push(`}, { name: '${def.name}' });\n`);
  return lines.join('\n');
};
