import type { ProviderDef } from '../../parsers/provider.parser.js';

const HEADER = '// @generated by flusk-lang — DO NOT EDIT\n';

const pascalCase = (s: string): string =>
  s.replace(/(^|[-_])([a-z])/g, (_, _p, c: string) => c.toUpperCase());

export const generateProvider = (provider: ProviderDef): string => {
  const className = `${pascalCase(provider.name)}Provider`;
  const lines = [HEADER];

  if (provider.config?.fields?.length) {
    lines.push(`export interface ${className}Config {`);
    for (const f of provider.config.fields) {
      const opt = f.required ? '' : '?';
      const type = f.type === 'number' ? 'number' : f.type === 'boolean' ? 'boolean' : 'string';
      lines.push(`  ${f.name}${opt}: ${type};`);
    }
    lines.push('}\n');
  }

  lines.push(`export class ${className} {`);
  lines.push(`  constructor(private readonly config: ${provider.config?.fields?.length ? `${className}Config` : 'Record<string, string>'}) {}\n`);

  for (const method of provider.methods) {
    lines.push(`  async ${method.name}(input: Record<string, unknown>): Promise<void> {`);

    if (provider.type === 'webhook' || provider.type === 'rest') {
      if (method.template) {
        lines.push(`    let body = ${JSON.stringify(method.template)};`);
        lines.push(`    for (const [key, val] of Object.entries(input)) {`);
        lines.push(`      body = body.replaceAll(\`{{\${key}}}\`, String(val));`);
        lines.push(`    }`);
        if (provider.type === 'webhook') {
          lines.push(`    await fetch(this.config.webhookUrl ?? '', {`);
        } else {
          lines.push(`    await fetch(this.config.baseUrl ?? '', {`);
        }
        lines.push(`      method: 'POST',`);
        lines.push(`      headers: { 'Content-Type': 'application/json' },`);
        lines.push(`      body,`);
        lines.push(`    });`);
      } else {
        lines.push(`    // No template — pass input as JSON`);
        lines.push(`    await fetch(this.config.webhookUrl ?? this.config.baseUrl ?? '', {`);
        lines.push(`      method: 'POST',`);
        lines.push(`      headers: { 'Content-Type': 'application/json' },`);
        lines.push(`      body: JSON.stringify(input),`);
        lines.push(`    });`);
      }
    } else {
      lines.push(`    // ${provider.type} provider — implement transport`);
      lines.push(`    console.log('${method.name}', input);`);
    }

    lines.push(`  }\n`);
  }

  lines.push('}\n');
  return lines.join('\n');
};
