import type { ProviderDef } from '../../parsers/provider.parser.js';

// TODO: Implement provider generator — translate ProviderDef to HTTP client + interface
export const generateProvider = (_provider: ProviderDef): string => {
  return `// @generated by flusk-lang — DO NOT EDIT\n// TODO: provider generator not yet implemented\n`;
};
