/**
 * Repository Implementation Generator — produces SQLite CRUD repositories
 * using better-sqlite3 (synchronous)
 */

import type { EntityDef, EntityField } from '../../parsers/entity.parser.js';

const HEADER = '// @generated by flusk-lang — DO NOT EDIT\n';

const toSnake = (s: string): string =>
  s.replace(/([a-z])([A-Z])/g, '$1_$2').toLowerCase().replace(/-/g, '_');

const toTableName = (entity: string): string => toSnake(entity) + 's';

const toPascal = (s: string): string =>
  s.split(/[-_ ]+/).map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join('');

const mapTsType = (field: EntityField): string => {
  const types: Record<string, string> = {
    string: 'string', number: 'number', boolean: 'boolean',
    float: 'number', date: 'string', datetime: 'string',
    timestamp: 'string', json: 'Record<string, unknown>',
    object: 'Record<string, unknown>', array: 'unknown[]',
  };
  if (field.type === 'enum' && field.values) return field.values.map((v) => `'${v}'`).join(' | ');
  return types[field.type] ?? 'unknown';
};

const isJsonType = (type: string): boolean =>
  ['json', 'object', 'array'].includes(type);

export const generateRepositoryImpl = (entity: EntityDef): string => {
  const name = toPascal(entity.name);
  const table = toTableName(entity.name);
  const autoColumns = new Set(['id', 'createdAt', 'updatedAt', 'created_at', 'updated_at']);
  const fields = entity.fields.filter((f) => !autoColumns.has(f.name));
  const allCols = ['id', ...fields.map((f) => toSnake(f.name)), 'created_at', 'updated_at'];
  const insertCols = fields.map((f) => toSnake(f.name));
  const jsonFields = fields.filter((f) => isJsonType(f.type));

  const lines = [HEADER];
  lines.push(`import type Database from 'better-sqlite3';`);
  lines.push(`import { nanoid } from 'nanoid';`);
  lines.push(`import { createChildLogger } from '../lib/logger.js';`);
  lines.push('');
  lines.push(`const log = createChildLogger('${table}-repo');`);
  lines.push('');

  // Type
  lines.push(`export interface ${name}Row {`);
  lines.push(`  id: string;`);
  for (const f of fields) {
    const opt = f.required === false ? '?' : '';
    lines.push(`  ${f.name}${opt}: ${mapTsType(f)};`);
  }
  lines.push(`  createdAt: string;`);
  lines.push(`  updatedAt: string;`);
  lines.push(`}`);
  lines.push('');

  // Create input
  lines.push(`export type ${name}Create = Omit<${name}Row, 'id' | 'createdAt' | 'updatedAt'>;`);
  lines.push(`export type ${name}Update = Partial<${name}Create>;`);
  lines.push('');

  // Row mapper (snake_case DB → camelCase TS)
  lines.push(`const toRow = (raw: Record<string, unknown>): ${name}Row => ({`);
  lines.push(`  id: raw.id as string,`);
  for (const f of fields) {
    const col = toSnake(f.name);
    if (isJsonType(f.type)) {
      lines.push(`  ${f.name}: JSON.parse(raw.${col} as string ?? '{}') as ${mapTsType(f)},`);
    } else if (f.type === 'boolean') {
      lines.push(`  ${f.name}: Boolean(raw.${col}),`);
    } else {
      lines.push(`  ${f.name}: raw.${col} as ${mapTsType(f)},`);
    }
  }
  lines.push(`  createdAt: raw.created_at as string,`);
  lines.push(`  updatedAt: raw.updated_at as string,`);
  lines.push(`});`);
  lines.push('');

  // Repository class
  lines.push(`export class ${name}Repository {`);
  lines.push(`  constructor(private readonly db: Database.Database) {}`);
  lines.push('');

  // create
  lines.push(`  create(data: ${name}Create): ${name}Row {`);
  lines.push(`    const id = nanoid();`);
  lines.push(`    const now = new Date().toISOString();`);
  const placeholders = insertCols.map(() => '?').join(', ');
  lines.push(`    this.db.prepare(`);
  lines.push(`      'INSERT INTO ${table} (id, ${insertCols.join(', ')}, created_at, updated_at) VALUES (?, ${placeholders}, ?, ?)'`);
  lines.push(`    ).run(`);
  lines.push(`      id,`);
  for (const f of fields) {
    if (isJsonType(f.type)) {
      lines.push(`      JSON.stringify(data.${f.name} ?? {}),`);
    } else if (f.type === 'boolean') {
      lines.push(`      data.${f.name} ? 1 : 0,`);
    } else {
      lines.push(`      data.${f.name},`);
    }
  }
  lines.push(`      now, now,`);
  lines.push(`    );`);
  lines.push(`    log.debug({ id }, '${name} created');`);
  lines.push(`    return this.findById(id)!;`);
  lines.push(`  }`);
  lines.push('');

  // findById
  lines.push(`  findById(id: string): ${name}Row | null {`);
  lines.push(`    const raw = this.db.prepare('SELECT ${allCols.join(', ')} FROM ${table} WHERE id = ?').get(id) as Record<string, unknown> | undefined;`);
  lines.push(`    return raw ? toRow(raw) : null;`);
  lines.push(`  }`);
  lines.push('');

  // list
  lines.push(`  list(filters?: Partial<Record<string, unknown>>): ${name}Row[] {`);
  lines.push(`    let sql = 'SELECT ${allCols.join(', ')} FROM ${table}';`);
  lines.push(`    const params: unknown[] = [];`);
  lines.push(`    if (filters && Object.keys(filters).length > 0) {`);
  lines.push(`      const clauses = Object.entries(filters).map(([k, v]) => {`);
  lines.push(`        params.push(v);`);
  lines.push(`        return k + ' = ?';`);
  lines.push(`      });`);
  lines.push(`      sql += ' WHERE ' + clauses.join(' AND ');`);
  lines.push(`    }`);
  lines.push(`    sql += ' ORDER BY created_at DESC';`);
  lines.push(`    const rows = this.db.prepare(sql).all(...params) as Record<string, unknown>[];`);
  lines.push(`    return rows.map(toRow);`);
  lines.push(`  }`);
  lines.push('');

  // JSON field names for proper serialization in update
  if (jsonFields.length > 0) {
    lines.push(`  private static readonly JSON_FIELDS = new Set([${jsonFields.map((f) => `'${f.name}'`).join(', ')}]);`);
    lines.push('');
  }

  // update
  lines.push(`  update(id: string, data: ${name}Update): ${name}Row | null {`);
  lines.push(`    const sets: string[] = [];`);
  lines.push(`    const params: unknown[] = [];`);
  lines.push(`    for (const [key, value] of Object.entries(data)) {`);
  lines.push(`      sets.push(key.replace(/([a-z])([A-Z])/g, '$1_$2').toLowerCase() + ' = ?');`);
  if (jsonFields.length > 0) {
    lines.push(`      params.push(${name}Repository.JSON_FIELDS.has(key) || typeof value === 'object' ? JSON.stringify(value) : value);`);
  } else {
    lines.push(`      params.push(typeof value === 'object' ? JSON.stringify(value) : value);`);
  }
  lines.push(`    }`);
  lines.push(`    if (sets.length === 0) return this.findById(id);`);
  lines.push(`    sets.push('updated_at = ?');`);
  lines.push(`    params.push(new Date().toISOString(), id);`);
  lines.push(`    this.db.prepare('UPDATE ${table} SET ' + sets.join(', ') + ' WHERE id = ?').run(...params);`);
  lines.push(`    return this.findById(id);`);
  lines.push(`  }`);
  lines.push('');

  // delete
  lines.push(`  delete(id: string): boolean {`);
  lines.push(`    const result = this.db.prepare('DELETE FROM ${table} WHERE id = ?').run(id);`);
  lines.push(`    return result.changes > 0;`);
  lines.push(`  }`);
  lines.push(`}`);
  lines.push('');

  return lines.join('\n');
};
