import type { RouteDef } from '../../parsers/route.parser.js';

const HEADER = '// @generated by flusk-lang — DO NOT EDIT\n';

const methodToFastify = (method: string): string => method.toLowerCase();

const toCamel = (s: string): string =>
  s.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());

const toKebab = (s: string): string =>
  s.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();

export const generateRoute = (route: RouteDef): string => {
  const lines = [HEADER];
  lines.push(`import { type FastifyInstance } from 'fastify';`);
  lines.push(`import type Database from 'better-sqlite3';`);

  // Collect unique function calls and generate imports
  const fnNames = new Set<string>();
  for (const op of route.operations) {
    fnNames.add(op.call);
  }
  for (const fnName of fnNames) {
    const kebab = toKebab(fnName);
    lines.push(`import { ${fnName} } from '../functions/${kebab}.function.js';`);
  }

  lines.push('');
  lines.push(`interface AppWithDb extends FastifyInstance { db: Database.Database; }`);
  lines.push('');

  const routeName = toCamel(route.name);
  lines.push(`export const ${routeName}Routes = async (app: FastifyInstance): Promise<void> => {`);
  lines.push(`  const { db } = app as AppWithDb;`);
  lines.push('');

  for (const op of route.operations) {
    const fullPath = `${route.basePath}${op.path === '/' ? '' : op.path}`;
    const method = methodToFastify(op.method);

    lines.push(`  app.${method}('${fullPath}', async (request, reply) => {`);
    lines.push(`    try {`);

    if (op.method === 'POST' || op.method === 'PUT' || op.method === 'PATCH') {
      lines.push(`      const body = request.body as Record<string, unknown>;`);
      lines.push(`      const result = ${op.call}(db, body);`);
    } else if (op.path.includes(':')) {
      lines.push(`      const { id } = request.params as Record<string, string>;`);
      lines.push(`      const result = ${op.call}(db, id);`);
    } else {
      lines.push(`      const result = ${op.call}(db);`);
    }

    if (op.method === 'DELETE') {
      lines.push(`      return reply.status(204).send();`);
    } else if (op.path.includes(':')) {
      lines.push(`      if (result === null || result === undefined) {`);
      lines.push(`        return reply.status(404).send({ error: 'Not found' });`);
      lines.push(`      }`);
      lines.push(`      return reply.send(result);`);
    } else {
      lines.push(`      return reply.send(result);`);
    }

    lines.push(`    } catch (err: unknown) {`);
    lines.push(`      request.log.error(err, '${op.call} failed');`);
    lines.push(`      return reply.status(500).send({ error: 'Internal server error' });`);
    lines.push(`    }`);
    lines.push(`  });\n`);
  }

  lines.push(`};\n`);
  return lines.join('\n');
};
