/**
 * Route Test Generator — produces integration tests using Fastify inject()
 */

import type { RouteDef } from '../../parsers/route.parser.js';

const HEADER = '// @generated by flusk-lang — DO NOT EDIT\n';

const toCamel = (s: string): string =>
  s.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());

export const generateRouteTest = (route: RouteDef): string => {
  const lines = [HEADER];
  lines.push(`import { describe, it, expect, beforeAll, afterAll } from 'vitest';`);
  lines.push(`import Fastify from 'fastify';`);
  lines.push(`import { ${toCamel(route.name)}Routes } from '../../src/routes/${route.name}.routes.js';`);
  lines.push('');
  lines.push(`describe('${route.name} routes', () => {`);
  lines.push(`  const app = Fastify();`);
  lines.push('');
  lines.push(`  beforeAll(async () => {`);
  lines.push(`    await app.register(${toCamel(route.name)}Routes);`);
  lines.push(`    await app.ready();`);
  lines.push(`  });`);
  lines.push('');
  lines.push(`  afterAll(async () => {`);
  lines.push(`    await app.close();`);
  lines.push(`  });`);
  lines.push('');

  for (const op of route.operations) {
    const fullPath = `${route.basePath}${op.path === '/' ? '' : op.path}`;
    const testPath = fullPath.replace(/:(\w+)/g, 'test-id');
    lines.push(`  it('${op.method} ${fullPath}', async () => {`);
    lines.push(`    const res = await app.inject({`);
    lines.push(`      method: '${op.method}',`);
    lines.push(`      url: '${testPath}',`);
    if (op.method === 'POST' || op.method === 'PUT' || op.method === 'PATCH') {
      lines.push(`      payload: {},`);
    }
    lines.push(`    });`);
    lines.push(`    expect(res.statusCode).toBeLessThan(500);`);
    lines.push(`  });`);
    lines.push('');
  }

  lines.push(`});`);
  lines.push('');
  return lines.join('\n');
};
