import type { RouteDef } from '../../parsers/route.parser.js';

const HEADER = '// @generated by flusk-lang — DO NOT EDIT\n';

const methodToFastify = (method: string): string => method.toLowerCase();

export const generateRoute = (route: RouteDef): string => {
  const lines = [HEADER];
  lines.push(`import { type FastifyInstance } from 'fastify';\n`);
  lines.push(`export const ${route.name.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase())}Routes = async (app: FastifyInstance): Promise<void> => {`);

  for (const op of route.operations) {
    const fullPath = `${route.basePath}${op.path === '/' ? '' : op.path}`;
    const method = methodToFastify(op.method);

    lines.push(`  app.${method}('${fullPath}', async (request, reply) => {`);

    if (op.method === 'POST' || op.method === 'PUT' || op.method === 'PATCH') {
      lines.push(`    const result = await ${op.call}(request.body);`);
    } else if (op.path.includes(':')) {
      lines.push(`    const { id } = request.params as Record<string, string>;`);
      lines.push(`    const result = await ${op.call}(id);`);
    } else {
      lines.push(`    const result = await ${op.call}();`);
    }

    if (op.method === 'DELETE') {
      lines.push(`    return reply.status(204).send();`);
    } else {
      lines.push(`    return reply.send(result);`);
    }
    lines.push(`  });\n`);
  }

  lines.push(`};\n`);
  return lines.join('\n');
};
