import type { RouteDef } from '../../parsers/route.parser.js';

// TODO: Implement route generator — translate RouteDef to Fastify route
export const generateRoute = (_route: RouteDef): string => {
  return `// @generated by flusk-lang — DO NOT EDIT\n// TODO: route generator not yet implemented\n`;
};
