import type { StreamDef } from '../../parsers/stream.parser.js';

const HEADER = '// @generated by flusk-lang — DO NOT EDIT\n';

const camelCase = (s: string): string =>
  s.charAt(0).toLowerCase() + s.slice(1);

const genTransform = (def: StreamDef): string[] => {
  if (!def.transform?.fields) return [];
  const lines = [`const transform${def.name} = (data: Record<string, unknown>): Record<string, unknown> => ({`];
  for (const [key, val] of Object.entries(def.transform.fields)) {
    lines.push(`  ${key}: data['${val}'],`);
  }
  lines.push(`});\n`);
  return lines;
};

export const generateStream = (def: StreamDef): string => {
  const lines = [HEADER];
  lines.push(`import { type FastifyInstance } from 'fastify';\n`);
  const fnName = camelCase(def.name);
  const hasTransform = !!def.transform?.fields;

  lines.push(...genTransform(def));

  lines.push(`export const ${fnName}Stream = async (app: FastifyInstance): Promise<void> => {`);

  if (def.type === 'sse') {
    lines.push(`  app.get('${def.path}', async (request, reply) => {`);
    lines.push(`    reply.raw.writeHead(200, {`);
    lines.push(`      'Content-Type': 'text/event-stream',`);
    lines.push(`      'Cache-Control': 'no-cache',`);
    lines.push(`      Connection: 'keep-alive',`);
    lines.push(`    });`);
    if (def.source?.entity) {
      lines.push(`    // Source: ${def.source.entity} (interval: ${def.source.interval ?? 'realtime'})`);
    }
    const send = hasTransform ? `transform${def.name}(data)` : 'data';
    lines.push(`    const send = (data: Record<string, unknown>): void => {`);
    lines.push(`      reply.raw.write(\`data: \${JSON.stringify(${send})}\\n\\n\`);`);
    lines.push(`    };`);
    lines.push(`    send({ status: 'connected' });`);
    lines.push(`  });`);
  } else if (def.type === 'websocket') {
    lines.push(`  app.get('${def.path}', { websocket: true }, (socket) => {`);
    if (def.source?.entity) {
      lines.push(`    // Source: ${def.source.entity} (realtime: ${def.source.realtime ?? false})`);
    }
    lines.push(`    socket.on('message', (msg: Buffer) => {`);
    lines.push(`      const data = JSON.parse(msg.toString());`);
    const wsData = hasTransform ? `transform${def.name}(data)` : 'data';
    lines.push(`      socket.send(JSON.stringify(${wsData}));`);
    lines.push(`    });`);
    lines.push(`  });`);
  } else {
    lines.push(`  // gRPC stream — implement with @grpc/grpc-js`);
    lines.push(`  console.log('${def.name} gRPC stream registered at ${def.path}');`);
  }

  lines.push(`};\n`);
  return lines.join('\n');
};
