/**
 * Watt App Generator — produces Platformatic Watt infrastructure files
 */

import type { ParsedSchema } from '../../index.js';

const HEADER = '// @generated by flusk-lang — DO NOT EDIT\n';

const toSnake = (s: string): string =>
  s.replace(/([a-z])([A-Z])/g, '$1_$2').toLowerCase().replace(/-/g, '_');

const toCamel = (s: string): string =>
  s.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());

export interface WattFile {
  path: string;
  content: string;
}

export const generateWattConfig = (): string => {
  return JSON.stringify({
    $schema: 'https://schemas.platformatic.dev/watt/3.0.0.json',
    server: { hostname: '0.0.0.0', port: '{PLT_SERVER_PORT}' },
    autoload: { path: 'apps' },
    logger: { level: '{PLT_LOG_LEVEL}' },
    cors: { origin: '{CORS_ORIGIN}', credentials: true },
  }, null, 2) + '\n';
};

export const generateRootPackageJson = (name: string): string => {
  return JSON.stringify({
    name: `@flusk/${toSnake(name)}`,
    version: '0.1.0',
    private: true,
    type: 'module',
    scripts: {
      start: 'wattpm start',
      dev: 'wattpm start --hot-reload',
      test: 'vitest run',
      'test:watch': 'vitest',
      migrate: 'node --import tsx apps/api/migrate.ts',
    },
    dependencies: {
      wattpm: '^3.0.0',
      'better-sqlite3': '^11.0.0',
      nanoid: '^5.0.0',
      pino: '^9.0.0',
      fastify: '^5.0.0',
    },
    devDependencies: {
      vitest: '^3.0.0',
      tsx: '^4.0.0',
      '@types/better-sqlite3': '^7.6.0',
    },
    engines: { node: '>=22.0.0' },
    pnpm: { onlyBuiltDependencies: ['better-sqlite3', 'esbuild', 'protobufjs'] },
  }, null, 2) + '\n';
};

export const generateApiPlatformaticJson = (): string => {
  return JSON.stringify({
    $schema: 'https://schemas.platformatic.dev/@platformatic/service/3.0.0.json',
    plugins: { paths: ['./plugins'] },
  }, null, 2) + '\n';
};

export const generateApiPackageJson = (): string => {
  return JSON.stringify({
    name: 'flusk-api',
    version: '0.1.0',
    type: 'module',
    dependencies: {
      'better-sqlite3': '^11.0.0',
      nanoid: '^5.0.0',
      pino: '^9.0.0',
    },
    devDependencies: {
      '@types/better-sqlite3': '^7.6.0',
    },
  }, null, 2) + '\n';
};

export const generateAppEntry = (schema: ParsedSchema): string => {
  const lines = [HEADER];
  lines.push(`import type { FastifyInstance } from 'fastify';`);
  lines.push(`import { initDatabase } from './db.js';`);
  lines.push('');

  // Import routes
  for (const route of schema.routes) {
    const camel = toCamel(route.name);
    lines.push(`import { ${camel}Routes } from '../src/routes/${route.name}.routes.js';`);
  }

  // Import middlewares
  for (const mw of schema.middlewares) {
    const camel = toCamel(mw.name);
    lines.push(`import { ${camel} } from '../src/middlewares/${mw.name}.middleware.js';`);
  }

  lines.push('');
  lines.push(`export default async function app(fastify: FastifyInstance): Promise<void> {`);
  lines.push(`  const db = initDatabase();`);
  lines.push(`  fastify.decorate('db', db);`);
  lines.push('');

  // Register middlewares
  for (const mw of schema.middlewares) {
    const camel = toCamel(mw.name);
    const hookMap: Record<string, string> = { request: 'onRequest', response: 'onResponse', error: 'onError' };
    const hook = hookMap[mw.phase] ?? 'onRequest';
    lines.push(`  fastify.addHook('${hook}', ${camel});`);
  }

  if (schema.middlewares.length > 0) lines.push('');

  // Register routes
  for (const route of schema.routes) {
    const camel = toCamel(route.name);
    lines.push(`  await fastify.register(${camel}Routes);`);
  }

  lines.push(`}`);
  lines.push('');
  return lines.join('\n');
};

export const generateDbModule = (): string => {
  const lines = [HEADER];
  lines.push(`import Database from 'better-sqlite3';`);
  lines.push(`import { readFileSync, readdirSync } from 'node:fs';`);
  lines.push(`import { join } from 'node:path';`);
  lines.push(`import { createChildLogger } from '../src/lib/logger.js';`);
  lines.push('');
  lines.push(`const log = createChildLogger('db');`);
  lines.push('');
  lines.push(`let db: Database.Database | null = null;`);
  lines.push('');
  lines.push(`export const initDatabase = (path = ':memory:'): Database.Database => {`);
  lines.push(`  if (db) return db;`);
  lines.push(`  db = new Database(path);`);
  lines.push(`  db.pragma('journal_mode = WAL');`);
  lines.push(`  db.pragma('foreign_keys = ON');`);
  lines.push(`  log.info({ path }, 'Database initialized');`);
  lines.push(`  return db;`);
  lines.push(`};`);
  lines.push('');
  lines.push(`export const runMigrations = (db: Database.Database, migrationsDir: string): void => {`);
  lines.push(`  const files = readdirSync(migrationsDir)`);
  lines.push(`    .filter((f) => f.endsWith('.sql'))`);
  lines.push(`    .sort();`);
  lines.push('');
  lines.push(`  db.exec('CREATE TABLE IF NOT EXISTS _migrations (name TEXT PRIMARY KEY, applied_at TEXT NOT NULL DEFAULT (datetime(\\'now\\')));');`);
  lines.push('');
  lines.push(`  for (const file of files) {`);
  lines.push(`    const applied = db.prepare('SELECT 1 FROM _migrations WHERE name = ?').get(file);`);
  lines.push(`    if (applied) continue;`);
  lines.push(`    const sql = readFileSync(join(migrationsDir, file), 'utf8');`);
  lines.push(`    db.exec(sql);`);
  lines.push(`    db.prepare('INSERT INTO _migrations (name) VALUES (?)').run(file);`);
  lines.push(`    log.info({ migration: file }, 'Applied migration');`);
  lines.push(`  }`);
  lines.push(`};`);
  lines.push('');
  lines.push(`export const getDatabase = (): Database.Database => {`);
  lines.push(`  if (!db) throw new Error('Database not initialized');`);
  lines.push(`  return db;`);
  lines.push(`};`);
  lines.push('');
  return lines.join('\n');
};

export const generateMigrateScript = (): string => {
  const lines = [HEADER];
  lines.push(`import { initDatabase, runMigrations } from './db.js';`);
  lines.push(`import { join, dirname } from 'node:path';`);
  lines.push(`import { fileURLToPath } from 'node:url';`);
  lines.push('');
  lines.push(`const __dirname = dirname(fileURLToPath(import.meta.url));`);
  lines.push(`const dbPath = process.env.DATABASE_PATH ?? join(__dirname, '..', 'data.db');`);
  lines.push(`const db = initDatabase(dbPath);`);
  lines.push(`runMigrations(db, join(__dirname, 'migrations'));`);
  lines.push(`console.log('Migrations complete');`);
  lines.push('');
  return lines.join('\n');
};

export const generateLoggerLib = (): string => {
  const lines = [HEADER];
  lines.push(`import pino from 'pino';`);
  lines.push('');
  lines.push(`const rootLogger = pino({ level: process.env.LOG_LEVEL ?? 'info' });`);
  lines.push('');
  lines.push(`export const createChildLogger = (name: string): pino.Logger => {`);
  lines.push(`  return rootLogger.child({ component: name });`);
  lines.push(`};`);
  lines.push('');
  return lines.join('\n');
};

export const generateEnvFile = (): string => {
  return [
    'PLT_SERVER_PORT=3042',
    'PLT_LOG_LEVEL=info',
    'CORS_ORIGIN=http://localhost:5173',
    'DATABASE_PATH=./data.db',
    '',
  ].join('\n');
};

export const generateAllWattFiles = (schema: ParsedSchema, projectName: string): WattFile[] => {
  return [
    { path: 'watt.json', content: generateWattConfig() },
    { path: 'package.json', content: generateRootPackageJson(projectName) },
    { path: '.env.sample', content: generateEnvFile() },
    { path: 'apps/api/platformatic.json', content: generateApiPlatformaticJson() },
    { path: 'apps/api/package.json', content: generateApiPackageJson() },
    { path: 'apps/api/app.ts', content: generateAppEntry(schema) },
    { path: 'apps/api/db.ts', content: generateDbModule() },
    { path: 'apps/api/migrate.ts', content: generateMigrateScript() },
    { path: 'src/lib/logger.ts', content: generateLoggerLib() },
  ];
};
