// @generated by flusk-lang — DO NOT EDIT

/**
 * API Reference page generator — embeds OpenAPI spec using Scalar
 */

export const generateApiReference = (): string => {
  const lines: string[] = ['<!-- @generated by flusk-lang — DO NOT EDIT -->', ''];
  lines.push('# API Reference', '');
  lines.push('<script setup>');
  lines.push("import { onMounted } from 'vue';");
  lines.push('');
  lines.push('onMounted(() => {');
  lines.push("  const el = document.getElementById('scalar-api');");
  lines.push('  if (!el) return;');
  lines.push("  const script = document.createElement('script');");
  lines.push("  script.src = 'https://cdn.jsdelivr.net/npm/@scalar/api-reference';");
  lines.push('  document.head.appendChild(script);');
  lines.push('});');
  lines.push('</script>');
  lines.push('');
  lines.push('<div id="scalar-api">');
  lines.push('');
  lines.push('::: tip');
  lines.push('The interactive API reference loads from the generated OpenAPI spec.');
  lines.push('Run `flusk-lang openapi` to generate the spec first.');
  lines.push(':::');
  lines.push('');
  lines.push('</div>');
  lines.push('');
  lines.push('<scalar-api-reference');
  lines.push('  spec-url="./openapi.yaml"');
  lines.push('/>');
  lines.push('');
  return lines.join('\n');
};
