// @generated by flusk-lang — DO NOT EDIT

/**
 * Architecture overview page generator with Mermaid diagrams
 */

import type { ParsedSchema } from '../../index.js';

const toPascal = (s: string): string =>
  s.split(/[-_ ]+/).map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join('');

const sanitizeId = (s: string): string => s.replace(/[^a-zA-Z0-9]/g, '_');

export const generateEntityRelations = (schema: ParsedSchema): string => {
  const lines: string[] = ['<!-- @generated by flusk-lang — DO NOT EDIT -->', ''];
  lines.push('# Entity Relations', '');
  lines.push('```mermaid');
  lines.push('erDiagram');
  for (const entity of schema.entities) {
    const name = toPascal(entity.name);
    if (entity.relations) {
      for (const rel of entity.relations) {
        const target = toPascal(rel.entity);
        const card = rel.type === 'belongsTo' ? '}o--||' : '}o--o{';
        lines.push(`  ${name} ${card} ${target} : "${rel.foreignKey}"`);
      }
    }
  }
  lines.push('```', '');
  return lines.join('\n');
};

export const generateEventFlow = (schema: ParsedSchema): string => {
  const lines: string[] = ['<!-- @generated by flusk-lang — DO NOT EDIT -->', ''];
  lines.push('# Event Flow', '');
  lines.push('```mermaid');
  lines.push('graph LR');
  for (const event of schema.events) {
    const eid = sanitizeId(event.name);
    if (event.publish) {
      for (const pub of event.publish) {
        const tid = sanitizeId(pub.trigger);
        lines.push(`  ${tid}[${pub.trigger}] --> ${eid}[${event.name}]`);
      }
    }
    if (event.subscribe) {
      const hid = sanitizeId(event.subscribe.handler);
      lines.push(`  ${eid}[${event.name}] --> ${hid}[${event.subscribe.handler}]`);
    }
  }
  lines.push('```', '');
  return lines.join('\n');
};

export const generateDataFlow = (schema: ParsedSchema): string => {
  const lines: string[] = ['<!-- @generated by flusk-lang — DO NOT EDIT -->', ''];
  lines.push('# Data Flow', '');
  lines.push('```mermaid');
  lines.push('graph TD');

  for (const route of schema.routes) {
    const rid = sanitizeId(route.name);
    for (const op of route.operations) {
      const fid = sanitizeId(op.call);
      lines.push(`  ${rid}["${route.basePath}"] --> ${fid}["${op.call}"]`);
    }
  }

  // Functions that call entities
  for (const fn of schema.functions) {
    const fid = sanitizeId(fn.name);
    for (const step of fn.steps) {
      if (step.call) {
        const sid = sanitizeId(step.call);
        lines.push(`  ${fid}["${fn.name}"] --> ${sid}["${step.call}"]`);
      }
    }
  }

  lines.push('```', '');
  return lines.join('\n');
};
