// @generated by flusk-lang — DO NOT EDIT

/**
 * Entity documentation page generator
 */

import type { EntityDef } from '../../parsers/entity.parser.js';

const toKebab = (s: string): string =>
  s.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();

const toPascal = (s: string): string =>
  s.split(/[-_ ]+/).map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join('');

export const generateEntityDoc = (entity: EntityDef): string => {
  const lines: string[] = ['<!-- @generated by flusk-lang — DO NOT EDIT -->', ''];
  const name = toPascal(entity.name);
  lines.push(`# ${name}`);
  if (entity.description) lines.push('', `> ${entity.description}`);
  lines.push('');

  // Fields table
  lines.push('## Fields', '');
  lines.push('| Field | Type | Required | Default | Description |');
  lines.push('|-------|------|----------|---------|-------------|');
  lines.push(`| id | uuid | yes | auto | Primary key |`);
  for (const f of entity.fields) {
    const type = f.type === 'enum' && f.values ? f.values.join(' \\| ') : f.type;
    const req = f.required === false ? 'no' : 'yes';
    const def = f.default !== undefined ? String(f.default) : '-';
    const desc = f.description ?? '-';
    lines.push(`| ${f.name} | ${type} | ${req} | ${def} | ${desc} |`);
  }
  lines.push(`| createdAt | datetime | yes | auto | Creation timestamp |`);
  lines.push(`| updatedAt | datetime | yes | auto | Last update timestamp |`);
  lines.push('');

  // Relations
  if (entity.relations && entity.relations.length > 0) {
    lines.push('## Relations', '');
    for (const r of entity.relations) {
      lines.push(`- ${r.type} **${toPascal(r.entity)}** (via \`${r.foreignKey}\`)`);
    }
    lines.push('');
  }

  // Queries
  if (entity.queries && entity.queries.length > 0) {
    lines.push('## Queries', '');
    for (const q of entity.queries) {
      lines.push(`- \`${q.name}\`: \`${q.sql}\``);
    }
    lines.push('');
  }

  // API Endpoints
  const kebab = toKebab(entity.name);
  lines.push('## API Endpoints', '');
  lines.push(`- \`GET /api/${kebab}\` — List all`);
  lines.push(`- \`POST /api/${kebab}\` — Create`);
  lines.push(`- \`GET /api/${kebab}/:id\` — Get by ID`);
  lines.push(`- \`PUT /api/${kebab}/:id\` — Update`);
  lines.push(`- \`DELETE /api/${kebab}/:id\` — Delete`);
  lines.push('');

  return lines.join('\n');
};
