// @generated by flusk-lang — DO NOT EDIT

/**
 * Event documentation page generator
 */

import type { EventDef } from '../../parsers/event.parser.js';

export const generateEventDoc = (event: EventDef): string => {
  const lines: string[] = ['<!-- @generated by flusk-lang — DO NOT EDIT -->', ''];
  lines.push(`# ${event.name}`);
  if (event.description) lines.push('', `> ${event.description}`);
  lines.push('');

  lines.push(`**Channel:** ${event.channel}`);
  if (event.topic) lines.push(`  \n**Topic:** \`${event.topic}\``);
  lines.push('');

  // Payload
  if (event.payload?.fields && event.payload.fields.length > 0) {
    lines.push('## Payload', '');
    lines.push('| Field | Type | Required | Description |');
    lines.push('|-------|------|----------|-------------|');
    for (const f of event.payload.fields) {
      const req = f.required === false ? 'no' : 'yes';
      const desc = f.description ?? '-';
      lines.push(`| ${f.name} | ${f.type} | ${req} | ${desc} |`);
    }
    lines.push('');
  }

  // Publish rules
  if (event.publish && event.publish.length > 0) {
    lines.push('## Published By', '');
    for (const pub of event.publish) {
      lines.push(`- Trigger: \`${pub.trigger}\``);
    }
    lines.push('');
  }

  // Subscribe
  if (event.subscribe) {
    lines.push('## Subscriber', '');
    lines.push(`- **Handler:** \`${event.subscribe.handler}\``);
    if (event.subscribe.retry) {
      lines.push(`- **Retry:** max ${event.subscribe.retry.maxAttempts} attempts (${event.subscribe.retry.backoff})`);
    }
    if (event.subscribe.deadLetter) {
      lines.push(`- **Dead Letter:** \`${event.subscribe.deadLetter}\``);
    }
    lines.push('');
  }

  return lines.join('\n');
};
