// @generated by flusk-lang — DO NOT EDIT

/**
 * Function documentation page generator
 */

import type { FunctionDef } from '../../parsers/function.parser.js';

const stepLabel = (step: { id: string; call?: string; action?: string }): string => {
  if (step.call) return `${step.id}: call ${step.call}`;
  if (step.action) return `${step.id}: ${step.action}`;
  return step.id;
};

export const generateFunctionDoc = (fn: FunctionDef): string => {
  const lines: string[] = ['<!-- @generated by flusk-lang — DO NOT EDIT -->', ''];
  lines.push(`# ${fn.name}`);
  if (fn.description) lines.push('', `> ${fn.description}`);
  lines.push('');

  // Inputs
  if (fn.inputs && fn.inputs.length > 0) {
    lines.push('## Inputs', '');
    lines.push('| Parameter | Type | Required |');
    lines.push('|-----------|------|----------|');
    for (const inp of fn.inputs) {
      lines.push(`| ${inp.name} | ${inp.type} | yes |`);
    }
    lines.push('');
  }

  // Steps as mermaid
  if (fn.steps.length > 0) {
    lines.push('## Steps', '');
    lines.push('```mermaid');
    lines.push('graph TD');
    const ids = fn.steps.map((_, i) => String.fromCharCode(65 + i));
    for (let i = 0; i < fn.steps.length; i++) {
      const step = fn.steps[i]!;
      const id = ids[i]!;
      const label = stepLabel(step);
      if (i === 0) {
        lines.push(`  ${id}[${label}]`);
      }
      if (i > 0) {
        lines.push(`  ${ids[i - 1]} --> ${id}[${label}]`);
      }
    }
    lines.push('```');
    lines.push('');
  }

  // Output
  if (fn.output) {
    lines.push('## Output', '');
    lines.push(`Type: \`${fn.output.type}\``);
    lines.push('');
  }

  // Errors
  if (fn.errors && fn.errors.length > 0) {
    lines.push('## Error Handling', '');
    for (const e of fn.errors) {
      lines.push(`- **${e.type}**: ${e.action}`);
    }
    lines.push('');
  }

  return lines.join('\n');
};
