// @generated by flusk-lang — DO NOT EDIT

/**
 * Docs generator orchestrator — produces a VitePress site from parsed schemas
 */

import type { ParsedSchema } from '../../index.js';
import type { WriteFileFn } from '../../commands/types.js';
import { join } from 'node:path';
import { generateEntityDoc } from './entity-docs.gen.js';
import { generateFunctionDoc } from './function-docs.gen.js';
import { generateRouteDoc } from './route-docs.gen.js';
import { generateEventDoc } from './event-docs.gen.js';
import { generateVitepressConfig } from './vitepress-config.gen.js';
import { generateApiReference } from './api-reference.gen.js';
import {
  generateEntityRelations,
  generateEventFlow,
  generateDataFlow,
} from './architecture.gen.js';

const toKebab = (s: string): string =>
  s.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();

const generateIndexPage = (schema: ParsedSchema): string => {
  const lines: string[] = ['<!-- @generated by flusk-lang — DO NOT EDIT -->', ''];
  lines.push('---');
  lines.push('layout: home');
  lines.push('hero:');
  lines.push('  name: Flusk Docs');
  lines.push("  text: Auto-generated from YAML schemas");
  lines.push("  tagline: Entities, functions, routes, events & architecture");
  lines.push('---');
  lines.push('');
  lines.push('## Overview', '');
  lines.push(`- **${schema.entities.length}** entities`);
  lines.push(`- **${schema.functions.length}** functions`);
  lines.push(`- **${schema.routes.length}** routes`);
  lines.push(`- **${schema.events.length}** events`);
  lines.push(`- **${schema.workers.length}** workers`);
  lines.push(`- **${schema.streams.length}** streams`);
  lines.push('');
  return lines.join('\n');
};

const generatePackageJson = (): string => JSON.stringify({
  name: 'flusk-docs',
  private: true,
  scripts: {
    'docs:dev': 'vitepress dev',
    'docs:build': 'vitepress build',
    'docs:preview': 'vitepress preview',
  },
  devDependencies: {
    vitepress: '^1.5.0',
    vue: '^3.5.0',
  },
}, null, 2) + '\n';

export const generateDocs = (
  schema: ParsedSchema,
  docsDir: string,
  writeFile: WriteFileFn,
): void => {
  // Package.json
  writeFile(join(docsDir, 'package.json'), generatePackageJson());

  // VitePress config
  writeFile(join(docsDir, '.vitepress', 'config.ts'), generateVitepressConfig(schema));

  // Index
  writeFile(join(docsDir, 'index.md'), generateIndexPage(schema));

  // Entities
  for (const entity of schema.entities) {
    writeFile(join(docsDir, 'entities', `${toKebab(entity.name)}.md`), generateEntityDoc(entity));
  }

  // Functions
  for (const fn of schema.functions) {
    writeFile(join(docsDir, 'functions', `${toKebab(fn.name)}.md`), generateFunctionDoc(fn));
  }

  // Routes
  for (const route of schema.routes) {
    writeFile(join(docsDir, 'routes', `${toKebab(route.name)}.md`), generateRouteDoc(route));
  }

  // Events
  for (const event of schema.events) {
    writeFile(join(docsDir, 'events', `${toKebab(event.name)}.md`), generateEventDoc(event));
  }

  // Architecture
  writeFile(join(docsDir, 'architecture', 'entity-relations.md'), generateEntityRelations(schema));
  writeFile(join(docsDir, 'architecture', 'data-flow.md'), generateDataFlow(schema));
  writeFile(join(docsDir, 'architecture', 'event-flow.md'), generateEventFlow(schema));

  // API Reference
  writeFile(join(docsDir, 'api-reference.md'), generateApiReference());
};
