// @generated by flusk-lang — DO NOT EDIT

/**
 * Route documentation page generator
 */

import type { RouteDef } from '../../parsers/route.parser.js';

export const generateRouteDoc = (route: RouteDef): string => {
  const lines: string[] = ['<!-- @generated by flusk-lang — DO NOT EDIT -->', ''];
  const fullPath = route.basePath;
  lines.push(`# ${fullPath}`);
  if (route.entity) lines.push('', `> CRUD routes for **${route.entity}**`);
  lines.push('');

  if (route.auth) {
    lines.push(`**Authentication:** ${route.auth}`, '');
  }

  lines.push('## Operations', '');
  for (const op of route.operations) {
    const method = op.method.toUpperCase();
    lines.push(`### ${method} ${op.path}`);
    lines.push('');
    lines.push(`- **Handler:** \`${op.call}\``);
    if (op.input) lines.push(`- **Input:** \`${op.input}\``);
    if (op.description) lines.push(`- **Description:** ${op.description}`);
    if (route.auth) lines.push(`- **Auth:** ${route.auth}`);
    lines.push('');
  }

  return lines.join('\n');
};
