// @generated by flusk-lang — DO NOT EDIT

/**
 * VitePress config generator
 */

import type { ParsedSchema } from '../../index.js';

const toKebab = (s: string): string =>
  s.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();

interface SidebarItem {
  text: string;
  link?: string;
  items?: SidebarItem[];
}

const buildSection = (
  title: string,
  prefix: string,
  names: string[],
): SidebarItem => ({
  text: title,
  items: names.map((n) => ({
    text: n,
    link: `/${prefix}/${toKebab(n)}`,
  })),
});

export const generateVitepressConfig = (schema: ParsedSchema): string => {
  const sidebar: SidebarItem[] = [
    { text: 'Overview', link: '/' },
  ];

  if (schema.entities.length > 0) {
    sidebar.push(buildSection('Entities', 'entities', schema.entities.map((e) => e.name)));
  }
  if (schema.functions.length > 0) {
    sidebar.push(buildSection('Functions', 'functions', schema.functions.map((f) => f.name)));
  }
  if (schema.routes.length > 0) {
    sidebar.push(buildSection('Routes', 'routes', schema.routes.map((r) => r.name)));
  }
  if (schema.events.length > 0) {
    sidebar.push(buildSection('Events', 'events', schema.events.map((e) => e.name)));
  }

  sidebar.push(
    {
      text: 'Architecture',
      items: [
        { text: 'Entity Relations', link: '/architecture/entity-relations' },
        { text: 'Data Flow', link: '/architecture/data-flow' },
        { text: 'Event Flow', link: '/architecture/event-flow' },
      ],
    },
    { text: 'API Reference', link: '/api-reference' },
  );

  const config = `// @generated by flusk-lang — DO NOT EDIT

import { defineConfig } from 'vitepress';

export default defineConfig({
  title: 'Flusk Docs',
  description: 'Auto-generated documentation from YAML schemas',
  themeConfig: {
    sidebar: ${JSON.stringify(sidebar, null, 6)},
    search: {
      provider: 'local',
    },
    nav: [
      { text: 'Home', link: '/' },
      { text: 'API Reference', link: '/api-reference' },
    ],
  },
});
`;

  return config;
};
