// @generated by flusk-lang — DO NOT EDIT

import { createFileRoute, Link } from '@tanstack/react-router'
import { createServerFn } from '@tanstack/start'
import { Suspense } from 'react'

// Server function — generated from loader config
const loadTeamMember = createServerFn('GET', async (params: { tenant: string; memberId: string }) => {
  const { getTeamMember } = await import('~/repositories/team-member.repository')
  return getTeamMember(params.tenant, params.memberId)
})

export const Route = createFileRoute('/$tenant/team/$memberId')({
  component: TeamMemberCard,
  loader: ({ params }) => loadTeamMember({ tenant: params.tenant, memberId: params.memberId }),
  head: ({ loaderData }) => ({
    meta: [{ title: `${loaderData?.name} — Team` }],
  }),
})

function TeamMemberCard() {
  const member = Route.useLoaderData()

  return (
    <main
      role="article"
      aria-label="Team member profile"
      className="mx-auto w-full max-w-lg px-4 py-6 sm:py-8 md:max-w-xl md:py-10 lg:max-w-2xl lg:py-12"
    >
      <article className="flex flex-col items-center gap-4 rounded-xl border bg-card p-5 shadow-sm sm:gap-5 sm:p-6 md:p-8 lg:p-10">
        {/* Avatar — responsive sizes, accessible */}
        <div className="relative">
          {member.avatar ? (
            <img
              src={member.avatar}
              alt={`${member.name} profile photo`}
              loading="lazy"
              className="h-20 w-20 rounded-full object-cover sm:h-20 md:h-24 lg:h-[120px] lg:w-[120px]"
            />
          ) : (
            <div
              className="flex h-20 w-20 items-center justify-center rounded-full bg-primary/10 text-lg font-bold text-primary sm:h-20 md:h-24 md:w-24 md:text-xl lg:h-[120px] lg:w-[120px] lg:text-2xl"
              aria-hidden="true"
            >
              {member.name
                .split(' ')
                .map((n: string) => n[0])
                .join('')
                .toUpperCase()}
            </div>
          )}
        </div>

        {/* Header — semantic h1, responsive sizing */}
        <h1 className="text-center text-xl font-bold tracking-tight sm:text-xl md:text-2xl lg:text-3xl">
          {member.name}
        </h1>

        {/* Role Badge */}
        <span className="inline-flex items-center rounded-full border border-primary/30 px-3 py-1 text-xs font-medium text-primary">
          {member.role}
        </span>

        {/* Bio — responsive line clamp, expandable */}
        <Suspense fallback={<div className="h-12 animate-pulse rounded bg-muted" />}>
          <ExpandableBio bio={member.bio} />
        </Suspense>

        {/* Stats — mobile: stack, md: grid-2, lg: grid-3 */}
        <div
          className="grid w-full gap-3 sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-3"
          role="list"
          aria-label="Member statistics"
        >
          <StatCard icon="folder" label="Projects" value={member.stats.projects} />
          <StatCard icon="git-commit" label="Contributions" value={member.stats.contributions} />
          <StatCard icon="check-circle" label="Reviews" value={member.stats.reviews} />
        </div>

        {/* Actions — mobile: stack, md: inline */}
        <div className="flex w-full flex-col gap-2 pt-2 md:flex-row md:justify-center md:gap-3">
          <Link
            to={`/${member.tenant}/messages/new`}
            search={{ to: member.id }}
            className="inline-flex items-center justify-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
          >
            <MailIcon className="h-4 w-4" aria-hidden="true" />
            Send Message
          </Link>
          <Link
            to={`/${member.tenant}/team/${member.id}/full`}
            className="inline-flex items-center justify-center gap-2 rounded-lg border bg-background px-4 py-2.5 text-sm font-medium transition-colors hover:bg-accent focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
          >
            <ExternalLinkIcon className="h-4 w-4" aria-hidden="true" />
            View Profile
          </Link>
        </div>
      </article>
    </main>
  )
}

/* ── Subcomponents ── */

function ExpandableBio({ bio }: { bio: string }) {
  const [expanded, setExpanded] = React.useState(false)

  return (
    <div className="w-full text-center">
      <p
        className={`text-sm text-muted-foreground transition-all ${
          expanded ? '' : 'line-clamp-3 sm:line-clamp-3 md:line-clamp-5 lg:line-clamp-none'
        }`}
      >
        {bio}
      </p>
      <button
        onClick={() => setExpanded(!expanded)}
        className="mt-1 text-xs text-primary hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring lg:hidden"
        aria-expanded={expanded}
      >
        {expanded ? 'Show less' : 'Read more'}
      </button>
    </div>
  )
}

function StatCard({ icon, label, value }: { icon: string; label: string; value: number }) {
  return (
    <div
      role="listitem"
      className="flex items-center gap-3 rounded-lg border bg-background p-3 transition-colors hover:bg-accent/50"
    >
      <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-md bg-primary/10 text-primary" aria-hidden="true">
        <IconByName name={icon} className="h-4 w-4" />
      </div>
      <div>
        <p className="text-xs text-muted-foreground">{label}</p>
        <p className="text-lg font-bold tabular-nums">{value.toLocaleString()}</p>
      </div>
    </div>
  )
}

/* ── Icons (inline SVG) ── */

import React from 'react'

function IconByName({ name, className }: { name: string; className?: string }) {
  const icons: Record<string, React.ReactNode> = {
    folder: <path d="M22 19a2 2 0 01-2 2H4a2 2 0 01-2-2V5a2 2 0 012-2h5l2 3h9a2 2 0 012 2z" />,
    'git-commit': <><circle cx="12" cy="12" r="4" /><line x1="1.05" y1="12" x2="7" y2="12" /><line x1="17.01" y1="12" x2="22.96" y2="12" /></>,
    'check-circle': <><path d="M22 11.08V12a10 10 0 11-5.93-9.14" /><polyline points="22 4 12 14.01 9 11.01" /></>,
  }
  return (
    <svg className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      {icons[name]}
    </svg>
  )
}

function MailIcon({ className, ...props }: React.SVGProps<SVGSVGElement>) {
  return (
    <svg className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}>
      <rect x="2" y="4" width="20" height="16" rx="2" /><polyline points="22,7 12,13 2,7" />
    </svg>
  )
}

function ExternalLinkIcon({ className, ...props }: React.SVGProps<SVGSVGElement>) {
  return (
    <svg className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}>
      <path d="M18 13v6a2 2 0 01-2 2H5a2 2 0 01-2-2V8a2 2 0 012-2h6" /><polyline points="15 3 21 3 21 9" /><line x1="10" y1="14" x2="21" y2="3" />
    </svg>
  )
}
